osbuild/image-builder-frontend

.travis.yml, .travis/custom_release.sh, package.json
The starter app has been updated over the last few months and new
options are required in the `scripts` section of `package.json`.
Bring the `scripts` section in line with the starter app to fix some
issues around routing requests to `/beta` in CI.
Signed-off-by: Major Hayden <major@redhat.com>
=> 📦 package.json: Update scripts section

src/SmartComponents/CreateImageWizard/CreateImageWizard.js
We had issues in composer a while back with VHDX in AWS and we have been
using raw images since then.
Signed-off-by: Major Hayden <major@redhat.com>
=> 📦 Denote AWS image as raw

.eslintrc.yml, src/SmartComponents/redux/reducers.js, src/test/SmartComponents/redux/actions.test.js, src/test/SmartComponents/redux/reducers.test.js
This was a bit confusing because in the inline documentation I wrote
used state as a key. However this changed to status pretty early on and
I forgot to update it.
=> test: Make sure the status of a compose is called status

.travis.yml
This reverts commit bd99a90faa8188eb8c9ada6b68c403fff6a800c2.
While this is common in cockpit's projects, osbuild projects refrain
from rebasing branches.
Rebasing on master as it happens to be when the test is running, leaves
you in a state where you neither know that the branch itself is working,
nor that it will work when you actually do merge it later, because
master might have changed in between.
=> Revert "Update travis config file to rebase on master before test running"

src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
gets rid of:
Warning: You seem to have overlapping act() calls, this is not
supported. Be sure to await previous act() calls before making a
new one.
=> tests: Redo waiting for elements to be removed to resolve warning

src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js, src/PresentationalComponents/CreateImageWizard/WizardStepRegistration.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.scss, src/PresentationalComponents/CreateImageWizard/WizardStepUploadAWS.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
Refactors wizard steps to more closely align to the [design document](https://docs.google.com/presentation/d/1YUPsj01oafTfnTqlihf6-stGbuINfQSIN9K9a24-byY/edit?usp=sharing), while also adopting some of the clouddot guidelines (i.e. adds a header to each step).
Also updates how js files are organized to align with recent refactoring made in [cockpit-composer](https://github.com/osbuild/cockpit-composer/tree/master/components/Wizard), while also adopting the SmartComponents and PresentationalComponents organization in the clouddot sample app. 
@Gundersanne I see that you made updates to the AWS form elements in #60. It looks like that PR replaces all of the AWS form inputs with the one for account ID. If that's the case, I think that probably what makes sense is to have the first step …
=> Wizard refactor

src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/PresentationalComponents/Release/Release.js, src/SmartComponents/ImagesTable/ImagesTable.js
Updates include:
- Release column:
- Adding a blue label
- Adding a user-friendly short label (e.g. RHEL 8 vs rhel-8)
- Target column
- Adding a user-friendly long label (e.g. Amazon Web Services vs aws)
- Adding more PF toolbar components to update the toolbar layout. This still leaves the clouddot `<TableToolbar>` component, which I'm not 💯% positive is the right component to use over PF's `<Toolbar>`, especially given the large margin before the Create button.
=> Table view updates

src/SmartComponents/CreateImageWizard/CreateImageWizard.js
TLDR; before this update the user always has to scroll to get to
the footer actions in the wizard.
There's a weird nested page section thing happening which results
in the wizard body+footer being 100% of the height of the main content
area, but when you add the wizard header as a separate section above
the 100% height wizard body+footer, the header pushes the wizard
contents down so that the bottom portion of the wizard (equal to the
height of the header, and roughly the height of the footer) is always out
of view. This means that the user always has to scroll to get to the
footer.
=> Adds a Stack layout to have the wizard footer visible

package.json
The later versions also recognize `main` as a beta branch.
=> package.json: Update frontend-components-config

src/SmartComponents/CreateImageWizard/CreateImageWizard.js
With the updates made in #66, the stack layout isn't needed. These updates bring the wizard layout closer to this [PF html example](https://www.patternfly.org/v4/components/wizard/html-demos/in-page/) of a full page wizard. The classes used for the wizard body page section don't appear to be supported in the `<PageSection>` component yet, so for now this just adds the html: `<section className="pf-c-page__main-wizard pf-m-limit-width">`.
=> Removes stack layout from wizard

src/SmartComponents/CreateImageWizard/CreateImageWizard.js
Once we have multiple image types we need to make this dynamic based on
upload type. But qcow2 doesn't work under any circumstance so let's use
ami.
=> CreateImageWizard: Change image type to ami

.travis/custom_release.sh
Once we fork prod in imagebuilder to be a separate version from stage, let's do the same with the frontend. Until that point let's just have main push to both stage and prod beta.
=> travis: Let main push to prod-beta as well

src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/PresentationalComponents/ImagesTable/Release.js
image-builder has recently got support for building CentOS Stream 8 images.
This commit adds the option to build these images in the frontend.
I'm not entirely sure what I'm doing, so please review carefully. :) Also, I'm not sure if the backend part is deployed yet...
=> add support for CentOS Stream 8

package.json, src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js, src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.scss, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/PresentationalComponents/CreateImageWizard/WizardStepUploadAWS.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.scss, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The user can now select between multiple upload providers. AWS, Azure, and Google. The selection uses tiles and the user can select one or more destinations. Currently, only aws supports setting the upload parameters.
The icons point to files hosted on cloud.redhat.com.
=> Support multiple cloud destinations

package.json, src/PresentationalComponents/CreateImageWizard/WizardStepPackages.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/api.js, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The additional package selection step is added to the create image wizard. Users can now query for packages and select them from a list. These packages are not yet passed into the blueprint customizations and are just for display. Tests have been updated and added.
Currently, we are missing the empty state strings and the search bar error for too few characters. I will create issues to capture these but we will probably need to rewrite this component using html and patternfly's css classes so I don't think it is feasible before the demo is due.
@Gundersanne @katierik do you think we should alphabetically sort the list of selected packages or leave it in the user selected order?
=> Select packages

src/App.js
This should fix the issue where if you go to the page directly, and are not logged in, you'd get the signup form after logging in even if you were authorized to use the service.
Essentially this waits until there's an active session.
https://user-images.githubusercontent.com/11140201/109670265-3aa0bc00-7b73-11eb-8a8e-c47045536dd0.mp4
=> App: Wait for user active session before checking permission

src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/PresentationalComponents/CreateImageWizard/WizardStepUploadGoogle.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The user can now specify their authentication settings for Google Cloud Platform.
Tests and validation are still needed for this PR.
=> CreateImageWizard: add google upload step

src/PresentationalComponents/CreateImageWizard/ImageWizardFooter.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The user should not be able to continue without selecting an upload destination. The only issue here is that, while the Next button is disabled, the user can still select other steps in the sidebar. This fixes #110
=> CreateImageWizard: validate upload destination

src/PresentationalComponents/CreateImageWizard/ImageWizardFooter.js, src/PresentationalComponents/CreateImageWizard/WizardStepRegistration.js, src/PresentationalComponents/CreateImageWizard/WizardStepReview.js, src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
If register now is selected, an activation key is required. If no activation key is entered the Next and Create buttons are disabled.
Also, if the activation key is empty an error message will appear to prompt the user to enter an activation key.
The subscription errors variable is removed in favor of declaring the error message directly in the registration step component. The validateSubscription function is removed in favor of validating the activation key field on change.
This fixes #114 and is dependent on #112
=> Validate subscription activation key

src/SmartComponents/ImagesTable/ImagesTable.js
Update the message now that we support CentOS Stream, Azure+GCP support as well as package selection.
=> ImagesTable: update empty-table message

src/PresentationalComponents/ImagesTable/ImageBuildStatus.js, src/test/SmartComponents/ImagesTable/ImagesTable.test.js
This is related to:
- https://github.com/osbuild/image-builder/pull/163
- https://github.com/osbuild/osbuild-composer/pull/1319
osbuild-composer and as a result also Image Builder are returning an invalid `image_status.status` value "running" for composes which are in progress.
Extend the front-end to handle all valid `image_status.status` values, specifically also "building", "uploading" and "registering". Also keep support for the invalid value "running" for some time to ensure backward compatibility with older osbuild-composer versions.
Modify test cases in `ImagesTable.test.js` to verify all possible `image_status.status` values. Also modify the `image_status` values used for testing to what is actually returned by osbuild-composer Cloud API and as a result also by Image Builder's …
=> Handle all valid image_status.status values

src/SmartComponents/CreateImageWizard/CreateImageWizard.js, src/SmartComponents/ImagesTable/ImagesTable.js, src/SmartComponents/LandingPage/LandingPage.js, src/SmartComponents/LandingPage/LandingPage.scss, src/test/SmartComponents/LandingPage/LandingPage.test.js
Links to documentation are added. Some of the styling does not exactly match the mockups but is the default styling for the patternfly components. @katierik any thoughts?
=> Add documentation links

src/Components/CreateImageWizard/CreateImageWizard.js
The patternfly Wizard component's description is wrapped in a p tag. The patternfly Text component also uses a p tag. A p tag should not be nested inside another p tag.
=> CreateImageWizard: remove nested p tag

README.md
Spinning up the frontend is a lot simpler than the backend, so have dedicated
instructions to just do that.
=> README: split frontend and backend instructions

src/Components/ImagesTable/ImageLink.js, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
The images list now contains a link to the ec2 launch wizard for a successfully uploaded aws image.
=> ImagesTable: add link to launch uploaded aws image

src/Components/CreateImageWizard/CreateImageWizard.js
This should be changed in the api. But will take some more work. For now
just pass it as a number, that is what the api expects at this point in time.
=> CreateImageWizard: Pass organization as a number

src/Components/CreateImageWizard/WizardStepUploadGoogle.js, src/Components/CreateImageWizard/WizardStepUploadGoogle.scss
The Google Cloud Platform step's description is improved, the radio fields have more space separating them, and the text input is width limited now.
Fixes: #186
=> CreateImageWizard: improve google step

src/Components/CreateImageWizard/WizardStepPackages.js, src/Components/CreateImageWizard/WizardStepPackages.scss, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Update the text description and replace "options" with "packages". Also, add styling to increase the size of the available and chosen packages list.
This fixes some of the differences between the designs and the current work. Additional improvements will take more considerable work so this PR should close #188 in favor of #210 #211 #212 #213
=> CreateImageWizard: improve packages step

src/Components/ImagesTable/ImageLink.js, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
When an azure image is successfully uploaded the user is provided a link to view the image in the azure web portal.
=> ImagesTable: add azure image link

src/Components/ImagesTable/ImageLink.js, src/test/Components/ImagesTable/ImagesTable.test.js
When a gcp image is successfully uploaded the user needs to know the project id and image name. These are now displayed in the status section of the UI.
This is a minimal solution just to display the info until dropdowns for the image info can be implemented.
@katierik Do you have any thoughts on how to simply display this information for now?
=> ImagesTable: add gcp info

src/Components/CreateImageWizard/WizardStepImageOutput.js, src/Components/CreateImageWizard/WizardStepReview.js, src/Components/ImagesTable/Release.js
We should pull these labels/descriptions from the service, but let's do
that separately.
=> src: Rename RHEL 8.3 to just RHEL 8

src/Components/CreateImageWizard/WizardStepReview.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This fixes #190. I left the term "the image" for the google and aws steps since we already specify it as "your image" and duplicate wording sounds weird.
=> CreateImageWizard: use your image instead of the image

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/WizardStepReview.js
Registration is only enabled for RHEL images now. Also, the release/distro was not being properly displayed in the review screen. 
Fixes #139 #117
=> Remove registration step for CentOS images

package.json, src/store/index.js
jira: https://issues.redhat.com/browse/RHCLOUD-15228
This fixes an error when SPA is enabled and we navigate to image builder from different applications.
I've updated webpack config dependency. It contains some important modules bug fixes.
cc @Gundersanne @ochosi
=> Fix store already initialized error.

config/dev.webpack.config.js, config/prod.webpack.config.js
jira: https://issues.redhat.com/browse/RHCLOUD-15320
- add missing modules configuration to webpack config
The build was generating empy `fed-mods.json` file. This file is used by chrome to handle webpack container loading. If you use custom `moduleName` in the federated modules plugin, you also have to add that same string to the base webpack config. Otherwise, the config will be looking for different module names and creates an incorrect metadata file
Fixes this issue: 
cc @ochosi @Gundersanne
=> Add missing modules entry to webpack config.

src/Components/CreateImageWizard/formComponents/ReviewStep.js
Previously one could trick the state machine into showing the subscription section by first filling in the subscription information, then going back to the image type and changing it to CentOS.
Now we check if "rhel" is part of the image type (to hopefully also cover future RHEL offerings).
This may have to be extended in case RHEL for Edge or some other offering doesn't contain the "rhel" string.
=> Fix review page

.travis.yml
This avoids double builds on the npm-update PRs.
=> .travis.yml: Only build the main and prod-beta branch

devel/docker-compose.yml
The base url for the osbuild-worker container was missing the `https` protocol in the docker-compose file.
=> Containers: minor fix

devel/README.md, devel/config/grafana/dashboards/dashboard.yml, devel/config/grafana/dashboards/insights-dashboard.json, devel/config/grafana/datasources/datasource.yml, devel/config/prometheus/prometheus.yml, devel/docker-compose.yml
This PR adds integration of Prometheus and Grafana into the `devel` container stack. The Grafana dashboard was taken from the `image-builder` stack. This should hopefully make it easier to develop dashboards and alerts locally.
- Prometheus container
- Grafana container with preconfigured datasource and dashboard
=> Devel: Prometheus/Grafana integration

src/Components/CreateImageWizard/formComponents/AzureAuthButton.js
On authorization of image builder on azure, the user will be redirected to portal.azure.com. The response mode is changed to query instead of post.
Fixes: #350
=> CreateImageWizard: update azure redirect

src/Components/CreateImageWizard/CreateImageWizard.js
When image creation failed to start the wizard would get stuck in the saving state with no notice to the user. Now the user will get an error alert contain the status code and message. The wizard no longer gets stuck in the saving state.
Fixes #270
=> CreateImageWizard: add creation failure alert

.github/workflows/coverity_scan.yml
Github actions do not recognize @daily. Cron instead will explicitly run at 05:00
UTC.
=> workflows: fix cron schedule

.github/workflows/coverity_scan.yml
this will prevent the tool from scanning itself
=> ci: Extract Coverity Scan tools in /tmp

devel/.env, devel/config/backend/quotas.json, devel/config/composer/acl.yml, devel/config/composer/osbuild-composer.toml, devel/config/grafana/dashboards/dashboard.yml, devel/config/worker/osbuild-worker.toml, devel/config/worker/token, devel/docker-compose.yml
- make changes to use the `image-builder` composer client
- add a mock oauth server to simulate SSO `offline_token` exchange
- provide worker container with privileges (needed for loopback devices)
- add quota file
- remove duplicate grafana dashboard (causing errors in logs)
Note: this PR relies on the following PR https://github.com/osbuild/osbuild-composer/pull/2003
=> devel: update the 

src/Components/CreateImageWizard/steps/aws.js
=> CreateImageWizard: decrease aws account id field length

package-lock.json, package.json
Also, since many of our tests rely on a browser-like environment we need to explicitly set the jest testEnvironment as jsdom. jsdom simulates a browser environment unlike node which is jest's default test environment.
=> Update jest to 27.3.1

src/Components/CreateImageWizard/CreateImageWizard.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The composeAdded action includes a field 'insert'. When set to true `insert` will place the added compose at the beginning of the images list. The test is modified so the new composes are added to the beginning of the list.
Fixes #161
=> CreateImageWizard: insert new compose on top of images list

src/Components/ImagesTable/ImageBuildStatus.js
"Image build is pending" is more in line with the rest of our status texts.
=> ImagesTable: update pending text

src/Components/CreateImageWizard/formComponents/Packages.js
The addEventListener call needs to have the useCapture field set to true. The data-driven-forms patternfly 4 wizard will continue to the next step when the Enter key is pressed. If we add our keydownHandler as an event listener with useCapture set to True, the keydownHandler will trigger before the wizards handler. This will effectively override the wizard's handling of the Enter key so that it can be used to search when the user has either package search bar in focus.
Fixes #448 
See: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener
=> CreateImageWizard: fix Enter key for packages search

src/Components/CreateImageWizard/formComponents/Packages.js
When adding all packages we no longer depend on the state update. Instead, we initialize an object with the chosen packages and pass that to both the step's state and the form's state. Using the step state to set the form's state was causing the form's state to be set from the prior step state and not the state with the new package list.
Fixes #447
=> CreateImageWizard: fix add all packages

src/Components/CreateImageWizard/formComponents/Packages.js
If a user choses packages and then changes to a different step, the packagesChosen state is wiped. These packages are now stored in the form state under 'selected-packages'. When the packages step is mounted, if there are 'selected-packages', these are the initial state for packagesChosen.
Fixes #441
=> CreateImageWizard: show previously chosen packages

src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/steps/registration.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Activation key was previously obscured by stars, instead just show it
(both in the input and in the review step) as it isn't secret.
=> CreateImageWizard: don't obscure activation key

src/Components/CreateImageWizard/CreateImageWizard.js
Prevents `...<div> cannot appear as a descendant of <p>.` when running
`npm run travis:verify`.
=> CreateImageWizard: Prevent dom validation error

src/Components/CreateImageWizard/formComponents/Packages.js
Having the available packages list be either undefined, empty, or with elements requires complicated logic. Instead, initialize
packagesAvailable to an empty array. In order to display an error state when the packages search returned no packages, now use a boolean flag if available packages were found. This check also sets us up in case we want to provide further feedback on failed package searches.
=> CreateImageWizard: redo package search default message

src/Components/CreateImageWizard/formComponents/Packages.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
When a user searches for available packages, already chosen packages are filtered from the available packages list. This prevents the user from adding duplicate packages.
Rebased on top of #479
Fixes #464
=> CreateImageWizard: filter already added packages

src/Components/CreateImageWizard/CreateImageWizard.js, src/Router.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This also mitigates the issue where clicking the image-builder nav link
would redirect you to `image-builder/image-builder` if image-builder was
already opened. And `/` didn't catch that path.
=> Router: Replace landing with catch-all route

src/Components/ImagesTable/ImageLink.js
The link for the gcp Instance description was not set to isInline. Fixing this aligns the text with the rest of the instance links.
=> ImagesTable: align gcp image details with other instance text

src/Components/CreateImageWizard/steps/msAzure.js
Resource group names only allow alphanumeric characters, periods, underscores, hyphens, and parenthesis and cannot end in a period. A regex validation is now added to ensure this.
Documented by azure here: https://docs.microsoft.com/en-us/rest/api/resources/resource-groups/create-or-update
Fixes #488
=> CreateImageWizard: validate azure resource group

src/Components/CreateImageWizard/formComponents/Packages.js, src/api.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
When searching for a package, all matching packages are now returned. First an
attempt is made using the api's default limit and if there are more
matching packages than the default limit a second request is made with
an increased limit. To facilitate this, api.getPackages() now accepts an
optional limit parameter. Retrieving all matching packages is necessary
because of the sorting logic.
=> CreateImageWizard: Get all matching packages from package search

README.md, config/dev.webpack.config.js, package.json
A developer can now run `npm run stage` which will run the UI against
the staging environment on crc.
=> package.json: add run script for stage env

src/Components/CreateImageWizard/steps/googleCloud.js
Update the popover for the gcp step in the CreateImageWizard. This commit
changes the default popover position to the right of the modal.
Fixes #601 
Screenshot:
=> CreateImageWizard: fix gcp popover

src/Components/CreateImageWizard/steps/aws.js
Autofocus the input field in the aws step of the CreateImageWizard modal.
Fixes #599
=> CreateImageWizard: prefocus aws input field

src/App.js
The tab title for image builder in crc was being diplayed as `image_builder`.
This commit fixes issue #617
=> App: fix tab title

src/Components/CreateImageWizard/steps/googleCloud.js
The margin on the `ul` list inside the gcp information popover was causing the popover
to look unevenly spaced. Removing the left margin resolves this. This commit fixes #630
Before:
After:
=> CreateImageWizard: gcp popover padding/margin fixes #630

src/Components/ImagesTable/ImageBuildStatus.js
Tighten the space between the status icon and the status text.
Fixes #595
=> LandingPage: tighten space between status icon and text

src/Components/CreateImageWizard/formComponents/MountPoint.js
Adds all valid prefixes defined in composer, removes invalid ones, and
disables the TextInput for the root partition. This makes customized
filesystems less error prone.
https://bugzilla.redhat.com/show_bug.cgi?id=2070761
=> CreateImageWizard: Change valid prefixes to match composer

src/Components/CreateImageWizard/formComponents/TargetEnvironment.scss
Decrease the spacing below labels from 8px to 4px in accordance with the mocks.
Fixes #597
=> CreateImageWizard: fix label spacing

.travis/custom_release.sh
The default release script doesn't push `main` to stage-beta.
=> .travis: Introduce simplified custom release script

src/Components/CreateImageWizard/formComponents/ActivationKeys.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The validators are passed values by the useFieldApi hook. Adding this to the activation key component allows the `required` validation to work.
Fixes #624
=> CreateImageWizard: fix validation for activation keys

README.md
Update the start scripts to match the updated scripts in the `package.json`. Additionally, add instructions
for forwarding the domains to localhost for the stage and prod since this is only mentioned in the `devel/`
readme.
=> README: update start scripts

src/Components/CreateImageWizard/CreateImageWizard.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The vhd alias for gcp was dropped, as image-builder includes extra repos
for gcp.
=> CreateImageWizard: Use 'gcp' image type for gcp

src/Components/ImagesTable/ImagesTable.js, src/Components/ImagesTable/ImagesTable.scss, src/test/Components/ImagesTable/ImagesTable.test.js
This commit displays the UUID in an expandable details row. This is
necessary because if an image was named, the UUID was not displayed.
It is important that a user know the UUID for troubleshooting, for
example in the case of requesting help with an image.
To facilitate this, the original Table component was converted to a
TableComposable component. TableComposable is newer and recommended over
the older Table by PatternFly.
=> ImagesTable: Show UUID in expandable details row

.github/workflows/sync-branches.yml
This workflow syncs the main branch with the stage-stable branch.
It also includes a production target which needs to be dispatched
manually. The production target pushes the input ref to both prod-beta
and prod-stable branches.
This results in the main branch always being deployed on stage-beta and
stage-stable, and the prod-beta and prod-stable branches being synced on
release.
---
~~With 4 different branches now (main, stage-stable, prod-beta, prod-stable), we should have a more formal way of releasing to a specific target.~~
~~Should we have prod-beta == stage-stable always?~~
---
On push to main main -> stage-beta sync.
Release sync $sourc ref -> prod-beta == prod-stable
=> .github: Sync branches workflow

src/Components/ImagesTable/ImageBuildErrorDetails.js, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
Add error information for failed image builds. The error details are only displayed
for failed builds and the error highest up the error chain is displayed in the expandable
section of the image.
=> ImagesTable: add error status

.github/workflows/sync-branches.yml
Make the name of the check job more like the name of the sync job.
---
very important patch, it just annoyed me suddenly .-.
=> .github: Rename sync-branches workflow ref check job

src/Components/CreateImageWizard/formComponents/MountPoint.js
/tmp was added to the list of valid mountpoints in the filesystem
customization step.
No validation is necessary at this time because rhel-86, centos-8, and
centos-9 all support a /tmp mountpoint.
=> CreateImageWizard: Add /tmp mountpoint

.travis/58231b16fdee45a03a4ee3cf94a9f2c3, .travis/custom_release.sh
This modifies the Jenkinsfile used for release to also send a POST
requested to a webhook url which will then trigger test pipelines in IQE
Jenkins.
That Jenkinsfile is quite stable and will probably not see any more changes as the frontend deployement is moving away from it. For now if we want to trigger IQE test pipelines after a deploy of new frontend this is the way to do it.
=> CI: add trigger for IQE pipelines

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/ImageCreator.js, src/Components/CreateImageWizard/formComponents/CentOSAcknowledgement.js, src/Components/CreateImageWizard/formComponents/ImageOutputReleaseSelect.js, src/Components/CreateImageWizard/steps/imageOutput.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Adds an info alert that reads `The CentOS Stream distribution is enabled for
community use and not eligible for Red Hat Support. To learn more, visit
CentOS Stream.` to the image output step when CentOS Stream 8 or CentOS
Stream 9 is selected as the release. This is necessary to ensure
customers understand the role CentOS plays with respect to RHEL.
=> CreateImageWizard: CentOS Speedbump

devel/gen-dashboards
So people don't have to install python-unversioned-command on Fedora. It saves you 11 kB of disk space, worth it. :P
=> devel/gen-dashboard: use python3 explicitly in the shebang

src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
In order to help people transition from using GUI to use the API directly,
it's helpful to give them an easy way to inspect the whole raw compose
request.
This commit adds a new button next to each compose that simply downloads
the original compose request in a json format. This request can then be
directly piped into the IB API to build a new image.
Manipulation DOM directly when using React? Crazy, right? It works though but I'm open to suggestions.
https://www.youtube.com/watch?v=pr-6evaue_4
(I failed to embed gif, sry.)
Original idea by Troy Dawson
=> ImagesTable: add option to download a raw compose request

src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
Fixes #769. This adds file extensions for private cloud and other target environments in Image output step as per recent SPUR.
=> Wizard: Display file extensions on Image output step

src/Components/CreateImageWizard/steps/aws.js, src/Components/CreateImageWizard/steps/googleCloud.js
Fixes #770. This clarifies that the user is responsible for copying the AWS/GCP image to their account before the image expires.
=> Wizard: Add clarification to AWS and GCP environment steps

package-lock.json, package.json, src/AppEntry.js, src/store/index.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/testUtils.js
This commit adds Redux Toolkit as a dependency. Adding Redux Toolkit is
beneficial because it will allow us to use the current best-practice Redux
development patterns and tools as well as reduce the number of
dependencies. Redux Toolkit is backwards compatible with existing Redux code,
and therefore works with all of the current actions and reducers.
The store is now created using Redux Toolkit's configureStore(). Previously, a
custom store creator developed by Red Hat Insights was used. However,
this is actually not required for Insights apps, and creating the store using
configureStore() is necessary to take advantage of Redux Toolkit. For
instance, the store can now be inspected using the Redux devtools in the
browser.
This commit removes the redux-logger middleware. It is no longer …
=> Redux: Add Redux Toolkit

src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
Fixes #594. This adds pagination to the bottom of the images list so the user doesn't have to scroll up to use it.
Tests were also updated to reflect the change.
=> ImagesTable: Add pagination to the bottom of the table

src/Components/ImagesTable/ImageBuildStatus.js
Fixes #808. This removes the `<small>` tag around status message to unify the font size within the table.
=> ImagesTable: Increase font size of text in Status column

src/Components/ImagesTable/ImagesTable.js
Previously the polling was started once on mount, but the reference to composes the polling function received didn't get updated. Reset the polling on each render, ensuring the polling function has the latest composes from the store.
Fixes #767
=> ImagesTable: Reset polling each time the composes are updated

src/Components/CreateImageWizard/formComponents/FileSystemConfigButtons.js, src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/steps/fileSystemConfiguration.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This commit improves the file system configuration step's error handling
by performing validation only when the next button is clicked. This
allows an invalid state to temporarily exist while the user is modifying
the mountpoints without bothersome error messages needlessly appearing.
Broadly speaking there were two options for the implementation: (1)
delay the validation, performing validation only upon clicking the next
button -or- (2) perform validation immediately as normal but hide error
messages until the next button is clicked. Option (1) proved to be
untenable - Data Driven Forms does provide `pauseValidation()` and
`resumeValidation()` functions from React Final Form which theoretically
would make this option possible... However, we need to call
`resumeValidation()` in the next …
=> Wizard: Improve file system configuration error messaging

src/Components/ImagesTable/ImagesTable.js
Fixes #797. This increases the size of the margin at the bottom of the table of images. That way the pagination controls are not obscured by the notifications icon.
=> ImagesTable: Increase bottom margin of the pagination toolbar

src/App.js
Because of mismatched redux versions between NotificationPortal and our app, the former couldn't automatically discover the store.
Also drop reregister of notificationsReducer, we already register it in store.
=> App: explicitly pass the store to the NotificationsPortal

src/AppEntry.js, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/ImagesTable/ImagesTable.js, src/Router.js, src/Utilities/path.js, src/entry.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/ImagesTable/ImagesTable.test.js
The insights platform is moving to react router v6, meaning router contexts can no longer be nested. As a result all applications will end up sharing the same `BrowserRouter`.
Switch to using the release (`/` or `/beta/`) as a basename for the BrowserRouter, and offload the full path (`/insights/$appname`) to the individual routes. This makes it easier to drop the BrowserRouter in image builder for the platform one in future.
---
`ci.ext.devshift.net PR build` can be ignored until #828 is merged and this is rebased
=> src/Router: use release as a basename in BrowserRouter

src/Components/ImagesTable/ImageBuildStatus.js, src/Components/ImagesTable/ImageBuildStatus.scss, src/Components/ImagesTable/ImageLinkDirect.js, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
This adds indication of expiring presigned urls for aws.s3 targets. Previously the targets remained marked as `Ready` until the builds disappeared after 14 days.
When an image is ready, the countdown in hours is shown in `Status` column. After that the image is marked as `Expired` and the download link changes to `Recreate image`.
=> ImagesTable: Indicate expiration of aws.s3 targets

src/Components/sharedComponents/DocumentationButton.js
Fixes #776. This updates Documentation links on Image output step from RHEL 8 docs URLs to RHEL 9 docs URLs.
=> Wizard: Update image output step links from RHEL 8 to RHEL 9

src/Components/ImagesTable/ImagesTable.js, src/Components/ImagesTable/ImagesTable.scss, src/test/Components/ImagesTable/ImagesTable.test.js
By skipping the rendering of the <a /> we can still download a data-URI formatted link.
This resolves: #805.
=> imagestable: request.json link now non-styled

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/api.js, src/constants.js, src/repos.js
The Content Sources service is now used for handling package info and search. The api call to this service requires a list of repo urls. The `repos.json` file tracks the supported repositories for each distro. This is then mapped into a url array for whichever distro we are searching for packages. The response body is similar to what existed in image-builder but the key `package_name` needs to be mapped to just `name`. Also, there is no pagination in Content Sources for `/rpms/names` so we can currently only fetch a limit of 20 packages.
=> api: use content-sources api for package search

src/Components/ImagesTable/ImageLinkDirect.js
Fixes #803. This removes the download icon and adds brackets around the file extension.
=> ImagesTable: Remove the icon from the download link

src/Components/ImagesTable/ImageLinkDirect.js
This removes an extra `/` from the path for the `navigate` function to be able to resolve relative path correctly.
=> ImagesTable: Fix Recreate image button

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes #774. This matches the Review step with the updated mocks as per SPUR.
The changes are following:
1. Target environment tab:
- value of AWS `Account ID` aligned with GCP and Azure values
2. Registration tab:
- `Subscription` changed to `Registration type`
- `Organization ID` removed, will be added in a different place so it's clearer it's associated with an activation key
3. System configuration:
- updated column name `Type` to `File system type` in partitions popover
- updated the width of the column to accommodate the change
- unified line spacing of `Image size` with the other rows
- changes `Packages` to `Additional packages`
=> Wizard: Update Review step

src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/steps/aws.js, src/Components/ImagesTable/ClonesTable.js, src/Components/ImagesTable/ImageBuildStatus.js, src/Components/ImagesTable/ImageLink.js, src/Components/ImagesTable/ImageLinkDirect.js, src/Components/ImagesTable/ImagesTable.js, src/Components/ImagesTable/ImagesTable.scss, src/Components/ImagesTable/RegionsPopover.js, src/Components/ImagesTable/Target.js, src/Components/ShareImageModal/RegionsSelect.js, src/Components/ShareImageModal/ShareImageModal.js, src/Router.js, src/Utilities/time.js, src/api.js, src/constants.js, src/store/actions/actions.js, src/store/clonesSlice.js, src/store/composesSlice.js, src/store/index.js, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/ShareImageModal/ShareImageModal.test.js, src/test/testUtils.js
This PR exposes the API's clone endpoints in the frontend. 
At this time, only AWS images support cloning (or 'sharing', as it is referred to in the frontend). An AWS composes' clones are displayed in a sub-table located in an expandable row.
Composes can be cloned (shared) to other regions via a new modal.
This PR also continues the process of modernizing our Redux store through the use of selectors for data normalization.
=> Aws multiple regions

src/Components/sharedComponents/DocumentationButton.js
The old URL pointed to the on-prem documentation, not the service docs.
=> DocumentationButton: fix documentation url

src/Components/ImagesTable/ImageLink.js, src/store/composesSlice.js
This is needed for filtering all unmatched instance types architecture in the provisioning wizard.
=> HMSPROV #355 - add architecture to provisioning wizard

src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
Prior to this commit, the downloaded request was just an ugly unformatted json. Surely, `jq . <request.json` could fix that, but it's much more convenient if the frontend does it itself.
Signed-off-by: Ondřej Budai <ondrej@budai.cz>
Example:
```
{
"image_name": "I am formatted!",
"distribution": "rhel-86",
"customizations": {
"packages": [
"bind-utils",
"jq",
"logrotate",
"nfs-utils",
"podman",
"podman-remote",
"sos",
"unzip",
"zip"
]
},
"image_requests": [
{
"image_type": "gcp",
"architecture": "x86_64",
"upload_request": {
"type": "gcp",
"options": {
"share_with_accounts": [
"serviceAccount:abcdef@abcdef.iam.gserviceaccount.com"
]
}
}
}
]
}
```
=> ImagesTable: indent the downloaded compose request

src/Components/CreateImageWizard/formComponents/ActivationKeyInformation.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/api.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes #822. This adds component `ActivationKeyInformation` with additional information for an activation key on a Registration tab of Review step. The added fields are:
- Name
- Role
- SLA
- Usage
- Additional repositories
Organization ID is added to the Activation key popover.
Function `getActivationKey` was added to `api` to get an additional information about activation key from RHSM api based on the name of the key.
=> Wizard: Add additional information for an activation key in Review step

src/Components/CreateImageWizard/steps/googleCloud.js
Fixes #879. This adds anchor at the beginning of the regular expression for validation of GCP targets.
=> Wizard: Improve validation of GCP targets

package-lock.json, package.json, src/Components/CreateImageWizard/ImageCreator.js, src/Components/CreateImageWizard/formComponents/ActivationKeyInformation.js, src/Components/CreateImageWizard/formComponents/RegistrationKeyInformation.js, src/Components/CreateImageWizard/steps/registration.js
This adds a `TextList` with additional information for a chosen activation key in Registration step of the Wizard.
Component `AdditionalKeyInformation` is wrapped within a new component called `RegistrationKeyInformation` for the purpose of displaying the information on the Registration step. As the component needed to use `FormSpy` element to work properly in this context within the Data Driven Forms. Without it the validation of the form didn't work as expected, because of a persisting reference to the element it was evaluated against.
Popover for an Activation key was also updated according to SPUR mocks.
=> Wizard: Add activation key information in Registration step

src/Components/CreateImageWizard/formComponents/ImageOutputReleaseSelect.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This commit fixes #893 by removing the ability to clear the release select on the image output step (this is the select where the user chooses from RHEL 8, RHEL 9, CentOS 8 or 9, etc...).
Originally the ability to clear the select was added so that the default state (where CentOS options are hidden behind a 'speedbump') could be returned to but this seems unnecessary in retrospect and introduces opportunities for bugs (as seen with the validation in #893) so it seems wise to simply remove the ability to clear altogether.
=> Wizard: Remove clear handler from Release select on Image Output step

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Repositories.js
This commit clarifies variable names and comments that were found to be confusing during the review of 5adc0e.
=> Wizard: Clarify variable names and comments in requestToState()

src/Components/ImagesTable/ImageBuildStatus.js, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
Fixes #899. The status of images (parent images and clones) in the clones table was displayed incorrectly - the 'highest priority' (e.g. failure > success) was displayed for all images.
This was due to a bug in a conditional in the ImageBuildStatus component. In the main images table, rows for AWS images should display the highest priority status of *all* images. A single failed clone should cause the status of the row in the main images table to be failure, even if the parent compose status is successful.
This logic was incorrectly being applied to *all* statuses. This commit fixes this - from now on, this logic is only used for rows in the main images table.
=> ImagesTable: Fix status bug

src/Components/ImagesTable/ImageLink.js
Supersedes #897 
Fixed a minor typo, `initiated` to `initialized` that was blocking merging. Not having provisioning in the ephemeral environment is a blocker for @akhil-jha.
=> Enable provisioning wizard in Ephemeral environment

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/formComponents/ImageOutputReleaseSelect.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/constants.js
Fixes https://github.com/RedHatInsights/image-builder-frontend/issues/909. Fixes https://github.com/RedHatInsights/image-builder-frontend/issues/918.
This updates the order of the releases on the Image output step to sort from newest to oldest. The RELEASES Object was converted to Map which remembers insertion order.
The color of the `Show options for further development of RHEL` option in the Release dropdown select was also changed to blue.
=> Wizard: Update order of releases on the Image output step

src/store/apiSlice.js, src/store/index.js
This commit adds the /provisioning/v1/sources endpoint via a new apiSlice.js which uses RTK Query's createApi method.
RTK Query allows us to query the /provisioning/v1/sources endpoint using an automatically generated React hook, `useGetSourcesQuery`. The usage is something like this (from within a React component): `const { data: sources, isLoading, isSuccess, isError, error } = useGetSourcesQuery()`.
This will make it much easier for us to manage data caching and just as importantly manage loading and error states properly.
Future PRs will migrate data fetching in the other slices (clones, composes, repositories) to the apiSlice.
For more info on RTK Query, see:
https://redux.js.org/tutorials/essentials/part-7-rtk-query-basics
=> Redux: Add RTK Query + /provisioning/v1/sources endpoint

package-lock.json, package.json
This commit bumps Jest to 29.4.1. This requires adding two additional development dependencies.
As of Jest 28 `jest-environment-jsdom` is no longer shipped with Jest by default, and has therefore been added as a dependency.
`uuid` was also added as a dev dependency. Jest 29 introduced some compatibility issues with `uuid` that were fixed in `uuid@9`: https://github.com/uuidjs/uuid/issues/451#issuecomment-1206284480
We import and use `uuid` in our tests, but as it was a dependencies dependency we did not control which version was installed. Version 8 (what was installed) causes Jest tests to fail like so:
```
SyntaxError: Unexpected token 'export'
> 29 | import { v4 as uuidv4 } from 'uuid';
```
=> Dev Deps: Bump Jest to 29.4.1

config/dev.webpack.config.js, config/prod.webpack.config.js, deploy/frontend-clowder.yml, src/Components/CreateImageWizard/CreateImageWizard.js
Due to merging the openshift and chrome plugin systems there's additional requirements on the format of the module name.
=> config: update module name in webpack config

.eslintrc.yml, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/formComponents/MountPoint.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/Components/CreateImageWizard/validators/fileSystemConfigurationValidator.js, src/Components/CreateImageWizard/validators/targetEnvironmentValidator.js, src/Components/ImagesTable/RegionsPopover.js, src/Components/ShareImageModal/RegionsSelect.js, src/api.js, src/store/repositoriesSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/ImagesTable/ImagesTable.test.js
Require const declarations for variables that are never reassigned after being declared. If a variable is never reassigned, using the const declaration is better. const declaration tells readers, “this variable is never reassigned,” reducing cognitive load and improving maintainability.
=> ESLint: Add `prefer-const` rule

jest.setup.js, package-lock.json, package.json, src/constants.js, src/store/apiSlice.js, src/test/mocks/handlers.js, src/test/mocks/server.js
This PR adds a new library `msw` that we will use to mock API requests at the network level. 
The first commit adds the dependency, and the basic set-up is performed in the second commit. We currently use RTK Query to query only one endpoint, `/provisioning/v1/sources`, so support for that endpoint is added. The third commit provides a polyfill for `fetch` in our testing environment (which is required by RTKQ).
=> Add mock service worker

src/repos.js
These URLs are used for package searching with the content-service.
- Remove the google cloud repos, these are added only for gcp
- Fix centos 9 URLs
=> src/repos: Fix urls

src/Components/ImagesTable/Target.js
The rhel-edge-commit and rhel-edge-installer image types had no target label. This is now added. Also, if other image types are created that do not have a descriptive label then default to using the image type.
=> ImagesTable: support additional image type labels

src/App.js
This disables the global filter on the top of the page. So later when an option to filter images by name is added, there won't be multiple filters which could lead to confusion.
=> App: Disable the global filter

jest.setup.js
This commit makes the `msw` server globally available to all test files. Given that the majority of our test files will ultimately make calls to APIs using RTK Query (calls are made in both the table and the wizard), making these globally available in jest.setup.js is reasonable.
=> Jest: Add mock service worker server commands to jest.setup.js

config/dev.webpack.config.js, config/prod.webpack.config.js, package.json, src/Components/LandingPage/LandingPage.js, src/Components/LandingPage/LandingPage.scss
As part of our 'Open Source Services' initiative, we'll add a badge that indicates that our service is open. The popover will give additional context as well as a link to our architectural docs.
=> Show 'Open Service' badge and popover

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/ImageCreator.js, src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js, src/Components/CreateImageWizard/formComponents/FieldListener.js, src/Components/CreateImageWizard/formComponents/GalleryLayout.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/TargetEnvironment.js, src/Components/CreateImageWizard/steps/aws.beta.js, src/Components/CreateImageWizard/steps/aws.js, src/Components/CreateImageWizard/steps/index.js, src/store/apiSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/mocks/handlers.js
This PR adds the ability to configure an AWS target using the Sources service available on Insights instead of manually entering an AWS account ID. 
Note that the Sources API is not queried directly, rather the Provisioning API provides endpoints to obtain sources and their associated information (such as the account id). The Provisioning endpoints are available via RTK Query hooks, and mocked in the tests using Mock Service Worker.
=> Aws sources

src/Components/LandingPage/LandingPage.js
Use the CodeBranchIcon instead of just CodeIcon for the Open Source Services popover button.
This is a follow-up of https://github.com/RedHatInsights/image-builder-frontend/pull/949
Here's how the new icon looks:
=> Landingpage: Switch to CodeBranchIcon

src/Components/CreateImageWizard/steps/registration.js
This commit updates the link on the registration step so users are directed to the exact place where they can manage keys.
Because managing keys through the customer portal will soon become deprecated (keys will be managed through the keys service on insights) the text was also changed to be more general.
=> Wizard: Update activation keys link text and URI

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/store/apiSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/mocks/handlers.js
Previously the base repository links for each distribution were read from `repos.js` file. This gets the needed information from a call to api endpoint `architectures/{distribution}`. The data is fetched via RTK Query and is then filtered by an architecture. For now the x86_64 architecture is hardcoded, this will change when multiple architectures get available.
=> Wizard: Get distribution repositories from an api endpoint

src/Components/ImagesTable/ImageLink.js
The Launch service wizard should only be used to launch AWS images that
were created using share_with_sources (and not share_with_accounts) in
their request.
The Launch service only supports a single source at the moment, as does
the Image Builder Frontend. Therefore, we do not pass the entire
share_with_sources array - only the 0th element, which should be the
`only` source for images created using the front-end. We do not expect
full compatibility between images created using the API (which could
theoretically have multiple sources in share_with_sources) and Image
Builder Frontend.
=> Launch link aws sources only

src/Components/ImagesTable/ClonesTable.js
If a clone is created using a source, and the source is then deleted, the source will be undefined. Attempting to read the account_id from undefined causes the app to crash. Optional chaining fixes this.
=> ClonesTable: Ensure source exists before reading its account_id property

src/Components/CreateImageWizard/CreateImageWizard.scss
Fixes #914.
This adds a maximum height limit to the dual list selector on the Packages step. That way the Wizard doesn't become scrollable when the Packages search returns more results.
=> Wizard: Ensure only one scrollbar on the Packages step

package-lock.json, package.json
This bumps:
- `@scalprum/react-core` from 0.2.8 to 0.4.1
- `@redhat-cloud-services/frontend-components` from 3.9.25 to 3.9.32
The bump was ending with failing tests and an error `SyntaxError: Cannot use import statement outside a module`.
The problem lies in Jest not transforming files inside the `node_modules` by default. To transpile the modules that were triggering the error the `transformIgnorePatterns` was added.
=> Dev Deps: Bump `@scalprum/react-core` and `@redhat-cloud-services/frontend-components`

config/dev.webpack.config.js
This allows users to develop against production without having access to the internal network.
https://github.com/RedHatInsights/frontend-components/tree/62f37029ca0f5f7e9b0fd61815fe62c96503bcbf/packages/config#running-prod-proxy-without-vpn
=> config/dev: run proxy without VPN for production envs

.eslintrc.yml
This adds `no-console` rule to throw an error when using any of the `console` methods as those are used only for debugging purposes.
=> ESLint: Add `no-console` rule

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/Components/CreateImageWizard/formComponents/Repositories.js, src/Components/CreateImageWizard/steps/packages.js, src/Utilities/isBeta.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The QE team has requested that all beta features be exposed in the ephemeral environment (insights.chrome.getEnvironment() === 'qa').
=> Wizard: Expose beta features in qa environment

package-lock.json, package.json
This bumps @scalprum/react-core and adds `@scalprum` module to `transformIgnorePatterns`.
This solves the problem with failing tests, same as in #996
=> Deps: Bump @scalprum/react-core from 0.4.1 to 0.5.1

src/Components/CreateImageWizard/CreateImageWizard.js
Show details when the wizard sends a request that results in an error. Now that AWS and Azure have a maximum size, this needs to be shown.
---
=> CreateImageWizard: show error details on save

src/Components/CreateImageWizard/CreateImageWizard.js
This commit fixes a bug in the wizard. The Azure step name was incorrectly set when using the 'Recreate image' option which caused the wizard to crash when trying to access the Azure step.
=> Wizard: Fix bug causing crash upon visiting Azure step

src/Components/CreateImageWizard/steps/packagesContentSources.js, src/Components/CreateImageWizard/steps/repositories.js
Fixes #1065.
This sets buttons on the Repositories and Additional custom packages steps to `CustomButtons` to ensure buttons in each of the steps have a unique ID.
=> Wizard: Ensure unique IDs for buttons

src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.test.js
The Jenkins job takes too long to execute the Azure tests.
This is a hotfix, we should rather speed up the tests.
=> test: Increase azure test timeout

src/Components/CreateImageWizard/formComponents/ReviewStepTables.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
This removes prop validation that was left behind after the props were removed during a Review step updates PR review.
=> Wizard: Remove prop validation for `ReviewStepTables` and `ReviewStepTextLists`

src/Components/CreateImageWizard/formComponents/ActivationKeyInformation.js, src/Components/CreateImageWizard/formComponents/ActivationKeys.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/api.js, src/store/apiSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/mocks/handlers.js
This migrates calls to RHSM endpoints `activation_keys` and `/activation_keys/{name}` to RTK Query.
Tests were also updated to use Mock Service Worker instead of previous Jest mock function.
=> Wizard: Migrate activation keys calls to RTK Query

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/formComponents/Packages.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes #913.
This adds status bars to the `DualListSelectorPane` on the Packages step. The status bar indicates how many packages were found and how many of those have been selected.
Warning for too many returned results was also added. When an exact match is found during a search with over 100 results, it is shown together with the warning.
=> Wizard: Add "refine search" warning to Packages step

package-lock.json, package.json
3.20.6 includes a hotfix that allows modals to take an appendTo prop, which is necessary for modals to display correctly with the new quickstart tutorials.
=> build(deps): bump data driven forms to 3.20.6

src/Components/ImagesTable/ImageLink.js
Without this prop, the wizard's width expands to fill the entire window.
=> LaunchWizard: Add large variant prop to set width of wizard correctly

src/Components/ImagesTable/ClonesTable.js, src/Components/ImagesTable/ImageBuildErrorDetails.js, src/Components/ImagesTable/ImageBuildStatus.js, src/Components/ImagesTable/ImageBuildStatus.scss, src/Components/ImagesTable/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
This removes error details from the image detail and moves them to popovers activated by clicking on "Image build failed" status.
Popovers were also added for clones which didn't include any error details previously.
=> ImagesTable: Add popovers with error details for failed builds

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/steps/packages.js, src/Components/CreateImageWizard/steps/packagesContentSources.js
This removes unnecessary sentences from the description of Packages and Additional Red Hat packages steps. The min and max height of the `DualListSelector` was also updated.
=> Wizard: Update text on Packages and Additional Red Hat packages steps

src/App.js, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/ActivationKeys.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/Components/CreateImageWizard/formComponents/Repositories.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/steps/packages.js, src/Components/CreateImageWizard/steps/registration.js, src/Components/ImagesTable/ImageLink.js, src/Components/ImagesTable/RegionsPopover.js, src/Components/LandingPage/LandingPage.js, src/Utilities/isBeta.js, src/Utilities/useGetEnvironment.js, src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/LandingPage/LandingPage.test.js, src/test/Components/ShareImageModal/ShareImageModal.test.js
Calling insights.chrome is deprecated. The commits in this PR:
(1) replace isBeta() function with custom useGetEnvironment() hook
(2) adapt App.js to useChrome() hook (stop calling insights.chrome directly)
(3) replace all calls in code to insights.chrome with calls to either useChrome() or useGetEnvironment() hooks
This PR is important, because calling the deprecated insights.chrome functions results in a massive amount of warnings flooding the console, which makes it very difficult to find real/important error messages.
Chrome API docs can be found here:
http://front-end-docs-insights.apps.ocp4.prod.psi.redhat.com/chrome/chrome-api
=> Wizard: Use useChrome hook to set beta feature flag

src/Components/LandingPage/LandingPage.js
This updates spacing between the description and buttons as shown in [mocks](https://www.sketch.com/s/d7aa6d29-fca0-4283-a846-09cc5fd10612/a/j4g3WMz).
Nesting of the `<p>` tags was also removed to eliminate `Warning: validateDOMNesting(...): <p> cannot appear as a descendant of <p>` from the console logs.
=> LandingPage: Update spacing in expendable quickstart area

src/Components/CreateImageWizard/formComponents/Packages.js
This disables the "Add all" button in the `DualListSelectorControl` on the Packages step when there's too many results to display, even if there's an exact match.
=> Wizard: Disable "Add all" button when there's an exact match

src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
There is a bug in Patternfly that causes 'pop out' selects (those that use the menuAppendTo="parent" prop) to be rendered underneat the wizard footer.
Until this is patched in Patternfly, we will have to live with suboptimal select menus that scroll inside the modal.
=> Wizard: Make AWS sources select scrollable in modal

src/Components/ImagesTable/ClonesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
The instance column is no longer in the clones table per the latest designs.
=> ClonesTable: Remove Instance column

src/Components/ImagesTable/ImagesTable.js, src/Components/ShareImageModal/RegionsSelect.js, src/constants.js
This disables sharing to new regions in case of failed build of the parent image.
The regions that always end in failure were also disabled in the `ShareImageModal`.
=> ImagesTable/ShareImageModal: Update sharing options for AWS

src/Components/ImagesTable/ClonesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js
This removes the `created_at` column from the clones table as per the latest designs.
=> ClonesTable: Remove `created_at` column from the clones table

src/Components/ImagesTable/RegionsPopover.js
If an image does not contain a share_with_accounts property, launch links do not appear in the launch popover. This happens when a user creates an AWS image in beta/preview, and then clicks Launch in stable.
A message is now displayed that explains the image was created using Preview features, and the link to Preview has been clarified to be more explicit.
=> Wizard: Adjust AWS launch popover for images created in preview

src/Components/ImagesTable/ImageLink.js
The switch statement used to determine the image type for the Launch wizard was written incorrectly, this commit fixes it.
=> Wizard: Fix erroneous switch statement in ImageLink

src/Components/ImagesTable/ImageLinkDirect.js
If an image does not contain a subscription_id property, the link to view the image in Azure will be malformed. This happens when a user creates an Azure image in beta/preview using sources, and then clicks the 'View uploaded image' link in stable.
Now, if an Azure image was created using sources (as evidenced by presence of a source_id in request's upload options), the Launch button appears and its popover has a link to Preview.
=> Wizard: Add Azure launch link for images created in preview

src/Components/CreateImageWizard/formComponents/Repositories.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
gpgcheck is on by default, and if no gpgkey is specified dnf complains.
=> CreateImageWizard: turn off gpg check explicitly

src/test/mocks/handlers.js
This commit removes the base URL from the MSW handlers. This is
necessary in order for MSW to integrate into the browser (future commit)
and does not adversely affect the current test integration with MSW.
=> Mock Service Worker: Relative handler URLs

config/dev.webpack.config.js, package-lock.json, package.json, src/AppEntry.js, src/mockServiceWorker.js, src/test/mocks/browser.js
This commit integrates Mock Service Worker into the browser. This will allow us to use MSW to mock network requests at the API level from a browser using the same MSW fixtures that we are currently using for our testing. This means we will be able to have the same environment for debugging, development, and testing if desired.
To develop using MSW, the developer will now use `npm run stage-beta:msw`. The dev server will start as normal, but now any request made that has a corresponding fixture will be intercepted and the fixture used to generate the response.
This adds an MSW=TRUE environment variable to the run script. When this environment variable is present, the dev webpack config will copy mockServiceWorker.js into the build directory (/dist) using CopyPlugin and will add some …
=> MSW: Integrate MSW into browser

package-lock.json, package.json, src/Components/LandingPage/LandingPage.js
The open source badge now lives in @redhat-insights/frontend-components.
=> LandingPage: Update Open Source Badge

src/Components/ImagesTable/ImageLink.js
Unleash is being used to determine whether or not to use the Launch wizard for Azure and GCP images. Unleash is not yet supported in our ephemeral environments, but we want our ephemeral environments to have parity with beta. This commit ensures that the Launch wizard opens for Azure and GCP images in ephemeral.
=> Wizard: Enable Azure and GCP provisioning links in ephemeral

src/Components/edge/ImageDetails.js, src/Router.js, src/Utilities/edge.js
In the context of HMS parity stage 1, implement federated manage edge image page at route manage-edge-image.
The url of the following screen looks like: /insights/image-builder/manage-edge-images/9130/versions/56308/packages/additional 
dependency PR: https://github.com/RedHatInsights/edge-frontend/pull/686
=> EdgeImageDetails: Implement manage edge image details page.

src/Components/ImagesTable/ImageDetails.js
This removes Spinner next to the Image name when a build of an Azure image fails.
=> ImagesTable: Remove `Image name` Spinner for failed Azure images

.eslintrc.yml, src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js
This rule forbids use of == or !=, and enforces use of === and !==.
=> ESLint: Add eqeqeq rule

package-lock.json, package.json
This reverts an update of:
- `@data-driven-forms/pf4-component-mapper`
- `@data-driven-forms/react-form-renderer`
from version 3.20.8 to version 3.20.5.
The reason being a bug ending up in an "Node.removeChild: The node to be removed is not a child of this node"
Steps to reproduce the bug:
1. Open Image Wizard with a Create image button
2. Close the Wizard with Cancel button
3. Repeat two or three times
Also can be reproduced with:
1. Click on Kebab in the image row of the Images Table
2. Choose Recreate image
3. Close the Wizard with Cancel button
=> build(deps): Regress `data-driven-forms` libraries to version 3.20.5

config/dev.webpack.config.js, src/Components/LandingPage/LandingPage.js, src/Components/edge/ImagesTable.js, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/LandingPage/LandingPage.test.js
This commit adds tabs to image builder table - https://issues.redhat.com/browse/THEEDGE-3275.
This is necessary to integrate edge frontend images on the same page. one tab for image builder and one tab for edge images.
when adding these tabs to 'landingpage' we will cause the 'create image' button will appear under tabs instead of the upper section - related to this story - https://issues.redhat.com/browse/THEEDGE-3354.
and prevent the duplicate toolbar that will show in edge image tab - related to that story https://issues.redhat.com/browse/THEEDGE-3361
---
The webpack changes are for using local federated modules.
=> add tabs to image builder table

src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/steps/googleCloud.js
The GCP account identifier is not email, it can be, but not always. For example service accounts do have identifiers which look like emails, but they are not. This is also confirmed by the GCP docs. This patch renames that label to "Principal" which is also used in the GCP docs.
Now, to avoid confusion, I am keeping (e.g. e-mail address) just to not put too much stress on the customer trying to figure this out.
Warning: I don’t know React or any JS library pretty much so this might break all tests - review with care.
=> GCP: rename Email label to Principal

src/Components/LandingPage/LandingPage.js
In the context of HMS-parity with edge management, fixes the current behavior when selecting tabs and navigating back from edge image details view:
- when selecting a tabs the corresponding url is shown (the url can be copied , and when pasted we return to the selected tab)
- when returning back from edge management details view, the user  return back to the last tab (e.g ostree tab) 
FIXES: https://issues.redhat.com/browse/THEEDGE-3445
=> LandingPage: Integrate selected tab with url.

src/Components/CreateImageWizard/steps/googleCloud.js
This commit fixes the format text when create image with Google Cloud Platform target
related to issue: https://github.com/RedHatInsights/image-builder-frontend/issues/1195
=> googleCloud: Format the text on GCP target

src/Components/ImagesTable/ImageLink.js, src/Components/ImagesTable/ImageLinkDirect.js
This adds "Launch an instance" and "Save a copy" commands to the Image commands popover for GCP images.
Mocks: https://www.sketch.com/s/d7aa6d29-fca0-4283-a846-09cc5fd10612/a/qbbyGg3
=> ImagesTable: Update Image commands popover for GCP images

src/Components/ImagesTable/ImageLink.js
This fixes the bug when Launch button got replaced with Image command button even in the Preview.
=> ImagesTable: Fix the GCP launch link

src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
According to the documentation (https://react.dev/learn/you-might-not-need-an-effect) useEffect should only be used to synchronize with external systems.
In the FSC component showing the partition table useEffect was used to compute a value based on the form state.
The documentation present two relatable usecases to what we were doing in the component:
- https://react.dev/learn/you-might-not-need-an-effect#resetting-all-state-when-a-prop-changes
- https://react.dev/learn/you-might-not-need-an-effect#updating-state-based-on-props-or-state
This commit uses the presented strategies to externalise in a new component the computation of the MinSize. Because it has for dependency the list of partitions and the manual setting, it will get redrwan every time these values are changed in the form …
=> Components/ReviewStepTextLists: remove useEffect

src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/steps/fileSystemConfiguration.js, src/Components/sharedComponents/DocumentationButton.js
The access.redhat.com documentation moved from
`https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/creating_customized_rhel_images_using_the_image_builder_service/index` to
`https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/creating_customized_images_by_using_insights_image_builder/index`.
=> src: Update doc links

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/TargetEnvironment.js, src/Components/ImagesTable/ImageLinkDirect.js, src/Components/ImagesTable/Target.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The OVA type is also the default when checking VMWare now.
I chose different tooltip text for the vmdk, I found the text supplied in the mocks not super informative, so I decided to stress the usage of it as well.
I also changed the tooltip text on the ova sligthly, mostly to indicate that it also includes the vmdk.
=> CreateImageWizard: Add support for vsphere-ova imagetype

src/Components/CreateImageWizard/steps/imageName.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This adds validation of an image name based on a pattern, which was chosen as an intersection of the naming constrains of hyperscalers.
The pattern is based on the one for naming GCP images as those naming guidelines are the most restrictive. With added minimal length restriction of AWS.
Sources:
- [Azure](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules)
- [GCP](https://cloud.google.com/compute/docs/naming-resources)
- [AWS](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-image.html) and
As the length of the name for AMI differs between the CLI reference and the screenshot of the error the stricter rule was chosen.
=> Wizard: Image name validation

src/test/Components/ImagesTable/ImagesTable.test.js
This wraps clicking on an error popover into `act()` and thus removes the `When testing, code that causes React state updates should be wrapped into act(...)` error.
=> test/ImagesTable: Remove `should be wrapped into act()` error

src/Components/CreateImageWizard/CreateImageWizard.js
These changes were introduced in #1079 to ensure that quickstarts stay visible even after opening a Wizard modal as they are both top-most components.
`ModalProps` which were used for this purpose were introduced in version 3.20.6 of `@data-driven-forms/pf4-component-mapper`. Since then we had to regress the version to 3.20.5 as it was crashing the application on closing of a modal. The issue linked to this can be found here: https://github.com/data-driven-forms/react-forms/issues/1389
As we are now using mapper version that does not allow to use `ModalProps` the functionality of the workaround was lost and it was causing following console.error: `Warning: React does not recognize the ModalProps prop on a DOM element.`
=> Wizard: Remove `ModalProps` from schema

src/Components/LandingPage/LandingPage.js
This adds "New" label to the Immutable (OSTree) tab as per recent mocks.
=> LandingPage: Add "New" label to Immutable tab

src/Components/LandingPage/LandingPage.js
In the context of HMS-parity with edge management, fixes the current behavior when using browser history back and forward.
- When selecting a tab and then push the browser history back/forward, the tab of the current url is selected.
FIXES: https://issues.redhat.com/browse/THEEDGE-3460
=> LandingPage: Fixes tabs selection on browser back/forward.

src/test/Components/ImagesTable/ImagesTable.test.js
This eliminates the `Error: Uncaught [TypeError: stepBody.scrollTo is not a function]` console error by mocking `scrollTo` as a prototype.
The error was caused by `scrollTo` not being implemented in JSDOM.
=> test/ImagesTable: Remove `scrollTo is not a function` console error

src/Components/LandingPage/LandingPage.js
Changing the traditional tab name To Conventional.
=> rename ib tab from traditional to conventional

src/mockServiceWorker.js
Recently msw was bumped from 1.2.1 to 1.2.2 (https://github.com/RedHatInsights/image-builder-frontend/pull/1245). The version gets updated in `mockServiceWorker.js` upon running `npm ci`.
This PR changes the version as it wasn't a part of the original bump PR, but appears after every clean install.
=> msw: Version bump in `mockServiceWorker.js`

src/Components/ImagesTable/ImageBuildStatus.js
Failed AWS images showed a `Failed to share image to one or more regions.` error even though they weren't shared to other regions.
This was caused by checking for a 'failure' status in an array of `imageStatuses` that included the parent status.
=> ImagesTable: Fix bug where failed AWS images showed sharing error

src/mockServiceWorker.js
msw was bumped from 1.2.2 to 1.2.3 in https://github.com/RedHatInsights/image-builder-frontend/pull/1264
This changes the version in `mockServiceWorker.js` as done by `npm ci`.
=> msw: Version bump in mockServiceWorker.js 1.2.2 -> 1.2.3

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/steps/imageName.js, src/Components/CreateImageWizard/steps/packages.js, src/Components/CreateImageWizard/steps/packagesContentSources.js, src/Components/CreateImageWizard/steps/repositoriesStepMapper.js
This commit change the name of wizard-details to details, to prevent misconfusion with the image-name component
=> Wizard: change the name of wizard details

src/Components/edge/ImagesTable.js
This commit add specific link when open Immutable tab without any images at image builder table
Fixes # related to https://issues.redhat.com/browse/THEEDGE-3478
=> imageTable:  Update links on empty state

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/steps/imageName.js, src/store/composesSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
fixes https://github.com/RedHatInsights/image-builder-frontend/issues/1244
this commit adds the description fields to the Details step when a user creates a new image,
and when the user recreates the image, this field will exist. 
this pr depends on pr in the backend side - https://github.com/osbuild/image-builder/pull/792
=> Wizard: Add description field to details step

package-lock.json, package.json
This reverts commit d8c6ca93d1cbc65d7895b3fdcb3c0fc1acc0a6fd.
Reverting the bump to PF5 as it will need to wait for ConsoleDot's adoption.
=> Revert "build(deps): bump @patternfly/patternfly from 4.224.2 to 5.0.2"

src/Components/CreateImageWizard/formComponents/Registration.js
A useEffect was used without conditions to update the value of a state variable depending on the form state. That's apparent to a way to initialize the state. Instead, what can be done, is to immediately initialize the state at the proper value.
=> wizard/registration: cleaning of a useEffect

src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/testUtils.js
This moves the `clickBack`, `clickCancel`, `clickNext`, `getNextButton` and `verifyCancelButton` functions from the tests to `testUtils`.
=> test: Move button clicking functions to `testUtils`

src/Components/ImagesTable/ImageLink.js
When no aria label is given to a modal component, an error is thrown in console:
```
Modal: Specify at least one of: title, aria-label, aria-labelledby. 
[Error] Modal: When using hasNoBodyWrapper or setting a custom header, ensure you assign an accessible name to the the modal container with aria-label or aria-labelledby.
```
=> Fix missing aria label in launch wizard  modal console error

src/Utilities/time.js
For browsers in a time zone with a negative offset relative to UTC, the `Created/Updated` date displayed in the image builder table is almost always one day off. For example, images created on May 16, 2023 show "May 15, 2023" as the created/updated date. The timestamp formatting in `timestampToDisplayString` strips the time from the UTC timestamp returned by the API, then converts this date + 00:00:00 UTC to the local timezone, which in my case is always the previous day in Eastern Time.
This PR fixes the issue by using the full timestamp string when converting to the local time zone.
=> Fix timestampToDisplayString to not strip time from UTC timestamp

src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/ShareImageModal/ShareImageModal.test.js, src/test/fixtures/composes.tsx, src/test/mocks/handlers.js
This adds `request` to a reponse from the `composes/{composeId}` endpoint and `meta` to a response from the `/composes/{composeId}/clones` endpoint as per API documentation.
The incomplete responses were causing problems when fetching data from the endpoints mentioned above.
The fixture was also migrated to TypeScript.
=> test/fixtures: Update compose fixture and migrate it to TypeScript

src/Components/LandingPage/LandingPage.js, src/Components/LandingPage/LandingPage.tsx
Previously the Popover was used within the title of the tab. In addition the fact that the Popover had a button to get triggered, it created a button in a button issue. The web browser was reporting this as abnormal and the UI behavior was not ideal: while clicking on the interrogation mark the user was also moved to the corresponding tab.
This commit fixes that issue by using a TabAction to get the Popover working. Inspired by the patternfly documentation:
- http://v4-archive.patternfly.org/v4/components/tabs#help-action
=> LandingPage: fix the button in a button error

src/Utilities/time.js, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/fixtures/composes.tsx
The format of the timestamps of mock composes was causing an error in msw browser after merging https://github.com/RedHatInsights/image-builder-frontend/pull/1137
This updates the mock timestamps to the format of the actual ones fetched from the API.
=> test/fixtures: Update timestamps of mock composes

src/Components/ImagesTable/ImageDetails.js, src/test/fixtures/composes.tsx
Fixes HMS-2266.
The conditional in the image details component needed to have a check added for vsphere-ova type images.
A mock compose and corresponding status for a vsphere-ova type image have also been added.
=> ImagesTable: Fix bug where vsphere-ova details are not displayed

src/Components/CreateImageWizard/formComponents/Packages.js
Incorrect proptype for `selectedAvailablePackages` was causing following error: ```Warning: Failed prop type: Invalid prop `selectedAvailablePackages` of type `object` supplied to `ExactMatch`, expected an array.```
This fixes the problem.
=> Wizard: Fix the `Failed prop type` error

package-lock.json, package.json, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/ImagesTable/ClonesTable.js, src/Components/ImagesTable/ImageLinkDirect.js, src/store/actions/actions.js, src/store/composesSlice.js, src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.2.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.azure.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/ShareImageModal/ShareImageModal.test.js, src/test/jest.setup.js, src/test/testUtils.js
This pull request aims at addressing the current issue regarding the errors thrown while executing the tests.
For now it fixes issues related with:
* scalprum
* act
* null access
* (and also one no-op)
For the errors that were not fixed in this PR, they are converted into warnings, and we will have to take care of them in the future. The conversion is made with a new lib https://github.com/ValentinH/jest-fail-on-console that @regexowl found out.
The lib also makes the tests actually fail if other errors are presents, so hopefully we can't add new ones.
=> fixing the tests from their errors and warnings

src/Components/CreateImageWizard/formComponents/ActivationKeyInformation.tsx, src/test/fixtures/activationKeys.ts
This migrates the `ActivationKeyInformation` component to TypeScript together with the `activationKeys` fixture.
=> Migrate activation keys to TypeScript

src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js, src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/ImagesTable/ImageDetails.js, src/store/helpers.ts
This is first of all heads up what we are planning, second of all atempt to get ready for sources list response to be in format
```
{
data: [ <source1>, <source2> ]
}
```
instead of
```
[<source1>, <source2>]
```
Follow-up with updated API spec after Prov change (https://github.com/RHEnVision/provisioning-backend/pull/638) is merged: https://github.com/RedHatInsights/image-builder-frontend/pull/1306
=> Prepare for Provisioning list endpoint nesting

config/dev.webpack.config.js
This PR adds the ability to customize the host (default to localhost to prevent any regression)  in the `LOCAL_API` env var.
This change  will allow us to run containerized  image-builder-frontend and provisioning (in federated mode) apps locally, as we do  in https://github.com/RHEnVision/provisioning-compose/pull/9
=> feat(HMS-1909): enable a custom host in LOCAL_API env var

src/Components/CreateImageWizard/steps/registration.js
Fixes HMS-2322: On the Register step of the image build wizard, the link to "Create and manage activation keys here" should point to https://console.redhat.com/insights/connector/activation-keys.
=> HMS-2322: Wizard: Update registration step activation key link URL

src/Router.js
According to the React documentation[0], a suspense tag is needed to
encapsulate a lazy loaded component. Some bad behavior have been fix in
the UI thanks to that tag (i.e notification popup unclosable after
wizard creation).
[0] https://react.dev/reference/react/lazy#suspense-for-code-splitting
The notification bug began in 1b01cfba.
=> router: lazy loading requires a suspense tag

src/Components/CreateImageWizard/formComponents/ReviewStepTables.js
fixes https://github.com/RedHatInsights/image-builder-frontend/issues/1305 
This commit update popup of custom repositories with name of repository instead of url of repository
=> Wizard: update popup with repositories name on Review step

src/Components/CreateImageWizard/formComponents/Registration.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes HMS-1492
This changes all occurences of "rhc" and "remote host configuration" from capitalized to lowercase. In cases where the sentence started with "rhc" this was changed to "remote host configuration" to avoid starting the sentence with "Rhc".
=> HMS-1492: Change rhc to non-capitalized

api/config/imageBuilder.ts, src/store/imageBuilderApi.ts
This commit adds mutations for the /compose and
/composes/:composeId/clone POST end points to the Image Builder API slice.
=> API: Add mutations for creating composes and clones

.travis.yml, README.md
This PR adds a check to ensure nobody is updating the API by hand.
Also adds documentation on how to update the endpoints and apis in the README.
Manual changes on the api are detected by running `npm run api` and then `git status`, when there are some, travis will fail:
And this check let the rest of the CI execute when there's no manual changes on the API files:
=> api: ci checks that the api is not changed by hand + doc

README.md, src/Components/edge/ImageDetails.js, src/Components/edge/ImagesTable.js, src/test/Components/edge/EdgeImagesTable.test.js, src/test/Components/edge/ImageDetails.test.js
The edge images table is going to be integrated in the frontend code base in the coming weeks. To help smooth that development process there is need for a feature flag that would keep the current behavior running on stage and prod while the new image table is being developed.
For now dummy code is returned for when the flag is on, and legacy behavior keeps on going when the flag is off.
The stage flag can be seen there:
- https://insights-stage.unleash.devshift.net/projects/default/features/image-builder.edge.local-image-table
The prod flag can be seen there:
- https://insights.unleash.devshift.net/projects/default/features/image-builder.edge.local-image-table
The commit brings in some documentation in the Readme. Any member of the team should be able to follow these steps to add in new …
=> edge: setup an unleash toggle for the image table

src/Components/ImagesTable/Instance.tsx
The `<LaunchWizard>` architecture prop was specified incorrectly, which caused the Instance dropdown in the Launch wizard to fail to load instance types.
=> LaunchWizard: Correct architecture prop

README.md, api/schema/contentSources.json, src/Components/CreateImageWizard/formComponents/CustomButtons.js, src/Components/CreateImageWizard/formComponents/Repositories.js, src/Components/CreateImageWizard/formComponents/ReviewStepTables.js, src/Utilities/checkRepositoriesAvailability.js, src/store/contentSourcesApi.ts
These params will be added to content-sources soon.  And in the short future there will be other origin's available (Red Hat for example).  In the far future there will be other content_types (most likely). 
I haven't tested this change so tread lightly :)
Content sources PR: https://github.com/content-services/content-sources-backend/pull/383
But this shouldn't cause any problem going in earlier.
=> Filter content-sources repos by origin and content_type

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/steps/googleCloud.js, src/store/typeGuards.ts, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/jest.setup.js
Depends on https://github.com/osbuild/image-builder/issues/829
Adding GCP image sharing option according to the discussion on [slack](https://redhat-internal.slack.com/archives/C03AZ0264LW/p1692789579814619) and [mocks](https://issues.redhat.com/browse/HMS-2352). 
In summary, within our GCP sources, we store the project ID. Images cannot be shared directly with a project ID, but they can be shared with a service account or a Google account. Consequently, to launch instances in GCP, users are not required to provide their Google account; instead, the images should be shared with the provisioning service account. This ensures that the provisioning team has access to the necessary images, as sharing them with individual users would not allow that.
After a thorough discussion, we have …
=> Add GCP image sharing options

api/config/imageBuilder.ts, api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/ImageCreator.js, src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/formComponents/MountPoint.js, src/Components/CreateImageWizard/formComponents/Oscap.js, src/Components/CreateImageWizard/formComponents/Packages.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/steps/fileSystemConfiguration.js, src/Components/CreateImageWizard/steps/imageOutputStepMapper.js, src/Components/CreateImageWizard/steps/index.js, src/Components/CreateImageWizard/steps/oscap.js, src/Components/CreateImageWizard/steps/packages.js, src/Components/CreateImageWizard/steps/registration.js, src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/Release.tsx, src/store/imageBuilderApi.ts, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/fixtures/composes.ts, src/test/fixtures/oscap.ts, src/test/mocks/handlers.js
This pull request adds to the wizard a new step to let the user pick an oscap policy.
Applying a policy has for effect to add (depending on the required customizations of the policy):
* Filesystem customizations
* Packages
The chosen policy is also added to the compose request send to IB.
This work is compatible with the recreate functionality as long as the policy is included in the compose request to recreate.
**Some design choices:**
When the user chose a policy, the next steps of FSC and Packages are impacted. And we took the choice to reinitialize these two steps every time the user makes changes in the policy steps. That means that if a user selects a policy, goes to the packages step to add some and then changes back their policy, the packages step will get reinitialized again. …
=> Openscap: allow customers to configure an oscap policy in the wizard

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/CreateImageWizard.scss, src/Router.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This pull requests makes the wizard appear in its own page when the user clic on the "create an image" button.
However, there's a bug with the height of the wizard still being limited, see the bug opened on data driven forms https://github.com/data-driven-forms/react-forms/issues/1402
To overcome the bug a custom CSS rule deactivate the height limitation.
=> Wizard not in modal

src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/Components/ImagesTable/ImagesTable.test.js
This should help with tests flaking on the `act()` error.
=> test: Improve stability of the ImagesTable tests

.eslintrc.yml
Commit #3e84abba3f43e4945d84faf2f2210df670bfb9d8 bumped @redhat-cloud-services/eslint-config-redhat-cloud-services from 1.3.0 to 2.0.3.
This introduced a new rule that broke a number of our imports. This commit forbids the rule for now.
(rulesdir/forbid-pf-relative-imports: off)
=> eslint: Disabled rulesdir/forbid-pf-relative-imports

src/Components/CreateImageWizard/CreateImageWizard.js, src/store/enhancedImageBuilderApi.ts
The images table uses the useGetComposesQuery hook to fetch composes and implement pagination. When this query is used, args are provided for the offset and limit and a 'Compose' tag is provided for the query.
When a mutation is triggered (causing a POST request to be sent to the `/compose` end point), the 'Compose' tag is invalidated which clears all cached data from useGetComposesQuery hooks, which in turn causes the table to refetch compose information.
If invalidating the `Compose` tag causes a refetch before the new compose is available in image-builder, the result does not contain the new compose and the table is not updated to include it.
This commit eliminates the race condition by waiting for the query to be fulfilled before invalidating tags (and therefore before refetching the …
=> API: Eliminate race condition in Image Builder API slice

src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
There was a bug preventing all the partitions required by an oscap policy to show up in the fsc step. That bug was because the FSC customizations were only accepted if they matched exactly the fix set of base partitions directories.
So now there's a bit of string manipulation to avoid that but it's all patched up.
fixes https://github.com/RedHatInsights/image-builder-frontend/issues/1385
=> fsc: fix the oscap fs customizations

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/ShareImageModal/RegionsSelect.tsx, src/store/enhancedImageBuilderApi.ts
This commit moves the notification dispatching for creating composes and
clones into a more sensible location – the Image Builder API slice.
It is more sensible because it separates the logic of the React
component (the wizard or share images modal) from the logic of handling
the request life cycle (which is now handled entirely in the slice).
There is a subtle but significant change – a new request will be
dispatched for every request. This is the correct way to do things as it
is possible that some requests succeed, and that others fail. Insights
causes the notifications to stack on top of each other neatly, so there
is no UI problem.
To facilitate this, we also need to use use Promise.allSettled instead
of Promise.all.
=> API: Move notification dispatch to Image Builder API slice

package-lock.json, package.json
This version includes a bugfix for the wizard navigation bar.
=> deps: bump @data-driven-forms/react-form-renderer from 3.21.6 to 3.21.7

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/formComponents/Repositories.js, src/Components/LandingPage/LandingPage.scss, src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.scss, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This commit:
1. Removes the header from the Data Driven Forms wizard
2. Adds padding around the in-page wizard so it is visually consistent
with the images table
3. Refactors the images table header into a re-usable component that is
now used in both the images table and the wizard
4. Allows the repositories table to fill the available vertical space in
the wizard
5. Adjusts the package dual list selectors so that they fill the
available horizontal space in the wizard
=> Wizard: Make wizard header match table header

src/Components/ImagesTable/ImagesTable.tsx, src/store/emptyImageBuilderApi.ts
This commit introduces a filter for the "image_type" to the "getComposes" endpoint, thereby improving the functionality of the Image Builder frontend table. This table consists of two tabs: RPM and OSTree. With this enhancement, users gain the ability to filter out OSTree images from the RPM tab, thus avoiding duplication.
this change is the impact of changes in the backend side in this pr https://github.com/osbuild/image-builder/pull/825
=> ImageTable: THEEDGE-3450 - add ignoreImageType to getComposes endpoint

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/ImageCreator.js, src/Components/CreateImageWizard/formComponents/ArchSelect.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/formComponents/TargetEnvironment.js, src/Components/CreateImageWizard/steps/imageOutput.js, src/constants.js, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/CreateImageWizard/formComponents/TargetEnvironment.test.js, src/test/fixtures/architectures.ts
This commit extends the supported architectures to aarch64. In the image output step (the first one of the wizard) the user is now faced with a new select choices to pickup the architecture they want to build.
Now the set of compatible targets to build is dynamically loaded from the backend and the UX changes what's accessible on the fly depending on what the user has selected.
HMS-1135: done
[Screencast from 2023-10-16 12-59-58.webm](https://github.com/RedHatInsights/image-builder-frontend/assets/86971992/f200004d-f911-4576-91a0-1e2c70312d82)
=> wizard: allow the creation of aarch64 images

.github/workflows/dev-checks.yml
As Travis CI is getting removed from RedHatInsights this should replace it in what we used to use Travis for.
This workflow is triggered on pull requests to main and runs clean install of dependencies, lint check and the unit test suite.
The main motivation of this workflow being separated from the IQE tests is to allow to quickly check if the basic tests pass during development without the need to wait for the IQE tests to finish their run.
=> workflows: Add a workflow with dev checks

src/Components/ImagesTable/Instance.tsx
This fixes an uneven padding for disabled "Download (....)" links.
=> ImagesTable: Fix padding of disabled download links

src/store/enhancedImageBuilderApi.ts
FIX # https://github.com/RedHatInsights/image-builder-frontend/issues/1410 
this commit add region name when user share to new region for image
=> ImageTable: add region name to new region message

api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/formComponents/TargetEnvironment.js, src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/ImagesTable/Status.tsx, src/Components/ImagesTable/Target.tsx, src/constants.js, src/store/imageBuilderApi.ts, src/store/typeGuards.ts, src/test/fixtures/composes.ts
This exposes the option to create OCI images in the Wizard. The feature is available only for Preview for now.
I've also added mock fixtures for an OCI image to have an example of how the data are displayed.
=> HMS-2782: Expose OCI in the Wizard

.eslintrc.yml, package-lock.json, package.json
This adds eslint-plugin-jsx-a11y to the eslint configuration, setting up recommended set of rules for accessibility testing.
The error output by `jsx-a11y/no-autofocus` on encountering `autoFocus` attribute was switched to warning for now as whether to auto focus on an element or not can be highly contextual.
Fixes #948
=> eslint: Add accessibility rules

src/Components/CreateImageWizardV2/CreateImageWizard.scss, src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ArchSelect.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/CentOSAcknowledgement.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/Environment.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ImageOutput.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizardV2/steps/Review/imageOutput.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/ImageOutput.test.tsx
Brings in the first step of the wizard v2. (also the review step, that'll help for integration testing). Here's what's new in the wizardV2:
The code is organised as followed:
- CreateImageWizard is the root and contains all the code associated
with the PF wizard. (i.e Wizard and WizardStep).
- Each step has its code under the step/ sub directory.
- The step directory is named after the step (i.e ImageOutput for the
Image Output step
- At the root of the step directory there is a `step.tsx` file which
contains the code of the step. in step/ImageOutput/step.tsx there is
an exported `ImageOutput` component.
- The main component of the step can access many subcomponents and they
have to be stored alongside it in its directory.
State management:
- The state management is only done with react …
=> HMS-2860: add the image output step to the new wizard v2

src/Components/CreateImageWizard/formComponents/MountPoint.js
The updated mountpoint policy merged in osbuild-composer upstream does not allow sub-directories of `/usr` to be placed on a separate partition. There are other changes, but this fix prevents users from making an obvious error during image creation, until the updated policy is reflected in the UI.
Related to https://issues.redhat.com/browse/COMPOSER-2030
=> Wizard/MountPoint: hotfix for updated mountpoint policy

src/Components/CreateImageWizard/formComponents/Packages.js, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js
The first commit cleans up some of the warnings related to the exhaustive dependencies rule.
The second commit fixes the bug in the packages search where hitting 'enter' causes a re-render and return to the first page of the wizard.
=> Fix HMS-3031

README.md
this commit adds an explanation to the readme file about how to add ssl certification to your computer (if you work on MAC) to be able to run `npm run stage-beta:msw`
=> README.md: add mac OS mock service worker instructions

src/Components/CreateImageWizard/formComponents/Repositories.js, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
This commit resolves #1201. 
It adds a toggle to the repositories step that allows users to toggle between all and selected repositories.
=> Wizard: add all/selected toggle buttons to custom repository step

src/test/fixtures/composes.ts
This updates the names of images to how should they look like according to the image name validation rules in Wizard.
_"The image name can be 3-63 characters long. It can contain lowercase letters, digits and hyphens, has to start with a letter and cannot end with a hyphen."_
=> fixtures: Update image names

README.md
This adds steps for setting up certificates needed in order to run msw with mocked data.
edit: Also moved the MSW instructions under the section about testing. Does that make sense?
=> README: Setup certificate for msw

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/UsrSubDirectoriesDisabled.js, src/test/fixtures/composes.ts
Paths with `/usr` sub-directories are no longer supported in file system configuration. This meant that an attempt to create an image with the erroneous path ended in an image build not starting but there was also no error displayed. 
The option to add a sub-directory to the `/usr` path was removed in https://github.com/RedHatInsights/image-builder-frontend/pull/1429. This is a follow up PR, that handles the same problem specifically for the Recreate action.
=> Wizard: Disable `/usr` sub-directories on Recreate

src/Components/CreateImageWizard/formComponents/Packages.js
Instead of always searching through x86 repos, search through the repos of the selected architecture. This fixes HMS-3066.
---
=> CreateImageWizard: package search through correct architecture

api/config/rhsm.ts, src/Components/CreateImageWizard/formComponents/ActivationKeys.js, src/Components/CreateImageWizard/steps/registration.js, src/store/rhsmApi.ts, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This PR adds an empty state to the activation key select, enabling a fast and convenient default activation key creation from the wizard's screen.
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/21b2e35e-5a23-4540-8747-7830b0d08834
=> feat(HMS-2789): simplify activation key creation

src/Components/CreateImageWizard/CreateImageWizard.js
This replaces hard coded 'x86_64' architecture with the value based on a form state for OCI images.
=> Wizard: Remove hard coded architecture from OCI request

src/Components/CreateImageWizard/steps/fileSystemConfiguration.js
Information about automatic partioning was also being displayed when manual partioning was selected. This commit fixes the bug.
=> Wizard: Fix HMS-2036, bug in file system customization steps

src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
`isBeta` is a function, so the check would also return true in stable.
=> CreateImageWizard: proprely gate WSL images

.github/dependabot.yml
This bumps a maximum number of opened dependabot PRs as there are currently three open PRs in need of manual revision. Those are blocking any other bumps from being even opened.
The bump should be temporary.
=> dependabot: Bump open PR limit

src/store/enhancedImageBuilderApi.ts
When a compose request was failing, the promises callback function was crashing. The reason was because of a misuse of the error object. This commit simply puts back the correct `path` to access the values within the error object to fix it.
=> api/imageBuilder: fix the alert in case of failure

src/api.js, src/test/Components/LandingPage/LandingPage.test.js
This removes `getVersion()` API call previously used in Axios.
=> API/test: Remove getVersion() Axios call

src/Components/ImagesTable/ClonesTable.tsx
this commit fix the fix grey box under AMI when image build is in progress
FIXES # https://github.com/RedHatInsights/image-builder-frontend/issues/1362
=> ImagesTable: fix grey box under AMI when image build is in progress

src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
this comit fixes the array-callback warning by changing map to foreach
and return null to the second map
=> fsc: fix array-callback-return linting warnings

.travis.yml
This disables npm caching for all Travis runs. The effect on the duration of the run is not significant and it should prevent problems with dirty cache in the future.
=> Travis: Disable npm cache

.eslintrc.yml
This temporarily disables jsx-a11y/no-autofocus rule. A comment marking the disabled rule was added and another disabled rule was moved under it as well.
=> ESLint: Temporarily disable non actionable rules

src/Components/CreateImageWizard/formComponents/Oscap.js, src/Components/CreateImageWizard/formComponents/OscapProfileInformation.tsx, src/Components/CreateImageWizard/formComponents/ReviewStep.js, src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js, src/Components/CreateImageWizard/steps/oscap.js, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/fixtures/composes.ts, src/test/fixtures/oscap.ts, src/test/mocks/handlers.js
Before, in the Oscap step, the drop down select menu was only listing profile_ids
Now, it shows the profiles names. When the user selects one, the details about the
profile are displayed under the selection, improving user experience.
FIXES # - HMS-3087
=> wizard/oscap: update the oscap step to latest specifications

package-lock.json, package.json
This bumps @redhat-cloud-services/frontend-components from 4.0.10 to version 4.2.1 and also adds @redhat-cloud-services module to "transformIgnorePatterns" to eliminate problems with transpiling.
=> deps: Bump @redhat-cloud-services/frontend-components to 4.2.1

.eslintrc-typescript.yml, .eslintrc.yml, src/Components/ImagesTable/ClonesTable.tsx
This removes some of the temporary rule overrides and fixes one occurrence of no-unused-vars.
=> ESLint: Remove temporary rule overrides and fix a lint problem

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ArchSelect.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/CentOSAcknowledgement.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/index.tsx, src/constants.js, src/store/index.ts, src/store/listenerMiddleware.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx, tsconfig.json
This PR adds the Image Output step to the V2 wizard.
All relevant tests are passing.
The wizard's state is now managed using RTK query and is visible using the Redux devtools.
Note that for the most part, our existing components can easily be converted from using DDF to RTK. Calls to `change()` in DDF are updated to calls to `dispatch()`, and calls to `getState()` are update to calls to the relevant Redux selector.
RTK's listeners are used to ensure that the wizard's state is always "correct" (i.e., "infeasible" states are automatically corrected by the listeners):
=> V2 Wizard - Image Output

src/App.js, src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js, src/Components/CreateImageWizard/formComponents/ActivationKeys.js, src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js, src/Components/CreateImageWizard/formComponents/FileSystemConfigButtons.js, src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/formComponents/MountPoint.js
This commit addresses warnings related to the react-hooks/exhaustive-deps rule.
It resolves these warnings by adding the missing dependencies to the useEffect hook.
This ensures that all necessary dependencies are correctly specified, aligning with the recommended usage patterns for React hooks.
=> app: useEffect warning fixes

src/Components/CreateImageWizardV2/CreateImageWizard.tsx
Fixes #1552.
The wizardSlice's reset wizard action was not working because when it was passed to `dispatch()` as an argument it was missing the `()`... oops!
It also needs to be dispatched inside of a useEffect hook with an empty dependency array so that it is only dispatched once, when the wizard opens.
=> V2Wizard: Fix wizard reset action

src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/CreateImageWizard/formComponents/TargetEnvironment.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/LandingPage/LandingPage.test.js, src/test/Components/ShareImageModal/ShareImageModal.test.js
Components sometimes render slower than tests run which causes failures when the test suite expects elements that did not finish their rendering yet.
This should help to prevent most of possible problems with the rendering speed.
=> test: Replace `.getBy` queries by awaited `.findBy`

src/Components/CreateImageWizard/formComponents/Packages.js
When a package is added to the chosen packages it stays in the list of available packages, but gets disabled as an option.
This adds a visual indication in a form of greyed out name of the package.
Before:
After:
=> Wizard: Indicate disabled packages

package-lock.json, package.json, src/store/index.ts, src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
This bumps:
- redux from 4.2.1 to 5.0.1
- @reduxjs/toolkit from 1.9.5 to 2.0.1
Test started to fail so some logic was moved to async.
=> deps: Manual bump redux from 4.2.1 to 5.0.1 and @reduxjs/toolkit from 1.9.5 to 2.0.1

src/Components/Blueprints/BlueprintCard.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/test/Components/Blueprints/Blueprints.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/LandingPage/LandingPage.test.js, src/test/fixtures/blueprints.ts, src/test/mocks/handlers.js
This PR adds an initial layout for the blueprints feature.
It uses the `/experimental` endpoint for fetching real blueprints from stage.
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/19690de5-81a3-4fb8-9002-6b015c6bf5f5
=> feat(HMS-3386): add blueprints initial layout

src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
Commit bae6435fd92797e1879ff6f2798c11819e1dbff0 adds scaffolding for the blueprint table. Blueprint features should be hidden behind experimental flags. The new buttons related to creating blueprints and rebuilding images in the header were not hidden behind the experimental flag, this commit fixes that and does so.
bae6435fd92797e1879ff6f2798c11819e1dbff0 also changed the header title from "Image Builder" to "Images". This change has been a long time coming - it is being left in for now. We may want to revisit the copy in the popovers to align it as the term "Image Builder" is still being used in those.
=> LandingPage: Hotfix to remove exposed blueprint buttons

.github/workflows/dev-checks.yml, api/README.md, api/codegen.sh, api/pull.sh, package.json
For checking wether the api was tempered with, we need separate action, that just checks the code against the currently pulled spec.
This introduces two subactions for `npx api`.
These are `npx api:generate` and `npx api:pull`.
=> api: split pulling API changes and regenerating new API

src/Components/ImagesTable/ImagesTable.tsx
It is important we have an error state for times that we may need to bring the image builder service down for whatever reason.
=> ImagesTable: Add error state

src/Components/CreateImageWizard/formComponents/CustomButtons.js, src/Components/CreateImageWizard/formComponents/ReviewStep.js
This temporarily disables recreating images containing custom repos.
Changes were marked with "Temporarily disable" and "REMOVE" comments to make the revert easier.
=> Wizard: Temporarily disable Recreate for images with custom repositories

src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This removes a leftover debugging statement and changes `getBy` query to an awaited async `findBy` as this was causing problems in the test when the checked component wasn't immediately available.
=> test: Remove debugging statement and change `getBy` query to `findBy`

src/test/.eslintrc
This adds `testing-library/no-debugging-utils` rule to output an error when a debugging statement was left over in the code.
https://github.com/RedHatInsights/image-builder-frontend/pull/1596 needs to be merged first.
Can be tested by adding `screen.logTestingPlaygroundURL();` to a test file.
=> ESLint: Add no-debugging-utils rule

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizardV2/steps/Repositories/RepositoriesStatus.tsx, src/Components/CreateImageWizardV2/steps/Repositories/RepositoryUnavailable.tsx, src/Components/CreateImageWizardV2/steps/Repositories/index.tsx, src/Components/CreateImageWizardV2/utilities/checkRepositoriesAvailability.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This PR adds Repository step to the V2Wizard. Files were migrated to TypeScript, new directory was created for utilities that are used across more steps and `.content` test suite was added and updates so only relevant tests are enabled.
=> V2Wizard: Add Repositories step

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx, src/store/wizardSlice.ts
This commit fixes the "A component is changing an uncontrolled input to be controlled" error in React components by ensuring input values are consistently initialized as strings. Previously, values initialized as undefined led to inconsistencies in controlled component behavior. By initializing with empty strings or using value={someValue ?? ''}, we ensure that input components remain controlled throughout their lifecycle, complying with React's expectations for controlled components and enhancing overall component stability.
=> Resolve Controlled Component Error by Initializing with Empty Strings

src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/LandingPage/LandingPage.tsx, src/test/Components/Blueprints/Blueprints.test.js, src/test/mocks/handlers.js
Enables Blueprints filtering.
Given this is a server side filtering, it also adds Debounce hook.
This hook enables delay the API request to save server roundtrips.
Refs HMS-3389
[Screencast from 2024-01-30 10-19-03.webm](https://github.com/RedHatInsights/image-builder-frontend/assets/2884324/80030cc9-81ae-4d92-820b-036e5ed45702)
=> Blueprints: add Blueprints filtering

src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
this commit fix https://github.com/RedHatInsights/image-builder-frontend/issues/1615
add the relevant data to release lifeCycle at review step
=> feat(HMS-3555) V2Wizard: fix ReleaseLifecycle component in the Review step

src/Components/ImagesTable/ImagesTable.tsx, src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/store/enhancedImageBuilderApi.ts, src/test/Components/Blueprints/Blueprints.test.js, src/test/mocks/handlers.js
_This feature should be visible only in experimental mode_ 
This PR adds the `Build images` functionality for building a blueprint's images.
A notification will shown if the build has been started successfully or it ended with an error:
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/b87e8232-4877-42e9-9e3a-419f90378089
=> feat(HMS-3431): add a blueprint build images

src/Components/ImagesTable/ImagesTable.tsx, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/fixtures/blueprints.ts
This PR adds a new `version` column in the image table,  only when a blueprint is picked:
=> feat(HMS-3392): add blueprint's version in image table

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
this ommit fix a bug with missing title at aws step above the 'us-east-1'
=> feat(HMS-3566) V2Wizrd: fix titles at aws step

src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
This removes the aspect ratio for chart and sets `maintainAspectRatio` to false.
The aspect ratio was causing problems with the annotation plugin, rendering the currentDate annotation line in a wrong place for some windows sizes.
=> Wizard: Remove aspect ratio for chart

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/steps/Details/index.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/Components/CreateImageWizardV2/validators.ts, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/store/enhancedImageBuilderApi.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This PR adds a handler for submitting  the blueprint's wizard, by implementing a mapper from redux store (wizard slice) to a valid blueprint creation request.
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/4264d958-46c7-49c4-a548-383ea900390b
=> Blueprints: Add handler for creating new blueprint

src/Components/CreateImageWizardV2/steps/Review/Footer.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/constants.js, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx, src/test/mocks/handlers.js
We need to start using `undefined` as the default state for when a value
has not been defined. Previously we had used things like `’’` for string
typed values. But this causes problems later when generating the request
we send to image-builder. Using `undefined` is explicit and will make
generating the requests much easier (as we don’t need to check for `’’`,
determine the intent, and convert it to undefined if necessary).
Explicit is better than implicit.
With that in mind, tests have been added to ensure that the correct
request is sent to the API for every option on the Registration step.
This is facilitated using a new `spyOnRequest()` function. In the
future, we will have similar tests for the rest of the steps.
A few other minor things:
1. We need to get the `store` using …
=>  V2Wizard/Registration: Add request assertion tests 

README.md
Let's save our contributors a hop and not link to the (deprecated) devel/README.md anymore, which is only a placeholder pointing to osubild-getting-started. Let's instead direct folks there in the first place.
This will also unblock periodically pulling the frontend docs into the developer guide: https://github.com/osbuild/osbuild.github.io/pull/40
I'd rather not fix the broken link there by pulling in an empty page.
=> README: Link to osbuild-getting-started

src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This increases the timeout of 'image name invalid for more than 63 chars' to 20000.
=> test: Up timeout for 'image name invalid for more than 63 chars'

src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
This adds guest-image and vsphere-ova as possible target environments to the requestMapper.
=> Blueprints: Add guest-image and vsphere-ova to requestMapper

src/Components/Blueprints/BlueprintCard.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/test/Components/Blueprints/Blueprints.test.js, src/test/fixtures/blueprints.ts
I am marking this as draft for now. There are some things that might not have been in the scope of this PR or that I am not so sure of.
1. I have changed the "Show all" button into a card, as I think that Patternfly [deselectable cards](https://www.patternfly.org/components/card/#selectable-cards-deprecated) is deprecated. I tried to make the cards deselectable but did not succeed. I thought that as a solution, we might make the Card component from the "Show all" button. Choosing this card would deselect an already chosen card. Let me know if you think that my assumption about the deprecated deselectable cards is invalid, and if we can keep the button.
2. Issue 3515 states the following: _Move blueprint's kebab dropdown to the right sidebar toolbar, should be enabled only when a blueprint …
=> feat(HMS-3515): Change blueprint cards to be clickable

api/schema/contentSources.json, src/Components/CreateImageWizard/formComponents/Repositories.js, src/store/contentSourcesApi.ts, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/fixtures/composes.ts, src/test/fixtures/repositories.ts
Content sources now support module_hotfixes flag, which is also supported by image-builder API (https://github.com/osbuild/image-builder/pull/928).
This passes this flag from ContentSources to the Compose request, to adhere to what user had set in Content sources. 
This flag allows for disabling unwanted modularity filtering.
=> feat(HMS-3341): pass module_hotfixes flag to compose request

src/test/Components/CreateImageWizardV2/CreateImageWizard.azure.test.tsx
This removes `@ts-ignore` instances in the Azure test suite.
=> test: Remove `@ts-ignore` comments

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
This removes bulk select and a refresh button from the Packages step and updates tests accordingly.
=> V2Wizard: Remove bulk select and refresh button from the Packages step

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
this commit fix https://github.com/osbuild/image-builder-frontend/issues/1691 when user change the source name, resource gruop should clean up
=> V2Wizrd: clean resource group when user change the source name

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This adds `autoFocus` attribute to radios on AWS, Azure and GCP step.
The Keyboard accessibility tests have been re-enabled.
Autofocus is currently not working on steps with a search input. As the changes will need to be more complex I've opened an issue for now: https://github.com/osbuild/image-builder-frontend/issues/1713
=> V2Wizard/test: Add autofocus and enable Keyboard accessibility tests (HMS-2781)

src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This fixes a bug on the registration step which made the text "Connect to Red Hat Insights" not to get rendered when registering with rhc.
All registration tests were also enabled in CreateImageWizard.test.tsx
=> V2Wizard/test: Fix bug on registration step and enable tests (HMS-2781)

src/Components/CreateImageWizard/formComponents/ImageOutputReleaseSelect.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Adding an optional search parameter to the wizard like so:
/insights/image-builder/imagewizard?release=rhel8
results in the wizard being opened and RHEL 8 being pre-selected as the release.
The Insights assistant chat bot will make use of this feature.
=> V1 Wizard: Add search parameter for release selection (HMS-3684)

src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
This removes "component=dl" from the OSCAP information.
Before:
After:
=> V2Wizard: Clean up OSCAP info (HMS-2781)

api/config/imageBuilder.ts, src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/EditImageWizard.tsx, src/Components/CreateImageWizardV2/index.js, src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/Router.js, src/store/enhancedImageBuilderApi.ts, src/store/imageBuilderApi.ts, src/store/wizardSlice.ts, src/test/Components/Blueprints/Blueprints.test.js, src/test/fixtures/blueprints.ts, src/test/mocks/handlers.js
This PR adds editing blueprints capabilities.
When a user clicks on `Edit details` or navigate to `/imagewizard/<BLUEPRINT_ID>`  the wizard opens  in the review step with preloaded blueprint's data, by mapping the blueprint's request to the state.
=> Blueprints: Add blueprint editing

src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
This capitalises id -> ID in the test of an alert on Azure step to keep consistent with the capitalisation throughout the step.
=> V1/V2Wizard: Capitalise ID on Azure step

src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
This moves the "Additional customizations" alert outside of OscapProfileInformation which ensures it is not shown in the Oscap expandable on the Review step.
User can see the added customisations in the individual expandables, making the alert non-actionable extra information.
=> V2Wizard: Move OSCAP alert outside of OscapProfileInformation (HMS-2781)

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
Adding an optional search parameter to the V2 wizard like so:
/insights/image-builder/imagewizard?release=rhel8
results in the wizard being opened and RHEL 8 being pre-selected as the release.
The Insights assistant chat bot will make use of this feature.
The render() test utility function had to be updated to accept an
optional searchParams argument.
=> V2 Wizard: Add search parameter for release selection (HMS-3684)

src/Components/CreateImageWizardV2/steps/Registration/ActivationKeyInformation.tsx, src/Components/CreateImageWizardV2/steps/Registration/index.tsx
This moves the FormGroup outside of the ActivationKeyInformation component and puts it higher into index of the Registration step. This way the group label does not get rendered on the Review step.
Before:
After:
=> V2Wizard: Move FormGroup outside of ActivationKeyInformation (HMS-2781)

src/Components/ImagesTable/ImagesTable.tsx, src/test/Components/Blueprints/Blueprints.test.js, src/test/fixtures/blueprints.ts, src/test/mocks/handlers.js
Fixes #1734.
The blueprint out of sync alert appears when clearing the selected blueprint, as you can see here:
https://github.com/osbuild/image-builder-frontend/assets/11807069/0d0a5124-f28b-4a14-a656-a1cf8ddcec47
Also it blends with the empty state:
=> fix(HMS-3704): hiding blueprint out of sync alert

src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
This removes aspectRatio from the ReleaseLifecycle chart. The set aspectRatio was causing incorrect rendering of the annotation line, making time travel during image building inevitable.
=> V2Wizard: Remove aspectRatio

src/Components/ImagesTable/EmptyState.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/Utilities/useExperimentalFlag.ts, src/test/Components/Blueprints/Blueprints.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.azure.test.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/Components/LandingPage/LandingPage.test.js
When the unleash switch `image-builder.new-wizard.enabled` will get activated on stage the blueprint and new wizard will be visible on the platform.
To make them only visible in preview we need to change the condition to check if Beta is selected by the user.
=> App: experimental features in beta only

src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/LandingPage/LandingPage.tsx, src/test/Components/Blueprints/Blueprints.test.js
Three simple commits:
1. Removes quickstarts
2. Removes `Create image` button from table
3. Changes `Clear selection` card to button
=> Blueprints Table: Minor fixes (HMS-3385)

src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The "Step Details image name invalid for more than 63 chars" is often timing out. The timeout was already increased in V2, this makes the same change for V1.
=> test: Increase timeout for CreateImageWizard test

src/Components/ImagesTable/ImagesTable.tsx
Adds title to blueprints table. Later we will need to extract this into a new component that changes the value depending on whether a blueprint is selected or not (if blueprint is selected, it will need to show blueprint name).
=> Blueprints table: Add title (HMS-3385)

src/Components/Blueprints/BlueprintActionsMenu.tsx, src/Components/Blueprints/BlueprintCard.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/LandingPage/LandingPage.tsx, src/store/BlueprintSlice.ts, src/store/index.ts
Made on top of  #1654, first two commits unrelated. 
This PR adds blueprints slice for managing blueprints client state globally. Multiple components use these data as props and args, and for keeping it consistent when a change occurs,  redux slice gives a clean solution.
=> Blueprints: add blueprints slice for client global state 

src/Components/Blueprints/BlueprintsSideBar.tsx
Fixes the empty state create button to actually open an image (Blueprint) wizard.
=> Blueprints: Empty state create button

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/constants.js
This updates the naming and the icons in the "Packages repository" column to be consistent with current mocks.
Before:
After:
=> V2Wizard: Update repository icons and names on Packages step (HMS-2864)

src/Components/LandingPage/LandingPage.tsx, src/Components/LandingPage/NewAlert.tsx
Adds an alert to explain the basic concept of blueprints to users. Actual copy (and presence of emojis) is pending feedback from UX/copy, this is just a placeholder for now.
=> Blueprints Table: Add "new" alert

src/Router.js
We failed to update the experimental flag in the routing to use the new useExperimentalFlag hook. This led to the V2 wizard being exposed in stage-stable. This commit fixes the bug.
=> Router: Hotfix to update experimental flag

src/Components/Blueprints/BuildImagesButton.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/ImagesTableToolbar.tsx
This extracts the toolbar, that was getting bit too big to a separate component. It also adjusts the title to correspond to the filter of the images. If there is a Blueprint selected, it changes the title to '<BlueprintName> images'
=> ImagesTable: extract toolbar to separate component

src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx, src/test/fixtures/architectures.ts
Adds tests that ensure the blueprint request is generated correctly for all releases (rhel 8 & 9, centos 8 & 9) and for both architectures (x86_64 and aarch64).
=> V2 Wizard Tests: Add tests for release and architecture

src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
FSC customisations are not being applied to bare metal - installer images, this adds an alert to make users aware of the fact.
=> Wizard: Add FSC alert for bare metal images

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
This mirrors the functionality of https://github.com/osbuild/image-builder-frontend/pull/1786 in V2Wizard.
An alert was added to the FSC step to make users aware that customisations are not being applied to bare metal - installer images.
=> V2Wizard: Add FSC alert for bare metal images

src/Components/Blueprints/BlueprintsSideBar.tsx, src/test/Components/Blueprints/Blueprints.test.js
Convert Empty state action to a link and add test for it.
=> Blueprint: Empty state action is link now

.eslintrc-typescript.yml, src/Components/CreateImageWizard/formComponents/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx, src/store/enhancedImageBuilderApi.ts
This turns ban-ts-comment rule on, adds some configuration to it and fixes the errors caused by changing linting.
The current rule allows ts-expect-error and ts-ignore, but only when accompanied by a description with a minimum length of 5 characters.
=> ESLint: Turn ban-ts-comment rule on

src/Components/CreateImageWizard/formComponents/ArchSelect.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Add an optional search parameter to the wizard like so:
```
/insights/image-builder/imagewizard?arch=aarch64
```
This results in the wizard being opened and `aarch64` being pre-selected as the architecture (as opposed to the default `x86_64`). The Insights assistant chat bot and our websites (access.redhat.com and developers.redhat.com) will make use of this feature.
This has been shamelessly cargo-culted from 349377267251a395e2b96a8f1afb97af85a8f401
=> V1 Wizard: Add search parameter for arch selection (HMS-3684)

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
This makes the drop down for root partition disabled, preventing the user from creating a configuration without a root partition.
Option to add suffix was also removed for mount points which don't allow suffixes.
=> V2Wizard: Disable changing of root partition

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
Add an optional search parameter to the wizard like so:
/insights/image-builder/imagewizard?arch=aarch64
This results in the wizard being opened and 'aarch64' being pre-selected as the architecture. The Insights assistant chat bot and our websites (access.redhat.com and developers.redhat.com) will make use of this feature.
This is a follow-up of #1798, porting the same functionality to the v2 wizard.
=> V2 Wizard: Add search parameter for arch selection (HMS-3684)

src/Components/Blueprints/BlueprintCard.tsx
Fixes #1770.
If you select a blueprint, edit it, and return to the table, the blueprint should still be selected and its images should appear in the table. 
This fixes a bug where the blueprint card was not selected upon returning to the table after editing. Note that the images table was showing only the images associated with that blueprint as intended.
=> Blueprints: keep blueprint card selected after editing (HMS-3385)

src/Components/LandingPage/NewAlert.tsx
Fixes #1804
This adds a close button to the Blueprints! alert, making it dismissible.
The dismissal persists only throughout a non-refreshed session.
=> Blueprints: Make Blueprints! alert dismissible

src/Components/LandingPage/NewAlert.tsx
This makes the name for the Blueprints! feature alert more specific in the localStorage.
=> Blueprints: More specific storage name

api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Oscap.tsx, src/Components/CreateImageWizard/formComponents/OscapProfileInformation.tsx, src/store/imageBuilderApi.ts, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js
Add masked services as a customization option, since disabling systemd units when the package isn't installed breaks the image build.
This depends on:
https://github.com/osbuild/image-builder/pull/1062 (manually added the API endpoint for the time being)
=> Enable masked systemd services in the frontend (HMS-3661)

src/Components/ImagesTable/ImagesTableToolbar.tsx
Sometimes, when the response from the API was a bit slow, and the name was not yet loaded, while the id was selected, this would end up by showing "undefined images".
=> fixes(HMS-3778): Show image name only after it is loaded

src/Components/CreateImageWizard/formComponents/TargetEnvironment.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Add an optional search parameter to the V1Wizard like so:
`/insights/image-builder/imagewizard?target=iso`
or
`/insights/image-builder/imagewizard?target=qcow`
This results in wizard being opened and iso or qcow target being pre-selected. The Insights assistant chat bot will make use of this feature.
=> V1Wizard: Add search parameter for target selection (HMS-3684)

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
Add an optional search parameter to the wizard like so:
`/insights/image-builder/imagewizard?target=iso`
or
`/insights/image-builder/imagewizard?target=qcow`
This results in wizard being opened and iso or qcow target being pre-selected. The Insights assistant chat bot will make use of this feature.
=> V2Wizard: Add search parameter for target selection (HMS-3684)

src/Utilities/useExperimentalFlag.ts
The useExperimental broken the ability to enforce experimental on developement environment, it is a good idea to be able to do so at least for now.
This fixes it.
=> Experimental: fix the ability to force experimental in developement

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Oscap.tsx, src/Components/CreateImageWizard/formComponents/OscapProfileInformation.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx, src/test/fixtures/oscap.ts
For the UX the user doesn't really need to know that the services are masked, rather than disabled in the backend. We can simplify this and show the masked services as disabled.
=> V1Wizard: masked services -> disabled services (HMS-3661)

src/Components/CreateImageWizard/formComponents/Oscap.tsx
this commit fix a warning-
React Hook useEffect has a missing dependency: 'change'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
=> fix one warning at useEffect on Oscap file

src/Components/CreateImageWizardV2/steps/Details/index.tsx, src/Components/CreateImageWizardV2/validators.ts, src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
We are now validating Blueprint name on the backend to be non-empty. Adds same validation for frontend
Refs HMS-3801
=> Blueprint: Validate Blueprint name is not empty (HMS-3801)

src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx, src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
This resolves the following warning: `Deprecation warning: value provided is not in a recognized RFC2822 or ISO format.` in test output.
=> Wizard: Resolve deprecation warning in test output

src/Components/Blueprints/BlueprintActionsMenu.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
This updates the data-testid of Create button in the header (`Link` component, not OUIA-compliant) and adds a data-testid to the blueprint search input (`SearchInput` component, also not OUIA-compliant).
A testId was also added to the blueprint actions dropdown (`MenuToggle`).
=> Blueprints: Add test ids

src/Components/Blueprints/BlueprintCard.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
The position of each header for the images table differs based on the content. We might want to try and have it fixed (percentage?), but I think it might make sense to leave the formatting based on the content. Therefore, only for empty table, I tried to make it a bit more consistent. Let me know what you think about hardcoding this.
=> Minor improvements to Blueprints UI (HMS-3848)

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
This updates copy shown in a table when too many results are fetched. Also a period was added to the end of the empty state bodies.
Without an exact match
With an exact match
=> V2Wizard: Update "Too many results" copy

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
The copy in the packages table (too many results to show, etc...) was not centered because the table actually has 5 columns, not 4. This fixes the problem.
=> V2Wizard: Center messages in packages table (HMS-2781)

src/Components/CreateImageWizard/formComponents/Repositories.js, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
This adds a full pagination to the bottom of the Repositories step. This allows the user to get to the very end of the repositories list easily.
=> V1Wizard: Add full bottom pagination to Repositories

src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
Fix #1865 
This PR maps the `register-later` subscription type during editing.
=> WizardV2: add 'register-later' to state mapper

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
This adds full pagination to the bottom of Repositories and Packages steps which will allow the user to get to the very end of the tables in a case of many results.
=> V2Wizard: Add full bottom pagination to Repositories and Packages

src/Components/ImagesTable/ImagesTable.tsx
This PR solves issue #1824 and removes the `recreate image` option.
As you can see, `Download compose request` is the only left item, but I'm not sure what is the point to keep it? Blueprints import/export should replace it, no?
=> fix(HMS-3851): remove 'recreate image' from kebab dropdown

src/Components/Blueprints/DeleteBlueprintModal.tsx
This updates the copy on `Delete blueprint` modal as per recent SPUR.
=> Blueprints: Update `Delete blueprint` modal copy

src/Components/Blueprints/BlueprintCard.tsx, src/test/Components/Blueprints/Blueprints.test.js
This PR fixes https://github.com/osbuild/image-builder-frontend/issues/1766 and happens due to [patternfly's bug](https://github.com/patternfly/patternfly-react/issues/9875)
For a workaround i used deprecated ` isSelectableRaised` and ` hasSelectableInput` props, which recommended by patternfly team.
=> fixes(HMS-3853): fix blueprint clear selection

src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
This initializes packages upon a selection of an OpenSCAP profile.
Current logic also fixes a bug previously present in V1 - when changing an OpenSCAP profile with other previously chosen packages, the packages outside of the profile persist and don't get removed.
=> V2Wizard: Initialize packages with OpenSCAP

src/Components/sharedComponents/ImageBuilderHeader.tsx
This updates the Create blueprint and Import buttons based on recent mocks.
mocks:
=> Blueprints: Update button in header

src/Components/ImagesTable/ImagesTableToolbar.tsx
This hides the Build Image button and blueprint actions kabob when no blueprint is selected as per recent mocks.
mocks:
=> Blueprints: No Build Image button without a blueprint

src/Components/Blueprints/BlueprintsSideBar.tsx
This renames the Clear selection button in the blueprints side bar and aligns it to the center.
mocks:
=> Blueprints: Rename Clear selection button and center it

src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx
This replaces VMWare -> VMware as per mocks.
mocks:
=> V2Wizard: Fix VMware capitalisation

src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Oscap/index.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/hooks.ts, src/store/wizardSlice.ts
This PR adds the Openscap step to the wizard request mapper, enabling creation and editing.
I simplify the Openscap component, by reducing the duplicated data in RTK query and wizard slice.
I added a fixed `max-height` for better scrolling, and added description for each policy.
https://github.com/osbuild/image-builder-frontend/assets/11807069/c36b7d1e-56d8-4bb2-be3f-d19fc3b4aab8
=> WizardV2: map oscap to wizard request

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx, src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
We're actually selecting a singular source to share the image with. It's the same in V1 wizard.
=> V2Wizard: Fix plural sources

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx, src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemTable.tsx, src/store/wizardSlice.ts
This PR adds support for re-ordering mount points in file system step by adding `draggable` support for the table.
https://github.com/osbuild/image-builder-frontend/assets/11807069/7ecda742-6288-42db-ab7e-489db4f1e3b2
=> WizardV2: Filesystem draggable mount point

src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
This PR fixes #1826 
This PR adds `MenutToggleAction` in the V2 wizard's menu toggle , so instead of clicking twice for save changes, users can just click on the desired action.
https://github.com/osbuild/image-builder-frontend/assets/11807069/29aa37ff-0dd3-4e01-8a16-7233c5f1ae5c
=> fix(HMS-3850): V2Wizard:use menu toggle for save and build

src/Components/CreateImageWizard/CreateImageWizard.js, src/Components/CreateImageWizard/formComponents/Oscap.tsx
- disable `stig` and `stig_gui` profiles since they don't boot
- ~add `firewalld` to packages needed for `PCI-DSS` profile.~
- promote OpenSCAP to prod stable
I removed the second step since https://github.com/osbuild/image-builder/pull/1110 landed
=> Promote OpenSCAP to prod stable (HMS-2077)

src/test/Components/CreateImageWizardV2/CreateImageWizard.azure.test.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This re-enables test of FSC alert and cleans up previously commented lines of the tests.
The variant for FSC duplicate alert was also switched from warning to danger for the sake of consistency with V1.
=> test: Re-enable FSC tests

src/Components/CreateImageWizardV2/steps/Registration/index.tsx
Noticed there's been a small change in the copy of Registration steps as per Blueprints SPUR. This updates the text.
=> V2Wizard: Update Registration copy

src/Components/sharedComponents/ImageBuilderHeader.tsx
This removes the plus icon from the "Create blueprint" button as per recent review.
=> Blueprints: Remove icon from "Create blueprint" button

src/Components/Blueprints/ImportBlueprintModal.tsx
The `<ActionGroup>` should be a child of `<Form>`, moving it improves the padding on the Import modal.
=> Blueprints: Update Import modal padding

src/Components/Blueprints/BuildImagesButton.tsx, src/Components/ImagesTable/EmptyState.tsx
Add action in the Images Table empty state when Blueprint is selected. Change the icon to plus as it better underlines the action needed to remedy.
=> Blueprints: selected Blueprint Empty state action

src/Components/LandingPage/LandingPage.tsx
This removes "New" label from the Immutable tab.
=> LandingPage: Remove "New" label from Immutable tab

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/ValidatedTextInput.tsx, src/Components/CreateImageWizardV2/steps/Details/index.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/wizardSlice.ts
Store validation status in redux state.
This is bit complex on the redux side, but pretty simple on the components. It allows for reuse of the validation state instead of revalidating wherever needed.
ATM it's just a PoC and it's applied just to Details step, next step would be to apply everywhere, but details are best to showcase the advantage, notice disabling the create button on Review step:
[Screencast from 2024-04-17 20-36-48.webm](https://github.com/osbuild/image-builder-frontend/assets/2884324/15fde597-05b2-4c40-8b50-a1d02002e639)
=> WizardV2: Validate steps through redux state (HMS-3801)

src/Components/ImagesTable/ImagesTable.tsx, src/test/Components/ImagesTable/ImagesTable.test.js
This updates the name of column headers as per recent mocks.
mocks:
=> ImagesTable: Update column headers

src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
This selects a repository on the Custom repositories step when it's added on the Packages step from the recommendations.
The check box is also disabled as removing the repository would have to trigger removal of the added packages as well.
And expandable with explanation about the disabled check box was added.
=> V2Wizard: Select a repository when added from recommendations

src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/wizardSlice.ts
This adds a new field indicating create/edit mode of the wizard to the state.
An alert an a modal were also added to warn users when removing custom repositories that this action can break their packages.
=> V2Wizard: Add `wizardMode` and repo removal modal

src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx
This removes the second "Save" from a save button on Review step.
before:
after:
=> V2Wizard: Update save button

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx, src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/hooks.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js, src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/fixtures/oscap.ts
OpenSCAP profile info is now correctly loaded into the state and verified to be in the final request with tests.
I modified the fixtures for the OpenSCAP profiles. My changes ensure we have a Venn-diagram like overlap when changing from one profile to another where one package is the same, one package is removed, and one package is added. The same is true for the services and partitions. For kernel args it is not so important as that is just a string (as opposed to an array), so it is enough to be different.
I was able to eliminate a useEffect by replacing it with a lazy query trigger function. Setting the second arg `preferCacheValue` to `true` means that a request is only made if cached data is not available.
I modified the Redux reducers a bit to add some additional safety. …
=> V2 Wizard: Fix OpenSCAP step (HMS-2781)

src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx
Adds tests to verify that building an AWS image using either sources or an account id results in a correctly generated request.
=> V2 Wizard: Add AWS tests (HMS-2781)

src/Components/LandingPage/LandingPage.tsx
Added Blueprints title to align with mocks.
=> V2 Wizard: Add Blueprints title to sidebar (HMS-2781)

src/Components/ImagesTable/Instance.tsx
This replaces the "Recreate" option for expired imaged with a disabled download link.
The change is gated behind experimental mode so V1 imagesTable composes are not affected.
=> V2Wizard: Remove "Recreate" option for expired images

src/Components/CreateImageWizardV2/CreateImageWizard.tsx
Disables the back button on the first step of the wizard. Disabling the back button (as opposed to hiding it) is how the wizard works in the Patternfly official examples.
=> V2 Wizard: Disable back on first step (HMS-2781)

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Previously when a package from an other repo was selected, it was still shown under "Other repos" toggle.
As a recommended repository gets added together with the package, it should be shown under "Included repos".
=> V2Wizard: Show selected packages in included repos

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
This adds an empty state specific for "Other repos" toggle.
=> V2Wizard: Add a specific empty state for "Other" toggle
