src/Components/CreateImageWizardV2/steps/Registration/ActivationKeysList.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
I was bothered by the organization's id in Activation key popover not being separated by an empty line. While adding it I've noticed we duplicated the component on Review step. Cleaned up the code a bit and got rid of a useEffect.
=> V2Wizard: Re-use activation popover for Review step

src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx
The popovers for VMware sphere types were not buttons. This caused weird behaviour with "ban" cursor when disabled and not opening popover when enabled.
"ban" cursor:
=> V2Wizard: Fix VMware popovers

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
This updates copy on empty state when no packages are found with "Available" and "Included repos" toggled.
Copy on "Selected" and "Other repos" was also updated.
=> V2Wizard: Update copy on empty state

src/Components/CreateImageWizardV2/steps/Registration/Registration.tsx
This updates the padding around registration options.
before:
after:
=> V2Wizard: Fix padding around registration options

src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/fixtures/oscap.ts
Fixes #1985
This concatenates masked service to the disabled services so both get rendered in the "Disabled service" code block.
Test to check this was also added.
=> V2Wizard: Add masked services to the "Disabled services" code block

src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Registration/ActivationKeyInformation.tsx
This updates padding around the popover button on OpenSCAP step and makes all `<HelpIcon>` icons the default size so it's consistent throughout the Wizard.
before:
after:
=> V2Wizard: Fix padding and size of `<HelpIcon>` button

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemTable.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
This sets a maximum width to the minimum size popover. Also moved code to a reusable component.
before:
after:
=> V2Wizard: Deduplicate minimum size popover and set width

src/Components/ImagesTable/EmptyState.tsx
This adds an empty state for blueprint table when there are no blueprints created.
Changes are gated behind experimental flag and preview so that the original ImagesTable isn't affected.
=> ImagesTable: Update empty state for Blueprints

src/Components/ImagesTable/EmptyState.tsx
This updates empty state for blueprints without images as per recent [mocks](https://www.figma.com/file/9t3owYlJi4M23fUXWpgXCE/HMS-Image-Builder?type=design&node-id=696-15611&mode=design&t=0EaRBEOETA1fn4Yf-0).
before:
after:
=> ImagesTable: Update empty state for blueprint without images

src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx, src/test/fixtures/blueprints.ts
The snapshot_date in the image_request must be a date. snapshot_date is an optional field and if no snapshot is used, the field should be undefined. Previously it was an empty string and this caused image builder to return a code 400 with message "Snapshot date is not in DateOnly (yyyy-mm-dd) format".
=> V2 Wizard: Fix snapshot_date field

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Fixes #2012
Packages from custom repos stayed in the table upon clearing the search input. This show the results only when searchTerm is not empty.
=> V2Wizard: Show packages only with a search term

src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx, src/Components/CreateImageWizardV2/utilities/hasIsoTargetOnly.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizardV2/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
Fixes #1788
This removes an option to manually configure FSC for ISO targets only.
A custom hook `useHasIsoTargetOnly` was added as it will be later needed in `requestMapper`. The current behaviour is so the option to manually configure partitions is not shown to the user for ISO targets only, but the possible FSC customisations from OSCAP profile get applied anyway.
The easiest way to solve this will be checking for `hasIsoTargetOnly` in `requestMapper` and populating the request with customisations / empty array based on the result.
The other way would be stopping the FSC from being populated during OSCAP profile selection. This created a bug when user was still able to click between steps in the nav menu and when they returned to the FSC step the partitions were not populated until the …
=> V2Wizard: Hide an option to manually configure FSC for ISO targets

src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/GCPTarget.test.tsx
Fixes #1555
This reinitializes the state of AWS/Azure/GCP target after it's tile was deselected. This way the state for the target won't be hanging there.
=> V2Wizard: Reinitialize AWS/Azure/GCP after deselecting target

src/Components/CreateImageWizardV2/EditImageWizard.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/constants.js, src/test/Components/Blueprints/Blueprints.test.js, src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizardV2/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx, src/test/fixtures/blueprints.ts, src/test/mocks/handlers.js
Edit mode is now fully tested and working for OpenSCAP profiles. A
handler for the PUT request was added and the fixtures were updated to
support this.
`EditImageWizard.tsx`: Previously we dispatched `initializeWizard()`
while waiting for the blueprintDetails to load. This meant that the
state was incorrect (empty) while the blueprintDetails request was
in flight.
`requestMapper.tsx`: Correctly populate state in edit mode if the
blueprint contains a custom file system – previously custom mountpoints
were dropped and automatic mode was selected.
`spyOnRequest()`: Differentiate between request types (e.g. GET, PUT)
for the same endpoint.
=> V2 Wizard: OpenSCAP edit tests (HMS-2781)

src/Utilities/useExperimentalFlag.ts, src/test/Components/ImagesTable/ImagesTable.test.js, src/test/Components/LandingPage/LandingPage.test.js
This allows us to flip the new wizard in stable :)
I've created the feature flag `image-builder.new-wizard.stable` in both stage and prod, so we can test it out in stage-stable first
=> experimental: Allow switching experimental on in stable

src/store/enhancedImageBuilderApi.ts
Invalidates Composes and ComposeBlueprints tags upon deleting a blueprint so that composes are re-fetched and the table is updated appropriately.
Previously, a deleted blueprints composes would still show in the table until the page was refreshed.
=> BlueprintTable: Invalidate tags on deleteBlueprint

src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx, src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizardV2/utilities/parseSizeUnit.ts, src/Components/CreateImageWizardV2/utilities/requestMapper.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
Fixes #2015
This updates the logic of parsing bytesize into size/unit pair.
Currently 'GiB' is set as a default which causes problem with smaller partitions on Edit.
A validation for the min_size is in place and the rule is that the size cannot be smaller than 0 of a given unit. If there was a partition with smaller size in KiB it will break the rule when converted to GiB.
=> V2Wizard: Fix FSC units on Edit

src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
This converts previously used expendable into an info alert.
=> V2Wizard: Expandable to alert for disabled EPEL repo

package.json
This ensures `api:pull` and `api:generate` run in correct order when running `npm run api`.
=> scripts: Run parts of `api` script in correct order

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Packages/components/PackageInfoNotAvailablePopover.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
Previously the repository in the table of packages on the Review step defaulted to "EPEL". This expands the condition to take into account packages added on Edit.
Description is handled in the same way.
The "Not available" text is consistent with how the packages table looks on the Packages step for pkgs populated from the request. A popover with more information was added also to the review table as it contains explanation about the "Not available" text.
=> V2Wizard: Fix repo/description in review table of package on Edit

src/Components/ImagesTable/ImagesTable.tsx, src/Components/LandingPage/LandingPage.tsx
Fixes #933
This applies `isWidthLimited` to the section containing ImagesTable, ensuring the table doesn't get stretched out too much.
The were also two sets of empty tags around ImagesTable return, this removes one of them.
before:
after:
=> LandingPage / ImagesTable: Set max width for the ImagesTable

src/Components/CreateImageWizardV2/validators.ts
Fixes #1554
Case validation for the e-mail field was previously case sensitive, disallowing uppercase letters. This updates the validation to accept both lower and upper case letters.
before:
after:
=> V2Wizard: Make e-mail validation case insensitive

src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js, src/Components/CreateImageWizard/formComponents/Repositories.js, src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemTable.tsx, src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/Components/ImagesTable/ImagesTable.tsx
The tests output contained following warning:
```
console.warn
Th: Table headers must have an accessible name. If the Th is intended to be visually empty,
pass in screenReaderText. If the Th contains only non-text, interactive content such as a checkbox
or expand toggle, pass in an aria-label.
```
This fixes the warning by adding an accesible `screenReaderText` text to every empty table heading cell. The text doesn't get rendered, but is available as an information for screen readers.
=> src: Fix "Table headers must have an accessible name" warning

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
This was feedback from a user related to summit demos
- Removes extra lead/trailing whitespace for the api (not in the input)
=> Bug - V2 Wizard: trim searchterm to prevent illegal characters

src/Components/CreateImageWizardV2/steps/FirstBoot/index.tsx
This PR adds an automatic syntax detection for first boot code editor, by parsing the shebang. 
https://github.com/osbuild/image-builder-frontend/assets/11807069/7277e2b5-691e-4939-8754-85e4be9d6045
=> feat(HMS-4116): support shell, yaml and python in first boot editor

src/Components/CreateImageWizardV2/CreateImageWizard.scss
Super minor change to make the wizard container min-height match the left panel min-height.
=> BUG - Fix UI min-height issue

src/constants.js, src/test/Components/ImagesTable/ImagesTable.test.tsx, src/test/fixtures/architectures.ts
The tradeoff is not being able to discern between a minor version and a major version in the 2 weeks post GA if the images were built using the UI, but I think the tradeoff is worth it. The frontend will never need updating to switch to a new version.
=> src/constants: Use major rhel distros by default

src/Components/CreateImageWizardV2/utilities/requestMapper.ts
Previously created blueprints didn't take into account what the current latest RHEL release is and built the specific minor release that was included in the blueprint. This should fix the bug and also fix snapshots.
=> Blueprints: Fix snapshots + latest release

src/Components/ImagesTable/ImagesTableToolbar.tsx, src/test/Components/Blueprints/Blueprints.test.tsx
this commit add the word 'some' to the toolbar title
=> WizardV2: add 'some' word to image table toolbar title

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js, src/test/Components/CreateImageWizard/CreateImageWizard.test.js, src/test/fixtures/packages.ts, src/test/mocks/handlers.js
Switches over to content sources entirely. For package groups we'll need to use content sources as well, so I think it makes sense. This keeps the custom and distro packages query separated, because we do some heuristics there. 
I also noticed that distro packages are search when there's 2 characters, and custom/recommends when there's 3 or more. Could change this to be consistent.
I removed the v1 wizard test without concent sources entirely.
=> Search against content sources for distro packages  (HMS-4094)

src/Components/Blueprints/ImportBlueprintModal.test.tsx, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizardV2/ImportImageWizard.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.ts, src/Components/CreateImageWizardV2/validators.ts, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/Router.js
Sooo...I think we are ready for a discussion on what we want to export AND import, since this is ready. :)
=> Blueprints: Add import Wizard (HMS-3690)

src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This fixes following typo "Google acount" -> "Google account"
=> WizardV2: fix google account typo

src/Components/ImagesTable/Status.tsx
As far as I saw `error.details` rarely contains a `.reason` again.
It's sometimes directly a string and maybe there is `error.details.s` or it's even a list of strings
I'm really not sure if this is the right place to handle this but the `error.details` are somehow support to contain "arbitrary" stuff... (For this uncertainty it's a draft for now)
Also `\n` does not seem to work with react and `<p>` so I needed this `map()`
=> Status.tsx: show as many different error types as possible (HMS-1442)

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Fixes https://github.com/osbuild/image-builder-frontend/issues/2084
Forget to add the page/perPage.
Using the useMemo prevents quite a bit of repeated logic/rerendering
=> V2Wizard: Fix pagination on Packages step (useMemo)

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizardV2/steps/Repositories/RepositoryUnavailable.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/BulkSelect.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/Empty.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/Error.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/Loading.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/Utilities.ts, src/Components/CreateImageWizardV2/steps/Repositories/index.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/fixtures/repositories.ts, src/test/mocks/handlers.js
- Updated content api usage
- Refactored repositories
- A lot of small changes 
One design change: 
My pm suggested removing the confirmation modal on deletion during the edit screen, I have commented that out and will ask for feedback from all of you. We believe the warning below should be sufficient.
Also updated the empty state screen:
=> Wizard V2: Custom Repositories refactor

src/test/mocks/handlers.js
When switching to using content sources for distro packages an old fixture was left in the handlers. This fixes the issue.
=> test: Fix `'mockPackagesResults' not found`

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
This adds a "clear" button to the package search input. The button appears only when there is already a searchTerm in the input.
=> V2Wizard: Add "clear" to package search (HMS-4182)

src/Components/CreateImageWizardV2/steps/Snapshot/index.tsx
Inform users that the snapshots only apply to RHEL content for now.
---
=> V2Wizard: add alert on snapshot step

src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx, src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizardV2/utilities/hasIsoTargetOnly.ts, src/Components/CreateImageWizardV2/utilities/hasSpecificTargetOnly.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
This adds an alert about OpenSCAP being incompatible with WSL when a WSL target is selected.
In a case of only WSL being selected as a target the OpenSCAP dropdown gets disabled.
=> V2Wizard: Disable OpenSCAP for WSL (HMS-3945)

src/Components/CreateImageWizardV2/steps/Packages/PackageRecommendations.tsx, src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Packages/components/PackageRecommendationDescription.tsx
This adds descriptions to the package recommendations.
=> V2Wizard: Add descriptions to package recommendations (HMS-4187)

src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
This makes the "Create blueprint" button and the "Import" button disabled when the Immutable tab is selected.
=> LandingPage: Make buttons disabled on Immutable (HMS-4182)

src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizardV2/steps/Review/index.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizardV2/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizardV2/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
Fixes #920
This improves the Review step as per recent mocks.
=> V2Wizard: Review step improvements (HMS-4085)

pr_check.sh
This reverts commit e85789f58d6958a71ce217a4ca019a5e265aa39d. It actually makes more sense to use insights-stage
=> Revert "pr_check: change --ref-env to insights-production"

src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx, src/test/fixtures/blueprints.ts
This adds a new 'repositories' fixture to the blueprints as was done for 'oscap'.
Newly added unit tests check that repositories get parsed from and back to request correctly and that when removing previously used repositories an 'Are you sure?' modal pops up.
=> test: Edit mode tests for repositories

src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx, src/Components/ImagesTable/Target.tsx, src/constants.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This moves mapping between target short and full names to the const to make it reusable.
=> V2Wizard: Move targets to a constant

pr_check.sh
This seems to be required in order to deploy without errors.
=> pr_check: remove resource limits for pulp

src/Components/CreateImageWizardV2/steps/Packages/index.tsx
This hides the package recommendations expandable when CentOS is selected as a distribution.
=> V2Wizard: Hide package recommendations for CentOS

src/Components/Blueprints/ImportBlueprintModal.tsx
Yeah, so before it was possible to insert the blueprint file inside the editor. I missed that someone might try to do that. Let's make the whole editor read-only as MVP.
=> fix(HMS-4310): Disable editing of Blueprint file

.github/workflows/dev-checks.yml
With Node 16 being EOL since 09/2023 we could replace it with Node 20 in our development checks.
=> workflows: Replace Node 16 with Node 20

src/Components/CreateImageWizardV2/CreateImageWizard.tsx, src/Components/CreateImageWizardV2/ValidatedTextInput.tsx, src/Components/CreateImageWizardV2/steps/Details/index.tsx, src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx, src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx, src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizardV2/utilities/requestMapper.ts, src/Components/CreateImageWizardV2/utilities/useValidation.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
Use redux hook to validate the form.
This gives us single point of contact for "is the data valid?" while not requiring every redux action touching form data to perform validation.
It's not perfect and might be improved when using external library solving the problems we're having.
Imperfections:
* Pristine state needs to be handled manually
* maintaining the validations externally to the fields
Possible future libraries (reserach needed):
* Redux form - deprecated, but that's what we do currently
* [Final form](https://final-form.org/) considered one of the best, but mostly based on data not being in redux
* IMO best fit and we should embrace not having our form data in redux :) 
* [React hook form](https://www.react-hook-form.com/) (uses mostly uncontrolled componente - not great fit
=> Wizard: validate wizard with Redux Hook

src/Components/Blueprints/BuildImagesButton.tsx, src/Components/ImagesTable/EmptyState.tsx, src/test/Components/Blueprints/Blueprints.test.tsx, src/test/fixtures/blueprints.ts, src/test/fixtures/editMode.ts, src/test/mocks/handlers.js
this commit add support of building an image with mulitple targets, when user build an image, he can choose which targets he wants to build.
=> buildImageButton: add support of building image with mulitple targets <HMS-4066>

src/Components/CreateImageWizardV2/steps/Packages/PackageRecommendations.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
This adds "Powered by RHEL Lightspeed" text and popover to the recommended packages expandable.
=> Wizard: Add Lightspeed to package recommendations (HMS-4340)

src/Components/CreateImageWizardV2/ValidatedTextInput.tsx, src/Components/CreateImageWizardV2/steps/Details/index.tsx, src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx, src/Components/CreateImageWizardV2/utilities/useValidation.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx, src/test/fixtures/blueprints.ts, src/test/mocks/handlers.js
Superseedes #1944 to validate blueprint name uniqueness.
Fetches Bluepritnts with the same name as inputed and when there is already one in the database, fails the validation.
This adds a hack in the ValidatedTextInput to accept error to have a special value 'default'
=> Wizard: validate uniqueness of Blueprint name (HMS-3801)

src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
=> Add ouiaIds for import Modal and button

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/Components/CreateImageWizardV2/steps/Repositories/RepositoriesStatus.tsx, src/Components/CreateImageWizardV2/steps/Repositories/RepositoryUnavailable.tsx, src/Components/CreateImageWizardV2/steps/Repositories/components/Empty.tsx, src/Components/CreateImageWizardV2/steps/Repositories/index.tsx, src/Components/CreateImageWizardV2/steps/Snapshot/index.tsx, src/Components/CreateImageWizardV2/utilities/betaPath.ts, src/constants.ts
This moves both preview and stable links to content to the `constants.ts` file.
=> src: Move content urls to const

src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
The stig profiles have been fixed downstream, so we can re-enable these.
=> wizard/compliance: re-enable stig profiles (HMS-4018)

src/constants.ts
ibutsu stage pipeline were failing because of wrong URL value 
It returns 404 which make test case to fail
https://ibutsu.insights.corp.redhat.com/results/885889cd-d08f-41ac-8248-d2271858c946#7c1c5d63-64e8-436c-bdb5-1cbf739c5b84
=> Updating docs URL with correct values because of 404 error

src/constants.ts
Image builder docs are now hosted under insights only.
=> src/constants: update docs link

src/Components/CreateImageWizardV2/CreateImageWizard.tsx
Follow-up for #2133
Implement error status for a step navigation.
It helps user to see on what step there is an validation error and why they can't create the blueprint.
Implementation is setting a status on a nav item, unfortunatelly the only way I found was through copy pasting the original implementation of WizardNavItem a bit and just changing the status validation.
It works, but it duplicates the Patternfly code :(
=> Wizard: set status on Details step

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
Fixes #2219
The request for package search in custom repositories was sent even when no custom repositories were selected, ending in 400. This fixes the problem.
=> Wizard: Fix 400 when fetching packages

README.md
This updates and cleans up README a bit. There were two API sections that got merged and moved under frontend development. Some typos were also addressed.
=> README: Update and clean up

package.json, src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This increases default test timeout from 10000 to 20000 and timeout for "image name invalid for more than 100 chars and description for 250" to 50000.
This should eliminate test flakes caused by timing out, later it will be "reverted" when the Vitest migration gets merged.
=> jest: Increase test timeout

src/Components/CreateImageWizardV2/utilities/requestMapper.ts, src/Components/CreateImageWizardV2/utilities/useValidation.tsx, src/store/wizardSlice.ts, src/test/fixtures/editMode.ts
Fixes #2220
In cases there is already a state in the wizardSlice, there might have been cases of flicker, when unique request could be started for edit mode, because wizards loads before requestMapper maps the new state of edited blueprints.
In such case, name is not empty (leftover from previous BP create/edit), but wizardMode was not yet set, so defaults to create.
This addresses it by just making sure the validation works as expected in Edit mode.
Now when the name is changed in Edit mode, we run the validation.
We now have the blueprintID in the state, which is empty on create state (might be just easier to recognize mode by id in the future :) )
=> Wizard: fix blueprint unique name validation in Edit mode

src/Components/CreateImageWizardV2/steps/FirstBoot/index.tsx
Add testid to Firstboot buttons.
The code editor [component does not exposes the ouids](https://github.com/patternfly/patternfly-react/blob/c16c6f4a6c64f1d70523f25a5195435971326dde/packages/react-code-editor/src/components/CodeEditor/CodeEditor.tsx#L535) of the buttons, so we are adding inner spans with ids.
```html
<div class="pf-v5-c-empty-state__actions">
<button aria-disabled="false" class="pf-v5-c-button pf-m-primary" type="button" data-ouia-component-type="PF5/Button" data-ouia-safe="true" data-ouia-component-id="OUIA-Generated-Button-primary-3">
<span data-testid="firstboot_browse">Browse</span>
</button>
</div>
<div class="pf-v5-c-empty-state__actions">
<button aria-disabled="false" class="pf-v5-c-button pf-m-link" type="button" data-ouia-component-type="PF5/Button" …
```
=> Firstboot: Add testid to empty state buttons

src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Repositories were not getting recommended after https://github.com/osbuild/image-builder-frontend/pull/2226 got merged. This fixes the problem.
=> Wizard: Fix repositories recommendations

src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
Rebased on https://github.com/osbuild/image-builder-frontend/pull/2238
This removes the `act()` warnings from the test output.
=> test: Fix act warnings 

README.md
This adds information about silencing DOM dumps in testing-library test output and how to allow DOM dump again if needed.
=> README: Add DOM dump silencing to `Test Guidelines`

.github/dependabot.yml
The backlog of stuck dependencies is shrinking, meaning we can go back to previous limit of three open dependabot pull requests.
=> dependabot: Decrease open PR limit

src/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/EditImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/Components/ImagesTable/ImagesTable.test.tsx, src/test/Components/LandingPage/LandingPage.test.tsx, src/test/Components/ShareImageModal/ShareImageModal.test.tsx, src/test/Components/edge/EdgeImagesTable.test.tsx, src/test/Components/edge/ImageDetails.test.tsx, src/test/setup.ts
This removes `@testing-library/jest-dom` from single test files and adds it to the shared setup.ts file.
=> test: Move `@testing-library/jest-dom` import to test setup file

src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
`image-builder.new-wizard.enabled`, `image-builder.wizard.oscap.enabled` and `image-builder.enable-content-sources` are no longer used in the code base and thus don't need to be mocked in tests.
=> test: Remove deprecated flags from mocking

package-lock.json, package.json, src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/ImagesTable/ImagesTable.test.tsx
This bumps vitest to the latest version and adds { retry: 3 } to three of the flakiest tests, this will allow retry on test failures, hopefully improving rate of flakes.
Also who added `npm run test:coverage` script, but forgot to install coverage dependency? Correct, it was me. Dependency is added, `npm run test:coverage` works now just as it did in jest.
=> test: Update vitest, install coverage dependency, add retry to flaky tests

src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/test/fixtures/repositories.ts
If a snapshot date is selected, all selected repositories need to have snapshotting enabled. So disable the ones which don't have snapshotting enabled.
=> Wizard: disable non-snapshot repositories when needed (HMS-4481)

src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
The disabled tests are flaking for Node 18.x only. I'm quite sure the problem lies within async. Working on a fix.
=> test: Temporarily disable flakey Oscap tests

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/ImagesTable/ImagesTableToolbar.tsx, src/test/Components/Blueprints/Blueprints.test.tsx
CentOS 8 was deprecated and is no longer used, but 'On Edit' for a no longer valid blueprint with 'centos-8' as their distribution defaulted to RHEL 9.
=> requestMapper: Automatically replace CentOS 8 with CentOS 9

deploy/iqe-trigger-integration.yml
this commit change the value of SE_NODE_SESSION_TIMEOUT 
from number to string becuase it is blocking auto-promotion test
=> change the value of SE_NODE_SESSION_TIMEOUT from number to string

src/Components/CreateImageWizard/steps/Packages/index.tsx
This replaces `isBeta()` with a constraint added to the 'image-builder.pkgrecs.enabled' unleash flag.
=> Wizard: Replace `isBeta()` with conditional flag (HMS-4513)

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx
This gates WSL target behind an 'image-builder.wsl.enabled' unleash flag instead of `isBeta()`.
=> Wizard: Migrate WSL from `isBeta()` to unleash flag (HMS-4513)

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/CreateImageWizard.tsx
this commit change the resoluiton of wizard__outer-wrap to solve
the problem that user should scroll to see the next, backl and cancel buttons
https://github.com/user-attachments/assets/f54826fb-bf1a-4b2b-81db-516b1793d2c0
=> createImage: change resolution to be able to see buttons in create image wizard (HMS-4485)

src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, vitest.config.ts
`remove profile` and `change profile` test in `Oscap.test.tsx` suite were flaking for Node 18.x, this should fix the issue.
=> test: Fix async logic in Oscap flakes and allow fileParallelism

api/schema/imageBuilder.yaml, src/Components/Blueprints/BlueprintDiffModal.tsx, src/Components/ImagesTable/ImagesTableToolbar.tsx, src/store/imageBuilderApi.ts
This adds a link to the alert about deprecated images, to see a version differenece.
It's fetching both Blueprints and showing json diff for those. We assume this is a PoC for versioning and we'll measure the traction of this link and try to get more feedback and improve as we go.
https://github.com/user-attachments/assets/e5f481a7-dfb8-4847-9ed9-5a689d016180
This depended on (all of it was cleared):
=> Blueprint: show basic version diff (HMS-4511)

src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx
This moves `selectCustomRepo` to `wizardTestUtils.tsx`
Since the function was originally imported into `Packages.test.tsx` from `CreateImageWizard.content.test.tsx` the entire content suite was re-run under Packages suite each time. This solves the issue.
=> test: Move util function to wizardTestUtils

vitest.config.ts
This re-disables `fileParallelism` again as it's still proving too flaky.
=> vitest: Disable `fileParallelism`

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
When a package got selected and deselected again, landing on 0 for selected packages, the information shown in the package recommendations was "Select packages to generate recommendations.No recommendations found for the set of selected packages", this updates the logic to separate the messages.
=> Wizard: Fix information rendered in package recommendations

src/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx, src/test/Components/ImagesTable/ImagesTable.test.tsx, src/test/Components/LandingPage/LandingPage.test.tsx, src/test/testUtils.js
`renderCustomRoutesWithReduxRouter` and `renderWithReduxRouter`are functionally the same apart from routes they use to render components.
We could just use `renderCustomRoutesWithReduxRouter` and use the routes from `renderWithReduxRouter` as a default value for an optional parameter `routes`.
=> testUtils: Merge `renderCustomRoutesWithReduxRouter` and `renderWithReduxRouter`

src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx
This disables `react-hooks/exhaustive-deps` rule for dependency arrays that should run only once on mount and therefore need to stay empty.
=> Wizard: Add eslint-disable to useEffect

src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx, src/test/testUtils.js
As clicking helper functions are used only in the context of Wizard, this moves them to an appropriate place.
=> test: Move clicking helper functions to `wizardTestUtils`

package-lock.json, package.json, vitest.config.ts
This bumps:
- vitest from 2.0.4 to 2.0.5
- @vitest/coverage-v8 from 2.0.4 to 2.0.5
and removes reporter from the coverage setting, leaving only default output for now (console output equal to jest).
=> devDeps: bump vitest and @vitest/coverage-v8

src/Components/CreateImageWizard/steps/FileSystem/FileSystemPartition.tsx, src/Components/CreateImageWizard/steps/FileSystem/index.tsx, src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/store/wizardSlice.ts
This renames `FileSystemPartitionMode` to `FileSystemConfigurationType` in preparation to expose raw/lvm partitioning in the UI: https://github.com/osbuild/image-builder-frontend/pull/2342
=> Wizard: Rename `FileSystemPartitionMode` to `FileSystemConfigurationType`

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTables.tsx, src/Components/CreateImageWizard/utilities/checkRepositoriesAvailability.ts, src/constants.ts
- This ticket just adds a new enum and ensures that Origin is being set in the useListRepositoriesQuery.
Related ticket in HMS [here](https://issues.redhat.com/browse/HMS-4426)
Other changes: 
Added one comment to remind myself to address a performance issue at some point. 
Will address in another ticket at a later time.
=> Wizard: Confirm Image builder is using origin for contentList call

src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx, src/Components/CreateImageWizard/utilities/generateRandomId.ts
Fixes #2353
This adds a random suffix to the default activation key name, making it less predictable.
=> Wizard: Unique default key name

src/Components/CreateImageWizard/CreateImageWizard.tsx
When the option to register with rhc and insights was added back the disableNext condition wasn't updated, allowing user to continue with registration even without selecting activation key.
=> Wizard: Fix disable Next on Registration step

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/constants.ts
This updates snippets used for event tracking in Amplitude, adding `imageBuilder` to the name of the event and as a `module` property.
Two more typed events were also added to track number of created blueprints. Name for both events is the same `blueprintCreated`, the differentiation between Create and Create and build images is captured in the `type` property.
These new events will allow to calculate percentage of users that were shown recommendations and of those who added a recommended package while succesfully finishing blueprint creation.
=> Wizard: Update Amplitude tracking

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
This uses the concept of useValidation for snapshot date.
It is the last validation that doesn't use this.
=> Wizard: Validate snapshot date with useValidation

src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
This cleans up Packages test file after relevant tests were moved there from `CreateImageWizard.content.test.tsx`.
In these cleanups nothing gets deleted, the parts only get moved around to make the flow of the test file less chaotic and where possible blocks of code get replaced by helper functions.
=> test: Cleanup Packages tests (HMS-4658)

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
This adds a component prop to the expandable button, solving the `Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.` warning that was repeatedly printed to the test output.
=> Wizard: Fix "button in a button" warning

.github/workflows/dev-checks.yml, pr_check.sh
This updates the test env to test with Node 20 only, pr_check is also updated to use Node 20.
The changes shouldn't affect users in any way, please let me know if you think it might.
There were common async flakes when using testing-library with Node 18, those often surfaced in gh actions / pr_check only and did not reproduce locally unless resources got limited (I can reproduce some flakes in Power Saver mode only, leading me to conclusion, that it's just async being mischievous). Switching to testing with Node 20 only should also allow us to re-enable some tests that got disabled specifically because them running with Node 18 ended up in a time out.
=> test: Test with Node 20 only

src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/hooks.ts, src/store/wizardSlice.ts
Removing the server store makes the way we handle data going in and out of the wizard state more consistent. Each customisation is mapped into the wizard state and pulled out when generating the blueprint payload.
When the services and kernel customisations are implemented, this information will need to be stored inside of the wizard state anyway.
Lastly this will make implementing a compliance step easier for edit mode, removing the need to write to the wizard state from within the server store when only a compliance policy id is available (on the review page), which would be used to fetch the profile ref id, which would in turn be used to fetch the customisations not stored in the wizard state.
=> src/store: Remove server store hooks

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx
This migrated Registration step validation to `useValidation`.
The scenarios in which the Next button and Create/Save button should be disabled are:
- any of "register now" options is chosen, but no activation key is selected
- activation key is selected, but it's invalid (information about it cannot be fetched)
=> Wizard: Validate registration with useValidation

src/test/Components/CreateImageWizard/EditImageWizard.test.tsx
The content steps were surfaced from previously used Content section and we're now testing with all flags set to true. Updating the list of step nav items that should be enabled.
=> test: Update Edit wizard test

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/test/setup.ts
This adds `isPreview` property to the analytics tracking with the use of chrome's `isBeta()`.
=> Wizard: Add `isPreview` property to analytics tracking

src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Utilities/time.ts, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
Currently the accepted date format in the UI date-picker is `MM/DD/YYYY`, and the API accepts `YYYY-MM-DD` as the date format.
This PR unifies the date formats (to `YYYY-MM-DD`) and removes unnecessary time conversion functions. 😅 
\
Related Ticket: [🔗HMS-4492](https://issues.redhat.com/browse/HMS-4492)
=> Wizard: Unify snapshot date format

src/Components/CreateImageWizard/CreateImageWizard.scss
There's a new bug that's at least partially caused by styling commented out in this PR: when zooming in or out while in Wizard, the Wizard shrunks it's height to an unusable value.
=> Wizard: Temporarily disable fixed footer

src/Components/Blueprints/BlueprintsSideBar.tsx
This dispatches changes to `blueprintSearchInput` and sets it as `undefined` when the value is an empty string.
=> Blueprints: Set `blueprintSearchInput` as undefined with empty string

.eslintignore, api/codegen.sh, api/config/compliance.ts, api/pull.sh, api/schema/compliance.json, api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemPartition.tsx, src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Oscap/OscapProfileInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/constants.ts, src/store/complianceApi.ts, src/store/emptyComplianceApi.ts, src/store/imageBuilderApi.ts, src/store/index.ts, src/store/wizardSlice.ts, src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Compliance.test.tsx, src/test/fixtures/blueprints.ts, src/test/fixtures/compliance.ts, src/test/fixtures/editMode.ts, src/test/mocks/handlers.js
The current state: 
[webm](https://github.com/user-attachments/assets/6b7d0973-473e-4bc5-9748-67d598999552)
One thing worth discussing is how we want to expose the compliance step. Should we show it alongside the existing openscap step? Should the steps be merged?
Since it would only be in preview, how about we just show both steps for now, knowing that they might conflict?
=> Insights Compliance integration (HMS-3829)

src/Components/CreateImageWizard/utilities/requestMapper.ts
when there none of `service.{enabled|masked|disabled}` firstboot also is not enabled (if requested)
this patch fixes this bug
=> CreateImageWizard/requestMapper: fix enabling firstboot

src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
This PR removes the "No repositories selected" message shown in the review step ("Content" > "Repository snapshot") instead of the picked date or the use latest option, if no custom repos are selected.
Related Ticket: [🔗HMS-4483](https://issues.redhat.com/browse/HMS-4483)
=> Wizard: remove no repos selected message

src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx, src/test/fixtures/oscap.ts, vitest.config.ts
This inlines a dependency that was causing problem in test runs and re-enables a test checking request generated when adding first boot script to the blueprint.
=> vitest/test: Inline `@monaco-editor` and enable "First boot request generated correctly" test

src/Components/sharedComponents/ImageBuilderHeader.tsx
This prefetches list of possible targets based on distribution for `onMouseEnter` event of Create blueprint button.
=> src: Prefetch list of targets on hover of Create blueprint button

src/Components/CreateImageWizard/steps/Packages/Packages.tsx
Previously when you searched for package from repositories recommendations and switched to "Other repos", new search left you in Other repos and didn't show results even if they were found in "Included". Since we search for recommendations only when no matches were found in distro and custom repos, the results will be always empty.
This solves the problem by defaulting to "Included repos" toggle with every new search, limiting clicks required from the user.
How to reproduce previous behaviour:
1. search for 'gnuplot' packages
2. no results should be found, switch to "Other repos"
3. search for a distro/custom repo package like "vim"
Previous behaviour - the "Other repos" toggle is still selected, showing no results. When switching to "Included repos" manually, the results can be found …
=> Wizard: Default to Included repos in package search

src/Components/CreateImageWizard/steps/Packages/Packages.tsx
The repos toggle height was slightly bigger than the Available/Selected toggle. This was caused by the popover button. Changes its size to small to fix the issue.
=> Wizard: Fix repos toggle height

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
This implements onKeyDown functionality for the Public cloud tiles, allowing selecting them with a Space key.
Corresponding test was also re-enabled.
=> Wizard/test: Implement keydown for target tiles

src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx
https://github.com/content-services/content-sources-backend/pull/852 beta repos are now bieng introspected, so package search should work.
=> Wizard: move RHEL 9 beta out of preview (HMS-2234)

src/Components/CreateImageWizard/utilities/requestMapper.ts
It would default to RHEL 9 instead of the beta.
=> Wizard: fix editing RHEL 9 beta blueprints

src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx
=> Wizard: use oscap profiles from major version for beta versions

Makefile
Ah I wanted to do a checker but it is now gone, no need for base64 encoding. Nice.
Well, then the Makefile I introduced solely for this purpose can go away. There is `npm` for those who want to build stuff.
=> chore: drop unused Makefile

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This moves the VMware radios into the body of VMware checkbox, following PatternFly's pattern of parent and child checkboxes / form elements: https://www.patternfly.org/components/forms/checkbox#controlled
=> Wizard: Move VMware radios into VMware checkbox

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
This updates the behaviour of VMware checkbox to make it possible to unselect VMware as a target.
How to reproduce:
1. select VMware vSphere checkbox
2. click on Virtual disk radio
3. try to unselect VMware vSphere checkbox
Previous behaviour - the checkbox can't be unselected New behaviour - the checkbox can be unselected, removing relevant type of VMware target from imageTypes
=> Wizard: Fix VMware select and unselect

.tekton/image-builder-frontend-pull-request.yaml, .tekton/image-builder-frontend-push.yaml
Resolves HMS-4948. This task is mandatory as of November 1, 2024.
=>  Konflux: Add rpms-signature-scan task (HMS-4948) 

src/Components/CreateImageWizard/ValidatedTextInput.tsx
adds `type` prop to `HookValidatedInput` with a default of 'text', to be able to support other types input like 'password'
=> Wizard: add support for other input type in`HookValidatedInput`

src/Components/CreateImageWizard/steps/FirstBoot/index.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/fixtures/editMode.ts
Scripts in which lines are terminated by CRLF break the first boot service, so let's make sure the line termination is correct.
=> Wizard: handle dos scripts in first boot (HMS-4966)

src/Components/CreateImageWizard/ValidatedTextInput.tsx, src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx, src/Components/CreateImageWizard/utilities/parseSizeUnit.ts
Some people might define a minsize of their blueprints that is not a certain number of KiB, MiB, GiB. In case we import such blueprint, we would prefill "undefined" string, which is not a valid value.
I think that the same would eventually happen if we created a blueprint using API, I do not think we check for minimal value.
Because we probably do not want to suggest that users should create blueprints with partitioning with minimal size in bytes, I did the following:
If the value is such, that we cannot display it in KiB, MiB or GiB, we have a new unit - Bytes - in the dropdown, and if it is selected, the text field is not editable. In case users click on different units, they can change it, but if they click back on 'B', they have their initial value in bytes again. Does that make …
=> Wizard: Add bytes to min_size partitioning <HMS-4981>

ci.sh
Otherwise fec doesn't pick them up.
=> ci.sh: export sentry variables before calling build

fec.config.js
The paths of each artefact needs to be prefixed to reflect where the static resources are hosted on consoledot (which is under /apps/image-builder).
=> fec.config: prefix paths

package-lock.json, package.json
This reverts #2556 and installs all dependencies from complete zero so there are no leftovers.
=> deps: Revert frontend-components bump, install from zero

src/Components/CreateImageWizard/steps/Registration/Registration.tsx
This temporarily disables rhc option for RHEL 10 Beta registration as it currently doesn't work.
=> Wizard: Disable rhc for RHEL 10 Beta

src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx
Adds feature flags for each of the rhel betas.
=> image-builder-frontend: only show Beta releases if flag is on

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
Previously the Wizard crashed when looking for recommendations for packages that had none.
How to reproduce the crash:
- go to the Packages step
- search for and select `tmux` package
After fix:
- when selecting a `tmux` package or any other package without recommendations, the recommendations stay empty, but the Wizard doesn't crash
=> Wizard: Fix package recommendations

package-lock.json, package.json, src/Components/Blueprints/ImportBlueprintModal.test.tsx, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
This pull request relates to [#4683](https://issues.redhat.com/browse/HMS-4683).
We want to support import on prem blueprints in our import feature. This enables importing toml blueprints that get automatically detected, and parsed.
A lot of fields we need to ignore, a lot of fields from our blueprints are not in the on-prem blueprint structure. This is our first attempt to allow on-prem blueprint, and it will get us more information whether users would use it or not. We also need to add a method to measure the usage of this feature. This is not here yet, and I would like to do it as a follow up, as it can raise discussions, and we do not want to block this feature on it.
We will bring a different solution, so eventually, we will get rid of this mapper. But the other solution that should …
=> src: Add on prem blueprints import support (HMS-4683)

pr_check.sh
We can now skip unit tests (running npn verify) in the pr_check to speed up the whole process and reduce flakiness. The unit tests are ran separately in a github action so this is fine.
=> pr_check: Skip unit tests

src/Components/ImagesTable/ImageBuildStatus.scss
Add the v5 slug to the status colors as the unversioned colors don't seem to be defined in PatternFly anymore. I haven't looked at the history, but I presume this was done at some point during v6 development, as the upstream colors now contain the v6 slug: https://www.patternfly.org/components/banner/design-guidelines/#usage
Fixes #2611
Before:
After:
=> ImageBuildStatus.css: Add version to status colors

src/Components/ImagesTable/ImagesTable.tsx
This adds a component value to the image name, making the spacing work correctly.
Before:
After:
=> ImagesTable: Fix image name spacing

src/store/enhancedImageBuilderApi.ts
There's a case where the IB api returns an error without more data in it, though it might be coming from a component which treats the request before the image builder api.
=> store/enhancedImageBuilderApi: handle empty error data (HMS-5049)

.tekton/image-builder-frontend-pull-request.yaml, .tekton/image-builder-frontend-push.yaml
I've noticed there was an auto-generarated rpms-signature-scan for the Konflux pipelines and it was disabled as it didn't work at the time of migration: https://github.com/osbuild/image-builder-frontend/pull/2524/commits/985c5d2b0f0add8b01fcda69180e2a94d608f326
Comparing it to what we have now, there are some small changes. Not sure if those are completely necessary, but thought they might alleviate hypothetical unpredictable behaviour in the future. :shrug: 
This PR is intentionally split into two commits, one just moves the rpms-signature-scan block lower in the pipeline and the second includes changes to the blocks, so it's hopefully nicer to review.
=> Konflux: Compare rpms-signature-scan with generated pipeline

src/Components/ImagesTable/ImagesTable.tsx
This makes bottom pagination format on ImagesTable consistent with the format being used in Repositories service.
Repositories:
=> ImagesTable: Unify pagination format with Repositories

api/schema/compliance.json, api/schema/imageBuilder.yaml, src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/imageBuilderApi.ts, src/store/wizardSlice.ts
The flag can be used later to track the usage of on prem import feature.
=> Blueprints: Add flag to track on prem import usage

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
This means we can easily link to the wizard and pre-select RHEL 10 Beta which will be nice for the release announcement blog post.
=> CreateImageWizard: Add RHEL10beta search parameter

src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureHyperVSelect.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/fixtures/composes.ts, src/test/fixtures/editMode.ts
HyperV generation will change the uploaded image into a V1/V2 image. V2 supports more instance types, and has UEFI boot.
=> Azure: Add support for selecting HyperV generation

src/Components/CreateImageWizard/steps/Packages/index.tsx
This shows package recommendations only when RHEL 8 or RHEL 9 are selected as a distribution.
=> Wizard: Conditionally hide package recommendations

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Locale/components/KeyboardInput.tsx, src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/CreateImageWizard/steps/Locale/index.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/setup.ts
This adds Locale step basics and file structure.
=> Wizard: LOCALE 1 - Basic Locale step (HMS-5055)

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/wizardSlice.ts
This creates structure and actions for the locale customization in the wizardSlice and requestMapper.
Based on and blocked by https://github.com/osbuild/image-builder-frontend/pull/2625
=> Wizard: LOCALE 2- Add locale structure to store and mapper (HMS-5097)

src/Components/Blueprints/ImportBlueprintModal.test.tsx, src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
This adds Timezone values to the on-prem mapper and updates the import test to check for expected values.
Based on and blocked by https://github.com/osbuild/image-builder-frontend/pull/2613
=> Wizard: TIMEZONE 2a - Add Timezone to on-prem mapper (HMS-5102)

src/Components/CreateImageWizard/steps/Timezone/components/NtpServersInput.tsx, src/Components/CreateImageWizard/validators.ts, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
This adds a validation pattern and a validation for NTP servers field and tests to check the functionality.
Based on and blocked by https://github.com/osbuild/image-builder-frontend/pull/2613
=> Wizard: TIMEZONE 2b - Add validation for NTP servers (HMS-5114)

src/store/enhancedImageBuilderApi.ts
Turns out it can also return `{error: data: {}}`, so without `errors` inside the data object.
=> store/enhancedImageBuilderApi: handle empty error data

src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx
This removes two comments left over after rebasing, both tests are already implemented a bit higher in the file.
=> test: Clean up comments left over after rebasing

ci.sh, fec.config.js, package-lock.json, package.json
Rationale is the same as in  #2662, but we need the module metadata for correct routing. None of these values are actually secret, only the auth token is. And turns out that the webpack plugin justs injects and doesn't upload in case we don't specify the auth token, so that's nice.<br/><br/>JIRA: [HMS-5179](https://issues.redhat.com/browse/HMS-5179)
=> sentry: use webpack plugin for injecting (HMS-5179)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Hostname/components/HostnameInput.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
This adds a validated hostname input and new tests.<br/><br/>JIRA: [HMS-5175](https://issues.redhat.com/browse/HMS-5175)
=> Wizard: Add Hostname functionality (HMS-5175)

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
This adds a new expandable to the Review step.
Based on and blocked by https://github.com/osbuild/image-builder-frontend/pull/2672<br/><br/>JIRA: [HMS-5177](https://issues.redhat.com/browse/HMS-5177)
=> Wizard: Add Hostname expandable to Review step (HMS-5177)

src/Components/CreateImageWizard/validators.ts, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
This adds a test to check the length of the hostname.<br/><br/>JIRA: [HMS-5185](https://issues.redhat.com/browse/HMS-5185)
=> test: Add test to check hostname length (HMS-5185)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelArguments.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelName.tsx, src/Components/CreateImageWizard/steps/Kernel/index.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx, src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx, src/test/setup.ts
This adds foundation for Kernel step, including gating and basic tests.
JIRA: [HMS-5198](https://issues.redhat.com/browse/HMS-5198)
=> Wizard: Kernel step basics (HMS-5198)

.gitignore, Makefile, ci.sh, cockpit/tsconfig.json, cockpit/webpack.config.ts, fec.config.js, src/constants.ts, src/store/cockpitApi.ts, src/store/emptyCockpitApi.ts, src/test/mocks/cockpit/fsinfo.ts, src/test/mocks/cockpit/index.ts, tsconfig.json, vitest.config.ts
We can use the cockpit files api to read in blueprints from disk.
This PR adds commits to bring in the required dependencies, some convenience scripts and an initial commit using an RTK query function to read blueprints from file and pull the details into the store.
=> On-prem: read blueprints from disk (COMPOSER-2413)

src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
This resolves `Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>.` warning in test output. There were two `<Form>` components nested in each other.
JIRA: [HMS-5237](https://issues.redhat.com/browse/HMS-5237)
=> Wizard: Fix "form in form" warning (HMS-5237)

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
this commit add Users to review step - (HMS-4906)
=> wizard: add  Users to review step (HMS-4906)

api/config/contentSources.ts, api/schema/imageBuilder.yaml, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/contentSourcesApi.ts, src/store/imageBuilderApi.ts, src/store/wizardSlice.ts
=> src: add custom repositories import feature

src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
The changes here should format the requested date from YYYY-MM-DD to RFC3339 in the snapshot step of the wizard. This helps content-sources clean up some tech debt and allows us to use RFC3339 for all date formats in our template-related APIs.
Background:
This [PR](https://github.com/content-services/content-sources-backend/pull/839) removed support for YYYY-MM-DD in the request for `/snapshots/for_date/` and broke things. The snapshot step in the wizard needed to be converted to use RFC3339 also. This commit has been reverted and things are good again.
Without these changes in the wizard, errors like this would be seen when calling `/snapshots/for_date/` from the content sources API with an unsupported date format:
```
parsing time \"2024-10-18\" as \"2006-01-02T15:04:05Z07:00\": cannot …
```
=> Wizard: switch snapshot date in wizard to RFC3339

src/Components/ImagesTable/ImagesTable.tsx
The filtering was defaulting to version '1', making images of other versions not appear when selecting a blueprint.
How to reproduce:
1. create a blueprint
2. build an image
3. edit the blueprint to get it to version 2
4. build another image
Current behaviour:
- only image with version 1 is visible
After fix:
- both image for version 1 and image for version 2 of the blueprint should be visible when the blueprint is selected
=> ImagesTable: Fix compose filtering by selected blueprint

src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx, src/store/wizardSlice.ts
Reverts osbuild/image-builder-frontend#2709
Reverting because for now we think the UX of the confirm password field is bad. It makes the user do more work for questionable gains - there is already a 'show password' button, so it feels duplicitous.
=> Revert "wizard: add confirm password to users step (HMS-4903)"

src/Components/CreateImageWizard/ValidatedTextInput.tsx
Fixes #2743
This hides the warning under FSC min size if the body of warning is empty.
Before:
After:
JIRA: [HMS-5327](https://issues.redhat.com/browse/HMS-5327)
=> Wizard: Do not show warning icon if warning === '' (HMS-5327)

src/Components/CreateImageWizard/steps/Firewall/components/PortsInput.tsx, src/Components/CreateImageWizard/steps/Firewall/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx
This adds chipping input for ports on the Firewall step.
JIRA: [HMS-5332](https://issues.redhat.com/browse/HMS-5332)
=> Wizard: Firewall ports input (HMS-5332)

Makefile, cockpit/webpack.config.ts, package-lock.json, package.json, src/Components/Blueprints/BlueprintsPagination.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/ImagesTable/ImagesTableToolbar.tsx, src/Components/ImagesTable/Instance.tsx, src/store/backendApi.ts, src/store/cockpitApi.ts, src/store/enhancedCockpitApi.ts, src/store/enhancedImageBuilderApi.ts, src/test/mocks/cockpit/index.ts
Subject says it all, this PR adds the ability to delete blueprints using the on-prem version of the frontend.
JIRA: [HMS-5224](https://issues.redhat.com/browse/HMS-5224)
=> on-prem: add ability to delete blueprints (HMS-5224)

src/store/cockpitApi.ts
This PR adds pagination support for on-prem blueprints and fixes the filtering of blueprints
when trying to search for blueprints.
JIRA: [HMS-5306](https://issues.redhat.com/browse/HMS-5306)
=> on-prem add blueprint pagination and fix filtering (HMS-5306)

.eslintrc.yml
This adds "no-unnecessary-condition" and sets the output to error. This should help us eliminate superfluous conditional chaining and uncover potentially faulty conditions.
Docs: https://typescript-eslint.io/rules/no-unnecessary-condition/
=> ESLint: Set "no-unnecessary-condition" rule to error

src/Components/CreateImageWizard/utilities/requestMapper.ts
This updates format of the snapshot date when the blueprint with the old format gets edited.
JIRA: [HMS-5283](https://issues.redhat.com/browse/HMS-5283)
=> Wizard: Parse old snapshot dates when editing (HMS-5283)

src/Components/CreateImageWizard/validators.ts
This removes checks for an `undefined` value in validators that take only `string`.
JIRA: [HMS-5354](https://issues.redhat.com/browse/HMS-5354)
=> validators: Remove undefined where only string value expected (HMS-5354)

.github/workflows/create-tag.yml, .github/workflows/release.yml
- add create-tag / release workflows
- generate and upload release artefacts, packit needs it for downstream releases.
=> Cockpit release improvements

src/Components/LandingPage/NewAlert.tsx
We'll be switching NewAlert with blueprints for information about newly available customizations. The component itself is a nice scaffolding for the upcoming announcement, would prefer to keep it for now.
Fixes #2550.
JIRA: [HMS-5295](https://issues.redhat.com/browse/HMS-5295)
=> LandingPage: Hide NewAlert (HMS-5295)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelName.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx
This adds a kernel name input.
JIRA: [HMS-5204](https://issues.redhat.com/browse/HMS-5204)
=> Wizard: Add Kernel name input (HMS-5204)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
this commit add validation to name field in Users step
JIRA: [HMS-5285](https://issues.redhat.com/browse/HMS-5285)
=> wizard: add user name validation (HMS-5285)

src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/EditDropdown.tsx
Fixes #2778
The "Create / Save changes to a blueprint and build images" buttons were disabled by default.
The button should be enabled any time the main button is enabled.
JIRA: [HMS-5366](https://issues.redhat.com/browse/HMS-5366)
=> Wizard: Fix "and build images" buttons (HMS-5366)

src/Components/CreateImageWizard/ChippingInput.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
This updates `<ChippingInput>` component to resolve two bugs:
- validation wasn't triggered when using the plus button on Timezone and Locale steps
- error text wasn't reset when the value was changed or cleared
JIRA: [HMS-5329](https://issues.redhat.com/browse/HMS-5329)
=> Wizard: Reset error text and validate on plus button (HMS-5329)

.eslintrc.yml, package-lock.json, package.json
This disables autofix specifically for the "no-unnecessary-condition" rule. This allows us to continue using autofix without applying the breaking changes.
JIRA: [HMS-5374](https://issues.redhat.com/browse/HMS-5374)
=> ESLint: Disable autofix for "no-unnecessary-condition" (HMS-5374)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Services/index.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx, src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx, src/test/setup.ts
This adds basic structure of the Services step.
JIRA: [HMS-5372](https://issues.redhat.com/browse/HMS-5372)
=> Wizard: Services step basics (HMS-5372)

src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
this commit add validation to ssh key field
JIRA: HMS-5349
=> wizrad: add validation to ssh key field (HMS-5349)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx, src/Components/CreateImageWizard/steps/Hostname/components/HostnameInput.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Aws/index.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/index.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Gcp/index.tsx, src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
this commit add support of TextArea for ssh_key field
JIRA: [HMS-5304](https://issues.redhat.com/browse/HMS-5304)
=> wizard: add support of TextArea for ssh_key field (HMS-5304)

src/Components/Blueprints/BlueprintActionsMenu.tsx, src/Components/Blueprints/BlueprintsPagination.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/Blueprints/BuildImagesButton.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/ImagesTableToolbar.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/ImagesTable/Status.tsx, src/Components/ImagesTable/Target.tsx, src/Components/LandingPage/LandingPage.tsx, src/Utilities/useDebounce.tsx, src/test/fixtures/packages.ts
Rebased on https://github.com/osbuild/image-builder-frontend/pull/2755
This is a first batch of "no-unnecessary-condition" issue fixes.
JIRA: [HMS-5355](https://issues.redhat.com/browse/HMS-5355)
=> src: Fix "no-unnecessary-condition" issues (HMS-5355)

src/Components/CreateImageWizard/ChippingInput.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelArguments.tsx, src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Oscap/OscapProfileInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx, src/test/fixtures/oscap.ts
This adds the kernel append input, removes kernel append from the OpenSCAP step and adds basic tests to cover the functionality.
TO DO:
JIRA: [HMS-5299](https://issues.redhat.com/browse/HMS-5299)
=> Wizard: Add kernel append input (HMS-5299)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
this commit create new component with eyeIcon button inside textInput,
for password field
JIRA: [HMS-5289](https://issues.redhat.com/browse/HMS-5289)
=> wizard: create new component with eyeIcon button inside textInput (HMS-5289)

src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/store/backendApi.ts, src/store/cockpitApi.ts
This PR makes it possible to step through each step of the `CreateImageWizard` and make the wizard functional.
It is a follow up to #2735. The actual blueprint creation will be done in a follow up PR.
JIRA: [HMS-5408](https://issues.redhat.com/browse/HMS-5408)
=> cockpit: make `CreateImageWizard` functional (HMS-5408)

package.json
This PR adds `start:federated` script for running image-builder-frontend as a static federated module.
=> scripts: add start:federated script

src/Components/CreateImageWizard/steps/Firewall/components/PortsInput.tsx, src/Components/CreateImageWizard/steps/Firewall/components/Services.tsx, src/Components/CreateImageWizard/steps/Firewall/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx
This adds firewall services, using the `<ChippingInput>` components. New tests were also added.
JIRA: [HMS-5353](https://issues.redhat.com/browse/HMS-5353)
=> Wizard: Add firewall services (HMS-5353)

src/Components/Blueprints/BuildImagesButton.tsx, src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx, src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/ImagesTable/Status.tsx, src/constants.ts, src/store/backendApi.ts, src/store/cockpitApi.ts, src/store/emptyCockpitApi.ts, src/store/enhancedCockpitApi.ts, src/test/mocks/cockpit/fsinfo.ts, src/test/mocks/cockpit/index.ts
https://github.com/user-attachments/assets/e2d116fb-7250-44ad-8b4b-f231a51f7c3f
JIRA: [HMS-5417](https://issues.redhat.com/browse/HMS-5417)
=> Build images with cockpit (HMS-5417)

src/store/cockpitApi.ts
Pass `-p` when creating blueprint directories in case `~/.cache/cockpit-image-builder` doesn't exist yet.
JIRA: [HMS-5419](https://issues.redhat.com/browse/HMS-5419)
=> store/cockpitApi: make cache dir in case it doesn't exist (HMS-5419)

cockpit/cockpit-image-builder.spec, src/Components/ImagesTable/Instance.tsx, src/test/mocks/cockpit/index.ts
https://github.com/user-attachments/assets/45e22797-11f7-495d-85fb-9b247d21c8e1
JIRA: [HMS-5422](https://issues.redhat.com/browse/HMS-5422)
=> Use cockpit-files for local targets (HMS-5422)

.github/workflows/release.yml, cockpit/cockpit-image-builder.spec
The release event isn't present when a tag is pushed, so use ref_name to
get the tag name.
=> .github/workflows/release: fix release workflow 2     

.github/workflows/release.yml, cockpit/cockpit-image-builder.spec
The osbuild release action cleans the repository, removing the tarball
that gets uploaded to the release. This tarball needs to be built before
schutzbot commits the version bump, so move it so it doesn't get
cleaned.
=> .github/workflows/release: work around git clean

src/store/cockpit/baseQuery.ts, src/store/cockpit/types.ts, src/store/cockpitApi.ts, src/store/emptyCockpitApi.ts, src/test/mocks/cockpit/index.ts
Add a `cockpitBaseQuery` for api calls that need to be made against the `cloudapi` on the osbuild-composer unix-socket. This function adds an extra step of parsing the result and transforming it into JSON.
There are currently no calls being made to the socket just yet, but we will need this going forward.
JIRA: [HMS-5361](https://issues.redhat.com/browse/HMS-5361)
=> store:/cockpitApi: add cockpitBaseQuery (HMS-5361)

src/store/cockpit/baseQuery.ts
Only invoke the cockpit library when actually contacting the cloudapi.
The cockpit library isn't defined in the service, so any invocation of the cockpit library when the application loads will make the frontend crash.
=> store/cockpit: don't use top-level constants that use cockpit

src/Components/ImagesTable/Instance.tsx
To ensure the local file target is copyable and usable in `cockpit-files`, the artefact directory needs to be readable.
=> ImagesTable: ensure local target is copyable

packit.yaml
Currently the version in fedora is `v55`, which is wrong, it should just be `55`.
=> packit.yaml: fix upstream tag template

src/Components/CreateImageWizard/ChippingInput.tsx, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Firewall/components/PortsInput.tsx, src/Components/CreateImageWizard/steps/Firewall/components/Services.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelArguments.tsx, src/Components/CreateImageWizard/steps/Timezone/components/NtpServersInput.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
This adds step validation to ChippingInput, allowing to validate imported values.
JIRA: [HMS-5446](https://issues.redhat.com/browse/HMS-5446)
=> Wizard: Add validation to ChippingInput (HMS-5446)

fec.config.js
this commmit enable useFileHash in fec.config.js - when set it to true Webpack will append a hash (a unique identifier) to the filename based on its content. This helps prevent the browser from using an outdated cached version of a file when its content has changed.
=> fec: enable useFileHash

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/wizardSlice.ts
this commit remove confirmPassword from Mapper because we decide that this field is not relevant anymore to Users step, and it should remove from the mapper as well
=> Wizard: remove confirmPassword from Mapper

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Services/components/ServicesInputs.tsx, src/Components/CreateImageWizard/steps/Services/index.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
This adds inputs for disabled and enabled systemd services. New tests are also added.
JIRA: [HMS-5403](https://issues.redhat.com/browse/HMS-5403)
=> Wizard: Add inputs for disabled and enabled services (HMS-5403)

src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
This adds services to on-prem mapper.
JIRA: [HMS-5405](https://issues.redhat.com/browse/HMS-5405)
=> Wizard: Add services to on-prem mapper (HMS-5405)

src/AppCockpit.tsx, src/Components/Cockpit/NotReady.tsx, src/Utilities/useComposerStatus.tsx
- Add a hook to check the status of `osbuild-composer.socket`
- Add a button to start/enable the socket
- Add a secondary button to jump to the unit file in the cockpit systemd services for `osbuild-composer.socket` if the unit is disabled/not active
https://github.com/user-attachments/assets/9c225ea7-922c-47fb-a03a-4be22786c3b9
JIRA: [HMS-5455](https://issues.redhat.com/browse/HMS-5455)
=> Composer service (HMS-5455)

src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizard/validators.ts, src/Utilities/useGetEnvironment.ts, src/store/backendApi.ts, src/store/cockpit/cockpitApi.ts, src/store/cockpit/enhancedCockpitApi.ts, src/store/wizardSlice.ts
Adds all the new customizations, and implements updating blueprints.
---
https://github.com/user-attachments/assets/9938233a-e0d2-46de-bbe9-da0047737d05
JIRA: [HMS-5459](https://issues.redhat.com/browse/HMS-5459)
=> cockpit plugin: enable all customizations and implement updating blueprints (HMS-5459)

src/Components/CreateImageWizard/utilities/requestMapper.ts
Regex was wrong, would take "2025-01-01T00:00:00.000Z" even though it's a valid RFC 3339 date.
JIRA: [HMS-5463](https://issues.redhat.com/browse/HMS-5463)
=> requestMapper: Fix snapshot date parsing (HMS-5463)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/LandingPage/LandingPage.tsx
Fixes #2372
This ensures that both Landing page and Wizard are aligned to center within wide windows.
Before:
After:
JIRA: [HMS-5452](https://issues.redhat.com/browse/HMS-5452)
=> src: Align to center (HMS-5452)

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
This adds systemd services expandable to the Review step.
JIRA: [HMS-5404](https://issues.redhat.com/browse/HMS-5404)
=> Wizard: Add services to Review step (HMS-5404)

.github/workflows/release.yml
After the upstream tag template changed, packit is now looking for the artefact matching the template, so without the "v".
=> .github/workflows/release: fix artefact name

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
this removes extendable users from Review step when there is no user or kernel name
FIX ISSUE: (https://github.com/osbuild/image-builder-frontend/issues/2718)
JIRA: [HMS-5474](https://issues.redhat.com/browse/HMS-5474)
=> Wizard: remove extendable users from Review step when there is no user or kernel name (HMS-5474)

package.json, src/Utilities/useGetEnvironment.ts, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx, src/test/cockpit-tests.sh, src/test/mocks/cockpit/cockpitFile.ts, src/test/mocks/cockpit/index.ts, src/test/mocks/os-release/index.ts
Needed some mocks and minor tweaks, overall not too drastic of a change.
=> test: test hostname step on cockpit

.github/workflows/release.yml, cockpit/cockpit-image-builder.spec
With #2862  moving the artefact out of the checkout dir got reverted.
Adds an obsoletes for cockpit-composer.
=> cockpit/spec: add obsoletes & fix release workflow

src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/ImagesTable/ImagesTable.test.tsx, vitest.config.ts
This sets retry globally to `3`, so we don't have to add it to the tests individually.
For the tests that are reliable this shouldn't have any effect, but it will trigger on tests that proved to be a bit flakey (like revisit tests).
JIRA: [HMS-5458](https://issues.redhat.com/browse/HMS-5458)
=> vitests: Set global retry (HMS-5458)

src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
Fixes #2834
Render "None" just as a plain text when there are no values to be shown in the review expandable.
JIRA: [HMS-5454](https://issues.redhat.com/browse/HMS-5454)
=> Wizard: Remove `CodeBlocks` for "None" as a value (HMS-5454)

.github/dependabot.yml
This will temporarily increase limit of opened pull requests, until the frontend-components bumps get resolved.
=> dependabot: Increase limit of opened pull requests

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx
Fixes #2700
Status icon rendered only when the step was previously visited, this caused problems with imported blueprints.
How to reproduce a bug:
1. import a blueprint with invalid hostname
2. skip to Review
Current behaviour:
- the Create blueprint button is disabled, but there is no indication of error next to the Hostname step in navigation
After fix:
- the error status should be rendered next to the Hostname nav item
JIRA: [HMS-5489](https://issues.redhat.com/browse/HMS-5489)
=> Wizard: Fix nav status icon (HMS-5489)

src/Components/CreateImageWizard/CreateImageWizard.scss
The original solution that broke some time ago works again. Removing the comments and temporary workaround.
JIRA: [HMS-5506](https://issues.redhat.com/browse/HMS-5506)
=> Wizard: Sticky footer returns (HMS-5506)

src/Components/CreateImageWizard/CreateImageWizard.scss
Reverts osbuild/image-builder-frontend#2895
My bad, I forgot that besides the footer not being sticky anymore this happened when the window got resized ;_;
=> Revert "Wizard: Sticky footer returns (HMS-5506)"

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
This sets registration type to `register-later` when a non-RHEL distribution is selected.
The bug was caught on Reddit: https://www.reddit.com/r/redhat/comments/1ir6cpd/error_when_building_centos_image_on_redhat_build/
JIRA: [HMS-5515](https://issues.redhat.com/browse/HMS-5515)
=> Wizard: `register-later` for non-RHEL images (HMS-5515)

src/Components/Blueprints/ImportBlueprintModal.tsx
This increases limit for the maximum size of a blueprint.
JIRA: [HMS-5519](https://issues.redhat.com/browse/HMS-5519)
=> ImportModal: Increase `maxSize` (HMS-5519)

src/Components/CreateImageWizard/CreateImageWizard.scss
This removes css styles for `DualListSelector` we no longer use and a temporary pagination fix that was already addressed directly in PF.
=> Wizard: Remove obsolete css

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
this fix an issue when user search for a package, the viewv stay "Selected" instead of switching to "Available
FIX ISSUE: (https://github.com/osbuild/image-builder-frontend/issues/2864)
JIRA: [HMS-5480](https://issues.redhat.com/browse/HMS-5480)
=> Wizard: Switch view to "Available" when searching for package (HMS-5480)

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
There is a bug that makes `custom-first-boot` service stay in services when the first boot script is removed.
How to reproduce:
1. create a blueprint with a first boot script
2. download the blueprint and confirm `custom-first-boot` was added to enabled services
3. click on "Edit blueprint"
4. go to First boot step and remove the script
5. save edited blueprint
Current behaviour:
- `custom-first-boot` service should be still enabled even with the removed first boot script
Updated behaviour:
- `custom-first-boot` is no longer in the blueprint after first boot script got removed
JIRA: [HMS-5481](https://issues.redhat.com/browse/HMS-5481)
=> Wizard: Remove first boot script from services when no script (HMS-5481)

src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
Fixes #2911
The target environments in the review step of the wizard have bigger spacing.
JIRA: [HMS-5563](https://issues.redhat.com/browse/HMS-5563)
=> Wizard: target environments spacing (HMS-5563)

src/Components/CreateImageWizard/ChippingInput.tsx, src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/ShareImageModal/RegionsSelect.tsx, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
`Chip` and `ChipGroup` components will be deprecated in PF6. This replaces them with recommended `Label` and `LabelGroup`.
=> Wizard: Deprecate `Chip` and `ChipGroup` components

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Utilities/useGetEnvironment.ts, src/test/Components/CreateImageWizard/steps/Oscap/Compliance.test.tsx, src/test/setup.ts
This removes `image-builder.timezone.enabled` and `image-builder.locale.enabled` gating as both were released to production.
JIRA: [HMS-5581](https://issues.redhat.com/browse/HMS-5581)
=> src: Remove timezone and locale unleash flags (HMS-5581)

package-lock.json, package.json, src/Components/edge/ImageDetails.tsx, src/Components/edge/ImagesTable.tsx
This bumps @redhat-cloud-services/frontend-components from 4.2.22 to 5.2.6 and updated `<AsyncComponent>` props. `appName` is no longer supported.
JIRA: [HMS-5495](https://issues.redhat.com/browse/HMS-5495)
=> deps: Bump @redhat-cloud-services/frontend-components from 4.2.22 to 5.2.6 (HMS-5495)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
This commit splits the HookValidatedInput component into three separate functions to improve modularity and readability:
- `getValidationState`: Calculates the validation state ('default', 'success', 'error') based on whether the input is pristine and if there is an error message.
- `ValidatedInputAndTextArea`: Renders the TextInput or TextArea component, utilizing the `getValidationState` output.
- `ErrorMessage`: Displays validation error messages.
This refactoring enhances code maintainability and testability, and the updated structure is now implemented for the username field.
=> Wizard: refactor HookValidatedInput component

src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx
This adds the timezones to the step validation and renders an error when an invalid timezone is imported.
How to test:
1. import a blueprint with invalid timezone "foo"
2. select a target
3. go to Registration step
4. click on "Review and finish" button
Current behaviour:
- the "Create" button is disabled, but when navigating to Timezone step no error is displayed
After update:
- there is an error rendered under the timezone select
JIRA: [HMS-5493](https://issues.redhat.com/browse/HMS-5493)
=> Wizard: Add validation to Timezone select (HMS-5493)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
Modify the logic of removing a package so that it remains in the selected table for possible re-addition until another package is removed or the wizard is switched to another screen.
FIX ISSUE: https://github.com/osbuild/image-builder-frontend/issues/2924
=> Wizard: Current unselected package fix

src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
Fixed #2960
The Select dropdown in Registration wizard step no longer shows activation key when user decides to register later.
JIRA: [HMS-5631](https://issues.redhat.com/browse/HMS-5631)
=> Blueprints: hiding unused activation key in when editing Blueprint (HMS-5631)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/steps/Hostname/components/HostnameInput.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx
This commit Implement refactor of HookValidatedInput for hostname and blueprint name
fields, addressing the following bugs:
1) Fixes a bug where the validation symbol persisted after a user deleted the value in the hostname field.
2) Fixes a bug where the validation symbol persisted after a user deleted the value in the blueprint name field.
These changes improve code maintainability and provide a more consistent user experience.
FIX ISSUE: [2917](https://github.com/osbuild/image-builder-frontend/issues/2917), https://github.com/osbuild/image-builder-frontend/issues/2971
JIRA: [HMS-5616](https://issues.redhat.com/browse/HMS-5616)
=> Wizard: Refactor hostname and blueprint name inputs (HMS-5616)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Details/index.tsx
This adds `data-testid` back to the blueprint name input.
JIRA: [HMS-5632](https://issues.redhat.com/browse/HMS-5632)
=> Wizard: Return of the testid (HMS-5632)

src/Components/CreateImageWizard/steps/FirstBoot/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts
I noticed there is a bug that does not show a relevant list of services that we create on user's behalf.
How to reproduce:
1. start creating a blueprint with a first boot script
2. go to the review step - the custom-first-boot service is not displayed there, but we are adding it on user's behalf
3. click on "Edit blueprint"
4. go to First boot step and remove the script
5. go to the review step - the custom-first-boot service is displayed there, but we will remove it after clicking "edit"
Overall, I thought that the code in requestMapper was a bit unclear, and I needed to do something similar for the Satellite follow-up, so I was digging deeper, and found a small bug.
Let me know what you think. I tried to prevent the code from removing/adding service in case we just edit an existing …
=> Wizard: add/rm firstboot service based on state

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/fixtures/packages.ts
This removes the "Too many results" state that was rendered when a search term returned more than 100 results.
=> Wizard: Remove "Too many results" state

src/Components/CreateImageWizard/steps/Locale/components/KeyboardDropDown.tsx, src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx, src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
The "No results found for <searchTerm>" options were previously enabled, but ignored upon click. This disables them properly and adds tests to check if they're disabled.
Before:
After:
JIRA: [HMS-5641](https://issues.redhat.com/browse/HMS-5641)
=> Wizard: Disable "No results found" options (HMS-5641)

.github/workflows/sentry.yml, fec.config.js
This adds image-builder to new sentry flow.
=> feat(RHINENG-15883): Add image-builder to new sentry flow

.github/dependabot.yml
Since the container embedded in our CI images is pinned, any update here
would result in the container having to be pulled again in CI
runs. Let's reduce the frequency that playwright gets updated, making it
easier to keep the container and the dependencies here somewhat in sync.
=> dependabot: ignore playwright dependency

src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
This commit refactors the SSH key field by replacing `HookValidatedInput` with the new `ValidatedInputAndTextArea` component. It also fixes a bug where the validation icon remained visible after the user cleared the `SSH key` field.
JIRA: [HMS-5637](https://issues.redhat.com/browse/HMS-5637)
=> Wizard: Refactor SSH key input using ValidatedInputAndTextArea component (HMS-5637)

src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
This commit refactors the Description field by replacing HookValidatedInput with the new ValidatedInputAndTextArea component.
It fixes a bug where the validation icon remained visible after the user cleared the Description field.
JIRA: [HMS-5649](https://issues.redhat.com/browse/HMS-5649)
=> Wizard: Refactor Description input using new component (HMS-5649)

.gitmodules, .tekton/image-builder-frontend-pull-request.yaml, .tekton/image-builder-frontend-push.yaml
This migrates frontend to use shared Dockerfile to comply with Konflux migrations requirements.
A submodule `build-tools` was added, obsolete tasks `create-frontend-dockerfile` and `parse-build-deploy-script` were removed and the path to the Dockerfile was updated.
=> Migrate to shared Dockerfile (HMS-5539)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelName.tsx, src/Components/CreateImageWizard/steps/Locale/components/KeyboardDropDown.tsx, src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx, src/Components/LandingPage/LandingPage.tsx, src/Components/ShareImageModal/RegionsSelect.tsx
This removes `isWidthLimited` prop from Page component in Wizard and ImagesTable.
JIRA: [HMS-5657](https://issues.redhat.com/browse/HMS-5657)
Before:
After:
=> src: Remove width limiting for Wizard and ImagesTable (HMS-5657)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx, src/Components/CreateImageWizard/utilities/PasswordValidatedInput.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
This commit adds password validation to the User step:
- Moved password validation logic to a separate `checkPasswordValidity` function, returning detailed results (strength and validation state).
- Simplified validation in `PasswordValidatedInput` by using `checkPasswordValidity` results directly.
- Added dynamic password strength indicator showing success or error based on requirements.
- Integrated environment-specific validation messages (e.g., for Azure).
- Improved code separation between presentation and validation for better maintainability.
- Unit tests: Adds tests for invalid passwords, covering both default and Azure cases.
use this Password strength - https://www.patternfly.org/components/password-strength/ as insperation 
JIRA: …
=> Wizard: Add validation to user's password in User step (HMS-5466)

src/Components/CreateImageWizard/utilities/useValidation.tsx
Currently, we only want to display the "Strong" label when the password meets the required strength conditions and only if it is Azure target. This change ensures that the label remains hidden for non-Azure cases.
Let’s just disable it for now until we can decide on further adjustments.
JIRA: [HMS-5674](https://issues.redhat.com/browse/HMS-5674)
=> Wizard: Show "Strong" label only for Azure when password meets criteria (HMS-5674)

src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
If a user skips too quickly to the Review step in Wizard, the step rerenders with the newly created activation key, and the "Create blueprint" button stays disabled until the activation key loads. 
JIRA: [HMS-5651](https://issues.redhat.com/browse/HMS-5651)
=> Race condition activation key (HMS-5651)

.gitignore, README.md, playwright.config.ts, playwright/lib/lib.ts, playwright_example.env, schutzbot/playwright_tests.sh
Streamline the process of setting up Playwright for local development of hosted service tests using dotenv. Add short guide to README as well.
JIRA: [HMS-5791](https://issues.redhat.com/browse/HMS-5791)
=> tests: Streamline hosted Playwright local setup (HMS-5791)

codecov.yml
API, PW and  store folders contain mostly files that are copied, auto-generated or test files. We don't need to collect coverage for those.
There were previously errors in expected values, this should fix them.
JIRA: [HMS-5792](https://issues.redhat.com/browse/HMS-5792)
=> codecov: Ignore API, PW and store folders and update config (HMS-5792)

tsconfig.json
After running `make cockpit/devel`, the generated files do not pass `npm run build`, outputing failures and making dev console and output of `npm run build` cluttered with errors.
This excludes `/pkg` folder during build time, removing the errors.
=> tsconfig: Exclude `/pkg` folder during build

tsconfig.json
Reverts osbuild/image-builder-frontend#3045
The directory needs to be excluded on webpack level. This causes a loop in webpack upon running `npm run start:stage`
=> Revert "tsconfig: Exclude `/pkg` folder during build"

fec.config.js
After running `make cockpit/devel`, the generated files do not pass `npm run build`, outputing failures and making dev console and output of `npm run build` cluttered with errors.
This excludes `/pkg` folder during build time, removing the errors.
=> fec.config: Exclude `pkg` directory during build time

package-lock.json, package.json
This bumps:
- vitest from 3.0.5 to 3.0.9
- @vitest/coverage-v8 from 3.0.5 to 3.0.9
The reason for not being able to bump in a dependabot PR is that the dependencies need to bumped together.
=> devDeps: Manually bump vitest and @vitest/coverage-v8

src/store/wizardSlice.ts
This adds a check for existing/non-existing item before splicing an array.
Based on https://github.com/osbuild/image-builder-frontend/pull/3029#discussion_r2011489983
> There's a potential issue with the group removal logic. When findIndex() doesn't find the group, it returns -1, which would cause splice(-1, 1) to remove the last element in the array rather than doing nothing. 
JIRA: [HMS-5793](https://issues.redhat.com/browse/HMS-5793)
=> store: Safeguard splicing (HMS-5793)

src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
This removes check for whether the value is defined from validators and moves it to the place the validator is called where needed.
JIRA: [HMS-5681](https://issues.redhat.com/browse/HMS-5681)
=> Wizard: Remove `if (!value)` check from validators (HMS-5681)

src/Components/CreateImageWizard/steps/Details/index.tsx, src/Components/CreateImageWizard/steps/ImageOutput/index.tsx, src/Components/CreateImageWizard/steps/Review/index.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useGenerateDefaultName.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
This commit resolves an issue where the blueprint name did not update when the user changed the Architecture or Distribution.
Additionally, it sets an initial value for blueprintName in the WizardSlice.
FIX ISSUE: https://github.com/osbuild/image-builder-frontend/issues/2929
JIRA: [HMS-5556](https://issues.redhat.com/browse/HMS-5556)
=> Wizard: Fix blueprint name update on Architecture/Distribution changes (HMS-5556)

playwright/test.spec.ts, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Oscap/OnPremSpinner.tsx, src/Components/CreateImageWizard/steps/Oscap/OnPremWarning.tsx, src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Oscap/OscapProfileInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx, src/Utilities/useOnPremOpenSCAP.tsx, src/store/backendApi.ts, src/store/cockpit/cockpitApi.ts, src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
This PR adds the following:
- enables the OpenSCAP step for on-prem
- adds a warning if the `openscap-scanner` and `scap-security-guide` packages aren't installed on the host
- this implementation runs the `oscap` tool on the host to fetch the available profiles and eventual customizations
JIRA: [HMS-5824](https://issues.redhat.com/browse/HMS-5824)
=> on-prem: add OpenSCAP customizations (HMS-5824)

src/Components/CreateImageWizard/LabelInput.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelArguments.tsx, src/Components/CreateImageWizard/steps/Services/components/ServicesInputs.tsx, src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx, src/Components/CreateImageWizard/validators.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
This adds a group input to the User step. The input is implemented as a `LabelInput`, when Administrator checkbox is checked, `wheel` group gets added and it's removal automatically unchecks the Administrator checkbox again.
Tests were also added and `LabelInput` component was updated to accept custom required category name.
JIRA: [HMS-5677](https://issues.redhat.com/browse/HMS-5677)
=> Wizard: Add group input to User step (HMS-5677)

src/Components/CreateImageWizard/CreateImageWizard.scss
- Improved the layout of the repository step in the wizard to prevent the "Next" button from being hidden behind a scroll.
- Adjusted the wizard size to ensure a better user experience without needing to scroll in the repository selection step.
- Ensured consistent button positioning across varying screen resolutions.
- Attached is a video demo showcasing how this change resolves it.
- This is my approach to solving the issue, and I'm happy to consider alternative suggestions if anyone has a different idea.
[Screencast from 2024-10-22 11-59-24.webm](https://github.com/user-attachments/assets/c93ce198-bc93-4b7a-8bc4-c87e5f9db26b)
=> Wizard: Ensure wizard footer remains visible in repo step

src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Components/CreateImageWizard/validators.ts
Prior to this commit, the wizard showed "Invalid description" when the description was too long. This was rather unhelpful for users.
The actual size check happens in validators.ts, but the functions there just return a boolean value, even if they check for multiple criteria.
I'm not entirely sure, why the validation functions live in a separate file, so I decided to move this specific condition to useValidation.tsx so the condition, and the relevant user-facing error message can be defined next to each other.
Fixes #3036
=> Wizard: show a specific error message when description validation fails

src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx
This adds a maxWidth prop to the OpenSCAP select. Previously the options overflowed on the right side of the screen.
Before:
After:
JIRA: [HMS-5845](https://issues.redhat.com/browse/HMS-5845)
=> Wizard: Fix OpenSCAP select width (HMS-5845)

api/schema/compliance.json, api/schema/composerCloudApi.v2.yaml, api/schema/contentSources.json, api/schema/imageBuilder.yaml, package-lock.json, package.json, playwright/test.spec.ts, src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/Registration/Registration.tsx, src/Components/CreateImageWizard/steps/Registration/SatelliteRegistration.tsx, src/Components/CreateImageWizard/steps/Registration/components/SatelliteRegistrationCommand.tsx, src/Components/CreateImageWizard/steps/Registration/index.tsx, src/Components/CreateImageWizard/utilities/certificates.ts, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/store/service/contentSourcesApi.ts, src/store/service/imageBuilderApi.ts, src/store/wizardSlice.ts, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx
This adds an option to paste the Satellite registration command + CA. Saving this information into the blueprint is still not done; I will create a follow-up; this is big PR as is.
=> Wizard: add satellite registration

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/Components/CreateImageWizard/steps/Snapshot/index.tsx, src/store/wizardSlice.ts, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx, src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
This renames the repository snapshot wizard step to "Reproducible builds" to emphasize the benefit to the user.
It also makes the snapshot date be auto set to the current date, and changes the 'reset' button  to do the same.
=> Wizard: rename repo snapshot step to repeatable builds HMS-5599

playwright/lib/lib.ts
The admin access popup is different for passwordless user and a user with a password.
This checks what popup got rendered and based on that acts to get administrative access.
JIRA: [HMS-5844](https://issues.redhat.com/browse/HMS-5844)
=> Playwright: Add check for admin access popup (HMS-5844)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Utilities/useGetEnvironment.ts, src/constants.ts, src/test/FedoraServices.test.tsx, src/test/setup.ts
This pull request introduces enhancements to the Image Builder Frontend service to support Fedora services. 
For more details, and a full dev setup docs, please refer to the [README file](https://github.com/FedoraConsole/community-chrome).
The key updates include:
- Support for Fedora Services:
Adds compatibility for Fedora services, by introducing `isFedoraEnv` in the existing `useGetEnvironment` hook. This new env is set by the ChromeAPI.
```js
const { isFedoraEnv } = useGetEnvironment();
```
- Keeping the hosted (consoleDot) and on premise environment isolated.
- Aligned Blueprint Wizard:
Hides irrelevant steps in the blueprint wizard when configuring Fedora and CentOS distributions, streamlining the user experience.
- Expanded Distribution Support:
Adds support for Fedora and CentOS …
=> Fedora-services: add support for fedora env

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx, src/Components/CreateImageWizard/steps/Registration/components/ManageKeysButton.tsx, src/Components/CreateImageWizard/steps/Registration/components/PopoverActivation.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
This replaces a deprecated select in `ActivationKeys` for a non-deprecated one. Some parts were also moved to separate component files.
JIRA: [HMS-5620](https://issues.redhat.com/browse/HMS-5620)
=> Wizard: Switch from deprecated select in `ActivationKeys` (HMS-5620)

src/Components/ImagesTable/Target.tsx
The AWS regions indicator that is currently baked into each row containing an AWS image is currently off by one due to incorrect parentheses in the code.
This is now fixed, so it displays '(1)' when there is one region (which is the default, us-east-1) instead of '(0)' which was both wrong and confusing.
Before:
After:
=> ImagesTable: Fix AWS regions indicator (off by one)

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This simple pull request promotes WSL images to production stable.
It also adds a Popover to reflect that this image type is currently not supported by Red Hat. The Popover and text reflect the UX mockup.
/jira-epic HMS-5949
JIRA: [HMS-5950](https://issues.redhat.com/browse/HMS-5950)
=> Promote WSL to production stable (HMS-5950)

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This updates the text and the link in the WSL popover.
JIRA: [HMS-5979](https://issues.redhat.com/browse/HMS-5979)
=> Wizard: Update WSL popover (HMS-5979)

src/Components/CreateImageWizard/CreateImageWizard.tsx
Added tracking for the "Next", "Back", "Cancel" and "Review and Finish" buttons in the Image wizard footer when creating a blueprint.
Fixes #3087
JIRA: [HMS-5977](https://issues.redhat.com/browse/HMS-5977)
=> Wizard: add segment tracking to buttons in wizard footer (HMS-5977)

src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx
resourceGroup is used in useEffect, so if assigned a new array to it every time this function is called, it would cause the useEffect to run every time, leading to an infinite loop. This is because useEffect uses Object.is to determine if the value has changed, and [] creates a new array every time. Thus, we use a constant empty array to avoid this issue.
Alternatively JSON.stringify(resourceGroups), or a deep comparison could be used as a useEffect dependency, but that feels like just a waste of resources.
Without this patch, I get this warning when running the basic test for upload to azure in `AzureTarget.test.tsx`:
```
Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one …
```
=> Wizard: fix a rerender loop in AzureResourceGroups

.eslintrc.yml, package-lock.json, package.json, playwright.config.ts, playwright/Customizations/Hostname.spec.ts, playwright/fixtures/cleanup.ts, playwright/helpers/helpers.ts, playwright/helpers/login.ts, playwright/helpers/navHelpers.ts, playwright/helpers/wizardHelpers.ts, playwright/test.spec.ts, schutzbot/playwright_tests.sh, src/Components/Blueprints/BlueprintCard.tsx
This PR introduces a refactor of the Playwright suite and adds a template for testing the customizations (demonstrated on Hostname).
- Test timeouts were changed globally to assure test results are posted in case of Codebuild timeout and they were also changed for each test and Playwright action in order to reduce flakes
- Parallelization was enabled
- New helper functions were introduced and existing ones were moved to different files
- Various missing excepts in assertions were fixed
- Cleanup fixture was added
The test template creates a BP, edits the BP, exports it, imports the exported BP back (to verify the BP format) and then the imported BP is verified in Wizard (to see if the content is correct). The cleanup fixture ensures that if any of these steps fail, the created BP is …
=> Playwright: Add customizations test template and refactor (HMS-5942)

src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizard/steps/Kernel/components/KernelName.tsx, src/Components/CreateImageWizard/steps/Locale/components/KeyboardDropDown.tsx, src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx
This fixes a bug - when clicking outside the select dropdown, the dropdown was not closed. 
Changes I made are what is used in demos of Patternfly that use the component. We were a bit inconsistent in this around our codebase.
=> Wizard: Fix Select's dropdown closing

src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/test/setup.ts
Needed so the Intercom team can decide whether or not to display an onboarding video (first time user with no images or blueprints).
Verified to be working in Segment:
=>     ImagesTable/BlueprintsSideBar: Add Segment tracking (HMS-5989)

api/schema/contentSources.json, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Packages/components/RepoPopovers.tsx, src/store/service/contentSourcesApi.ts, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
This prepares the Packages step for modularity implementation. The changes in this PR are:
- updating and re-generating API schema
- replacing previously used Included/Other repos toggle with tabs
- making the selected packages count render only when there's at least one selected package
- renaming "Package name" column to just "Name"
- removing "Description" column and moving the information to the expandable part of the row
- removing the "Support" column
mocks: https://www.figma.com/proto/ULjbLMEimzuTGu06oNySNE/Image-builder-Lightspeed?page-id=0%3A1&node-id=420-10356&viewport=-1447%2C-1737%2C0.09&t=dYK45rQxBflfZu19-1&scaling=scale-down&content-scaling=fixed&starting-point-node-id=420%3A10356
In a follow-up:
- adding Application stream column
- adding Retirement date column
- …
=> Wizard: Modularity prep (HMS-5952)

src/Components/CreateImageWizard/steps/Users/components/RemoveUserModal.tsx, src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx, src/Components/CreateImageWizard/steps/Users/components/calculateNewIndex.ts, src/Components/CreateImageWizard/utilities/PasswordValidatedInput.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
This adds support for multiple users in the Wizard. The users are rendered in tabs and can be both added and removed. When clicking on remove button, modal pops up to inform user that the changes cannot be undone.
JIRA: [HMS-5911](https://issues.redhat.com/browse/HMS-5911)
=> Wizard: Add support for multiple users (HMS-5911)

api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx, src/Components/CreateImageWizard/utilities/PasswordValidatedInput.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/service/imageBuilderApi.ts, src/store/wizardSlice.ts
This updates API schema and uses the `hasPassword` value to render a password placeholder in edit mode.
JIRA: [HMS-5951](https://issues.redhat.com/browse/HMS-5951)
=> Wizard: Password placeholder (HMS-5951)

src/test/setup.ts
The WSL flag was removed from the codebase, this removes it from the test mock as well.
JIRA: [HMS-6002](https://issues.redhat.com/browse/HMS-6002)
=> test: Remove WSL flag from unleash test mock (HMS-6002)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx
Currently, when a search term is entered and then reduced to a single character in the Wizard's packages step, the previous results are still shown.
What is expected is that the empty state hinting at the search term being too short would be shown.
The condition in bodyContent was wrong, because it assumed that the list of results would be 0 when in fact it wasn't being cleared.
Fixes #3139
=> Wizard: Fix 'too short' state in Packages step

api/config/contentSources.ts, api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizard/steps/Repositories/components/Empty.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTables.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/Components/CreateImageWizard/steps/Snapshot/components/Templates.tsx, src/Components/CreateImageWizard/steps/Snapshot/components/TemplatesEmpty.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/Utilities/useGetEnvironment.ts, src/constants.ts, src/store/contentSourcesApi.ts, src/store/service/contentSourcesApi.ts, src/store/service/imageBuilderApi.ts, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx, src/test/fixtures/templates.ts, src/test/mocks/handlers.js, src/test/setup.ts
Jira: https://issues.redhat.com/browse/HMS-5320
---
- Adds support for selecting a content template when creating an image
1. Create a few templates in the Templates UI, some with and some without additional non-RH repositories and of various versions and architectures. 
2. Select `Use a content template` on the snapshot step of the wizard. The correct templates (filtered by arch and OS version) should be shown in the table
3. On the repositories step, only the repositories in the template should be shown, and should be selected and read-only
4. Blueprint and image should be created successfully on submit
5. Feature flag exists to control this behavior in stage/prod
=> Wizard: add support for content templates

playwright/test.spec.ts, src/Components/CreateImageWizard/steps/Packages/Packages.tsx
As a small simplification and also to make the UX more consistent, let's use a SearchInput widget over the custom InputGroup structure. This means the search boxes will also be consistent between the repository and package search pages.
Fixes #3133
JIRA: [HMS-6011](https://issues.redhat.com/browse/HMS-6011)
=> Wizard: Use SearchInput component for packages (HMS-6011)

src/Components/Blueprints/BlueprintActionsMenu.tsx, src/Components/Blueprints/BlueprintCard.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/Blueprints/BuildImagesButton.tsx, src/Components/Blueprints/EditBlueprintButton.tsx, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/ValidatedInput.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemConfiguration.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemPartition.tsx, src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx, src/Components/CreateImageWizard/steps/ImageOutput/ArchSelect.tsx, src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx, src/Components/CreateImageWizard/steps/Oscap/components/OnPremWarning.tsx, src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureHyperVSelect.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx, src/Components/CreateImageWizard/steps/Users/components/RemoveUserModal.tsx, src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/ImagesTableToolbar.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
Since we're moving away from IQE the `ouia-id` atributes should be no longer needed. This removes them from the entire code base.
JIRA: [HMS-6012](https://issues.redhat.com/browse/HMS-6012)
=> src: Remove `ouia-id`s (HMS-6012)

package-lock.json, package.json
This bumps `vitest` and `@vitest/coverage-v8` from 3.1.1 to 3.1.2
=> devDeps: Bump `vitest` and `@vitest/coverage-v8`

playwright.config.ts
This increases timeout for `expect` from 30s to 50s.
=> playwright: Increase timeout for `expect`

playwright/Customizations/Locale.spec.ts
Adds a Locale customization test that creates a BP, edits BP, exports and imports it back and verifies the BP content.
=> tests/playwright: Add Locale customization test (HMS-4590)

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
Changed the naming of analytics track calls to stay consistent in the analytics tracking names of other instances
=> Wizard: edit naming of analytics traces for consistency

api/config/imageBuilder.ts, api/schema/imageBuilder.yaml, src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx, src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx, src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx, src/store/service/imageBuilderApi.ts, src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx, src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Compliance.test.tsx, src/test/fixtures/editMode.ts, src/test/fixtures/oscap.ts, src/test/mocks/handlers.js
This splits the policy and profile selectors as they're drifting apart.
Instead of querying the customizations attached to the profile, query
the customizations attached to the policy, as these take into account
tailoring. As a result unnecessary customizations won't be added.
=> Wizard: support tailored customizations

playwright/Customizations/Timezone.spec.ts
Adds a Timezone customization test that creates a BP, edits BP, exports and imports it back and verifies the BP content.
Let's see if there are the same error as we have #3126 3126
=> tests/playwright: Add Timezone customization test

package-lock.json, package.json, src/mockServiceWorker.js
This bumps msw from 2.7.3 to 2.7.5, the manual bump is needed, because dependabot doesn't want to touch `mockServiceWorker.js`. But the file gets updated when running `npm i`.
=> devDeps: Manually bump msw

api/schema/contentSources.json, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/store/service/contentSourcesApi.ts
This adds retirement date column to the Packages table and populates it with `end_date` from content-services `searchRPMs` endpoint.
JIRA: [HMS-6015](https://issues.redhat.com/browse/HMS-6015)
=> Wizard: MODULARITY 2 - Add retirement date column (HMS-6015)

.github/workflows/playwright.yml, playwright.config.ts
This PR should decrease the flakiness in parallelization in Playwright tests by providing a larger AWS codebuild instance.
=> playwright: Use better AWS Codebuild runner (HMS-6025)

src/store/wizardSlice.ts
If 'wheel' group was removed the Administrator checkbox stayed check. This unchecks it.
=> Wizard: Fix users bug - 'wheel' group removal

src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx
When resolving conflicts, the `style: 200px` prop sneaked past me and stayed in the code. It's time to let it rest. 🪦
=> Wizard: make policy selector wider in Compliance step

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/fixtures/packages.ts
This implements basic sorting for the following columns of packages table:
- name
- application stream
- retirement date
Conditional sorting upon stream selection will be split into a separate PR.
=> Wizard: MODULARITY 1 - Implement packages table sorting (HMS-6014)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
Rebased on: https://github.com/osbuild/image-builder-frontend/pull/3178
This updates the sort logic to reflect currently selected application stream. For example if `nodejs` with application stream 22 gets selected, results for other modules with the same application stream should be prioritized before the rest of results.
=> Wizard: MODULARITY 2 - Update sorting to reflect currently selected stream (HMS-6014)

playwright/helpers/login.ts, src/AppCockpit.tsx, src/Components/Cockpit/NotReady.tsx, src/Components/Cockpit/RequireAdmin.tsx, src/Components/Cockpit/index.tsx, src/Utilities/useIsCockpitAdmin.tsx, src/test/mocks/cockpit/cockpitPermission.ts, src/test/mocks/cockpit/index.ts
The on-prem frontend needs administrative access in order to run correctly. Show a an empty state dialog that reflects this if the user is logged in with limited access.
JIRA: [HMS-6044](https://issues.redhat.com/browse/HMS-6044)
=> on-prem: check user permissions (HMS-6044)

src/Components/ImagesTable/Instance.tsx
This adds `imageBuilder - Image Downloaded` tracking event to track target, blueprint id and blueprint version for downloaded images.
JIRA: [HMS-6144](https://issues.redhat.com/browse/HMS-6144)
=> ImagesTable: Add tracking to image downloads (HMS-6144)

src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts
This fixes a bug that was caused by using incorrect ids of imported custom repositories. Due to that bug, only in some cases the repositories were correctly preselected.
Now what works is importing both existing and non-existing custom repositories.
<details>
<summary>Json blueprint with two custom repositories for testing</summary>
```json
{
"content_sources": [
{
"distribution_arch": "x86_64",
"distribution_versions": [
"9"
],
"gpg_key": "",
"metadata_verification": false,
"module_hotfixes": false,
"name": "Centos 9",
"origin": "external",
"snapshot": true,
"url": "https://nginx.org/packages/centos/9/x86_64/"
},
{
"distribution_arch": "x86_64",
"distribution_versions": [
"any"
],
"gpg_key": "",
"metadata_verification": false,
"module_hotfixes": false,
"name": "Fedora 40",
"origin": …
```
=> Wizard: fix imported repositories not preselected (HMS-6013)

src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
We've been refetching the data, but not re-rendering the list. This should fix the issue.
JIRA: [HMS-6294](https://issues.redhat.com/browse/HMS-6294)
=> Wizard: Fix activation keys list refresh (HMS-6294)

src/Components/CreateImageWizard/utilities/PasswordValidatedInput.tsx
User password gets redacted from a blueprint, meaning if there was any password set, it does not render on import.
Previously a placeholder was rendered as a value of password, making the value not editable. This renders the password indication as a placeholder text, solving the issue.
JIRA: [HMS-6290](https://issues.redhat.com/browse/HMS-6290)
=> Wizard: Fix password placeholder (HMS-6290)

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/constants.ts
I know nothing about the modern JS/TS, review with care. Problems:
* The file /usr/local/sbin/register-satellite is not executable.
* The file does not have a shebang.
* The file contents is for some reason all URL encoded.
* Finally, the file is missing an end newline.
/epic https://issues.redhat.com/browse/HMS-6296
=> Wizard: encode satellite cmd properly

src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
The error for invalid user groups was not previously rendered on import. This fixes the issue and adds an import test to check that the error messages for all user fields get correctly rendered.
=> src: Fix user groups validation on import (HMS-6279)

src/Components/CreateImageWizard/CreateImageWizard.scss, src/Components/CreateImageWizard/CreateImageWizard.tsx
Recently the wizard has started rendering such that its vertical height matches the height of its body – and therefore only occupies some fraction of the page’s vertical space for many steps. The desired behavior is for its footer to be fixed at the bottom of the viewport.
Specifying the page section type prop as ‘wizard’ resolves the issue. This is the pattern used in the Patternfly documentation for in-page wizards. See here:
https://www.patternfly.org/components/wizard/react-demos#in-page
Using CSS to adjust Patternfly component rendering is an antipattern. More custom CSS means more time spent troubleshooting rendering issues. Custom CSS related to rendering of the wizard has been removed.
There is still an annoying issue. The body of the wizard is not scrollable and will overflow. …
=> Wizard: Fix vertical height bug

src/Components/CreateImageWizard/steps/ImageOutput/ReleaseLifecycle.tsx
This adds RHEL10 lifecycle dates to the chart we show when customers select RHEL8.
Open question: Should we also show this when RHEL9 is selected, now that we want to promote RHEL10 adoption?
=> Wizard: Add RHEL10 to ReleaseLifecycle chart

src/Components/CreateImageWizard/steps/Snapshot/components/Templates.tsx, src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/wizardSlice.ts
Supports these changes to image-builder-crc: https://github.com/osbuild/image-builder-crc/pull/1600, which require the template name
JIRA: [HMS-6299](https://issues.redhat.com/browse/HMS-6299)
=> Wizard: send template name in image request (HMS-6299)

src/constants.ts
We need to fix the ordering of registrations vs custom first boot script. The PR also drops unused WantedBy statements.
=> Wizard: drop unwanted WantedBy and run after custom firstboot

package-lock.json, package.json
This bumps @currents/playwright to version 1.13.2 to skip versions that broke github action.
JIRA: [HMS-8600](https://issues.redhat.com/browse/HMS-8600)
=> devDeps: Manually bump @currents/playwright to 1.13.2 (HMS-8600)

.github/workflows/playwright.yml, config/routes.json, playwright/helpers/helpers.ts
This PR switches the playwright tests in CI to use the consoledot testing
proxy instead of the development one in fec. This should result in
faster and more stable tests.
=> build: add testing proxy to playwright CI

src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx, src/store/wizardSlice.ts, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
If the reset button is clicked, there is a glitch that shows error state for a moment. This commit removes the glitch by setting the snapshot date even for invalid values, and removes the workaround that was previously added.
https://github.com/user-attachments/assets/d47c3a82-c85e-4e1d-bc1d-c423b640ff2b
=> Wizard: fix datepicker glitch after reset

src/App.tsx
The in-page wizard should have its footer fixed/sticky at the bottom of the page with the main body area scrollable if necessary. This is the default Patternfly behavior.
Currently, the entire wizard grows to fill its parent container. Setting the overflow property in its parent div, which has the .chr-render class defined by Insights Chrome, to overflow solves the issue and causes the wizard to behave as it should.
The Insights Chrome team is hesitant to make this change in Insights Chrome as it could break other apps layouts, and suggested using Javascript to accomplish this:
https://github.com/RedHatInsights/insights-chrome/pull/3117#discussion_r2129045341
=> Wizard: Fix overflow issues

src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx, src/Utilities/sortfn.ts
This sorts the activation keys list by name.
The `sortFn` function was also updated to handle undefined values.
JIRA: [HMS-6291](https://issues.redhat.com/browse/HMS-6291)
=> Wizard: Sort activation keys list (HMS-6291)

src/Components/ImagesTable/ImagesTable.tsx
With the change to PF6 the list of items in the table section was not padded properly, we can fix this by wrapping the code in a `PageSection` component.
=> ImagesTable: fix main section alignment

src/Components/CreateImageWizard/CreateImageWizard.scss
We don't use the `Tile` component anymore. I believe we can remove this styling.
JIRA: [HMS-8684](https://issues.redhat.com/browse/HMS-8684)
=> Wizard: Remove unused styling (HMS-8684)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Packages/components/RepoPopovers.tsx
Previously when the Included/Other repos popover button was clicked the tab changed as well. This makes the popover button independent on the selected tab.
JIRA: [HMS-8680](https://issues.redhat.com/browse/HMS-8680)
=> Wizard: Make popover button independent on tab (HMS-8680)

src/Components/CreateImageWizard/CreateImageWizard.scss
This adds a style to make sure the Wizard takes up the entire height of the page also in Firefox.
All the credit for figuring this out goes to @lucasgarfield, I've just opened the PR
JIRA: [HMS-8696](https://issues.redhat.com/browse/HMS-8696)
=> Wizard: Fix wizard height (HMS-8696)

api/config/contentSources.ts, src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/store/contentSourcesApi.ts, src/store/service/contentSourcesApi.ts
- Add `listRepositoryParameters` endpoint to contentSources API
- Display human-readable names instead of technical labels
- Fix inconsistency between Image Builder and Repositories service display
- Resolve "any" vs "Any" capitalization this fix issue: https://github.com/osbuild/image-builder-frontend/issues/3008
it's also fix this bug - https://issues.redhat.com/browse/HMS-8685
**Beofre:**
**After:**
=> Repositories: fix architecture/version display to use readable names (HMS-8707)

.gitignore, playwright.config.ts, playwright/Customizations/Firewall.spec.ts, playwright/Customizations/Hostname.spec.ts, playwright/Customizations/Kernel.spec.ts, playwright/Customizations/Locale.spec.ts, playwright/Customizations/Systemd.spec.ts, playwright/Customizations/Timezone.spec.ts, playwright/fixtures/customizations.ts, playwright/fixtures/popupHandler.ts, playwright/global.setup.ts, playwright/helpers/helpers.ts, playwright/helpers/login.ts, playwright/helpers/wizardHelpers.ts, playwright/test.spec.ts
Add a single login for all tests in the form of a global setup and auth token sharing and move the popup closing logic into a separate fixure. Includes a handler for the new intercom popup notification as well.
=> playwright: Add single login (HMS-6280)

src/Components/CreateImageWizard/steps/ImageOutput/ReleaseLifecycle.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
Since we want to nudge customers to default to RHEL 10, it may make sense to show them the shorter lifecycle of RHEL 9 when they select it.
This is a follow-up of #3337
=> Wizard: Show lifecycle information for RHEL9

src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
The cards are now broken, this should make them selectable again.
=> Wizard: Fix target env cards clickability

playwright/Customizations/Filesystem.spec.ts
New test that checks the Filesystem customization. Wasn't sure about some stuff - helping comment would be  appreciated!
=> Wizard: add Filesystem customization test (HMS-5967)

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
Turn statements around, first explain the functionality and then specify that recommendations are not dependencies.
Update based on https://github.com/osbuild/image-builder-frontend/pull/3353#discussion_r2163233773
=> Wizard: Update recommendations description  (HMS-8703)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTables.tsx, src/Utilities/epel.ts, src/constants.ts
This adds support for the EPEL 10 repository 🔟 _(especially needed since RHEL 10 was made the default 🫣)_ 😅. Changes the way of getting the correct EPEL version for RHEL distribution to be more future proof. ✨ 
Issue Link: [[HMS-8656🔗](https://issues.redhat.com/browse/HMS-8656)]
1. While building a RHEL 10 image and searching for additional packages, the "recommendations" should be coming from EPEL 10 and not 9.
2. After selecting a "recommended" package, the modal should suggest to add and on confirmation actually add EPEL 10 repo in `Repositories`.
3. Building an image with a "recommended" package and added EPEL 10 should work. 
4. The same thing should still work for RHEL 8 and 9 as it does now.
=> Wizard: add EPEL 10 support

package-lock.json, package.json, src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
This bumps eslint-plugin-testing-library from 7.2.2 to 7.5.3 and updates a test to pass linter check.
JIRA: [HMS-8757](https://issues.redhat.com/browse/HMS-8757)
=> devDeps: Bump eslint-plugin-testing-library (HMS-8757)

src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Review/ReviewStepTables.tsx
This removes the column with repository information from package table as it could be confusing and misleading.
=> Wizard: Remove repository column from packages table (HMS-8701)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/Kernel/index.tsx
This hides Kernel step for WSL targets only and adds an alert with info that the customization will not be added to the WSL images if more targets are selected.
More targets including WSL:
=> Wizard: Hide Kernel step for WSL (HMS-8759)

playwright/helpers/wizardHelpers.ts, playwright/test.spec.ts, src/Components/Blueprints/BlueprintCard.tsx, src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
This commit fixes an issue where if both isClickable and isSelectable are passed to a card in Patternfly 6, the hand cursor no longer appears on hover and it is not obvious the card is clickable.
=> BlueprintCard: Make hand cursor appear on hover

src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
This replaces previously used VMware radios with checkboxes, allowing the user to select both VMware vSphere targets at the same time.
JIRA: [HMS-8778](https://issues.redhat.com/browse/HMS-8778)
=> Wizard: Replace VMware radios with checkboxes (HMS-8778)

src/Components/Blueprints/BlueprintDiffModal.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Users/components/RemoveUserModal.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/ShareImageModal/ShareImageModal.tsx
The schema for `Modal` component changed between PF5 and PF6, this updates the modals to their non-deprecated version.
JIRA: [HMS-8691](https://issues.redhat.com/browse/HMS-8691)
=> Wizard: Replace deprecated Modals with non-deprecated ones (HMS-8691)

src/Components/LandingPage/LandingPage.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx
Adds Patternfly sticky header styling to avoid end user confusion around hidden buttons.
Updates HMS-8708
=> fix: landing page sticky header (HMS-8708)

playwright/test.spec.ts, schutzbot/playwright_tests.sh, src/Components/CloudProviderConfig/AWSConfig.tsx, src/Components/CloudProviderConfig/CloudProviderConfig.tsx, src/Components/CloudProviderConfig/validators/index.tsx, src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/Router.tsx, src/store/cloudProviderConfigSlice.ts, src/store/cockpit/cockpitApi.ts, src/store/cockpit/enhancedCockpitApi.ts, src/store/cockpit/types.ts, src/store/index.ts, src/test/mocks/cockpit/cockpitFile.ts
Add a modal/page to configure the `osbuild-worker` with the required configs for the various cloud providers
JIRA: COMPOSER-2488
=> on-prem: cloud provider config modal (COMPOSER-2488)

playwright/Customizations/Firewall.spec.ts, playwright/Customizations/Kernel.spec.ts, playwright/Customizations/Systemd.spec.ts, playwright/Customizations/Timezone.spec.ts, src/Components/CreateImageWizard/LabelInput.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx, src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
This is a suggestion for #3156 which I didn't know existed when I started implementing this draft…
I didn't test the implementation, nor do I know if the return value type `string | null` is a good or even valid approach.
@ksiekl please check if this branch helps and feel free to continue working on it (or ping me if I should continue)
=> CreateImageWizard: Implement user-friendly error messages (HMS-8704)

src/Components/CreateImageWizard/steps/Registration/components/ActivationKeysList.tsx, src/Components/CreateImageWizard/steps/Registration/components/ManageKeysButton.tsx
This updates key dropdown's helper text to match recent mocks and fixes the behaviour when the Wizard got refreshed when pressing "Enter" in the dropdown's input.
Also checked other criteria:
- the input is clearable
- current selection is marked with a check in the list of options
JIRA: [HMS-8825](https://issues.redhat.com/browse/HMS-8825)
=> Wizard: Update activation keys dropdown (HMS-8825)

playwright/test.spec.ts, src/Components/Blueprints/BlueprintActionsMenu.tsx, src/Components/Blueprints/ImportBlueprintModal.tsx, src/Components/CreateImageWizard/steps/FileSystem/components/FileSystemTable.tsx, src/Components/CreateImageWizard/steps/ImageOutput/components/ReleaseLifecycle.tsx, src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx, src/Components/CreateImageWizard/steps/Registration/components/Registration.tsx, src/Components/CreateImageWizard/steps/Repositories/components/Empty.tsx, src/Components/CreateImageWizard/steps/Snapshot/components/TemplatesEmpty.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureHyperVSelect.tsx, src/Components/CreateImageWizard/steps/TargetEnvironment/Gcp/index.tsx, src/Components/ImagesTable/EmptyState.tsx, src/Components/sharedComponents/ImageBuilderHeader.tsx, src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/Blueprints/ImportBlueprintModal.test.tsx, src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx, src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx, src/test/Components/CreateImageWizard/wizardTestUtils.tsx, src/test/Components/ImagesTable/ImagesTable.test.tsx, src/test/Components/LandingPage/LandingPage.test.tsx
As using `data-testid`s in tests is an anti-pattern, this removes more of them and replaces them with appropriate locators in the tests.
JIRA: [HMS-6151](https://issues.redhat.com/browse/HMS-6151)
=> src: Remove more `data-testid`s (HMS-6151)

src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx
**Summary:**
Previously, pressing Enter while typing in the OpenSCAP profile filter caused the page to refresh due to default form submission behavior.
Fixes #2655
This fix adds `event.preventDefault()` to the onKeyDown handler to prevent that behavior and improves keyboard UX by:
- Opening the dropdown if it's currently closed
- Automatically selecting the result if there's exactly one match
- Preserving standard typeahead behavior without triggering a page reload
This ensures the wizard remains stable and keyboard-friendly during profile selection.
**BEFORE:** 
https://github.com/user-attachments/assets/104bbf31-d268-442e-94cc-033291b45417
**AFTER:**
https://github.com/user-attachments/assets/cbb9b769-de8d-4dce-a9a7-a444b7c3cb03
=> Wizard: Prevent page refresh when hitting Enter in OpenSCAP profile selector (HMS-8768)

src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
This sets delay to null for `uploadFile` helper, meaning there's no delay for the `.upload` user method now.
JIRA: [HMS-8925](https://issues.redhat.com/browse/HMS-8925)
=> test: Remove delay for .upload user method (HMS-8925)

src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx, src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx, src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
This renders an empty state with a spinner when fetching target environments and alert when there's an issue.
JIRA: [HMS-8941](https://issues.redhat.com/browse/HMS-8941)
=> Wizard: Add fetch and error state for target environments (HMS-8941)

.github/workflows/playwright.yml
There were some changes in Ethel recently, duration currently seems to be a required field. Ethel team works on a fix.
Default value for duration is 1 year so I've set it to that.
JIRA: [HMS-8958](https://issues.redhat.com/browse/HMS-8958)
=> playwright: Add duration to test account creation request (HMS-8958)

src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx
When creating an empty user, the "+" sign gets hidden, and only pops back up if at least user name, psswd, or ssh key is filed out.
Fixes #3114
JIRA: [HMS-8652](https://issues.redhat.com/browse/HMS-8652)
=> Wizard: disable adding empty user tabs (HMS-8652)

src/App.tsx, src/Components/Blueprints/BlueprintsSideBar.tsx, src/Components/Blueprints/BuildImagesButton.tsx, src/Components/Blueprints/DeleteBlueprintModal.tsx, src/Components/CreateImageWizard/steps/Registration/index.tsx, src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/EditDropdown.tsx, src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx, src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/ImagesTable/Status.tsx, src/Components/LandingPage/NewAlert.tsx, src/Components/LandingPage/Quickstarts.tsx, src/Utilities/useGetEnvironment.ts, src/test/setup.ts
This fixes the way we're importing `useChrome` in some places. The mock was also updated to reflect the changes. This resolves several lint warnings.
JIRA: [HMS-8951](https://issues.redhat.com/browse/HMS-8951)
=> src: Fix `useChrome` import, update mock, solve some lint warnings (HMS-8951)

.github/workflows/playwright.yml
Reverts osbuild/image-builder-frontend#3485
Ethel API is fixed now, we don't need to specify "duration" anymore.
=> Revert "playwright: Add duration to test account creation request (HMS-8958)"

src/Components/CreateImageWizard/utilities/requestMapper.ts, src/store/wizardSlice.ts
- Add fips field to wizardState type with enabled boolean property
- Add fips configuration to initialState with default value false
- Add selectFips selector to access FIPS state from store
- Add changeFips reducer action to update FIPS enabled state
**JIRA:**
[HMS-8992](https://issues.redhat.com/browse/HMS-8992)
FIPS (Federal Information Processing Standards) is a security standard required by organizations that handle sensitive data. 
When enabled, it enforces cryptographic requirements and security policies on the generated image. 
This change adds the Redux state management foundation to support FIPS mode configuration in the image
builder wizard.
the next step of enabling fips if Compliance policy or SCAP profile indicates FIPS needs to be enabled, will be done after UX meeting
=> Wizard: Add FIPS state management infrastructure (HMS-8992)

src/Components/CreateImageWizard/utilities/PasswordValidatedInput.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx, src/test/fixtures/editMode.ts
**Summary**
When editing a blueprint, password fields show an eye icon that appears clickable but is actually disabled for security reasons (passwords cannot be retrieved from the backend). This creates confusing UX where users expect the icon to work but it doesn't respond.
This change adds a tooltip that appears when hovering over the disabled eye button, explaining that "Passwords cannot be viewed when editing a blueprint for security reasons."
The fix wraps the disabled button in a span element to ensure the tooltip triggers properly, as disabled buttons don't receive mouse events.
**Jira**
[HMS-8968](https://issues.redhat.com/browse/HMS-8968)
Fixes #3303
🤖 Generated with AI
**Screen Captures**
| Before                                              | After …
=> Wizard: Add tooltip explaining password visibility in edit mode (HMS-8968)

package-lock.json
npm was complaining about some high-severity vulnerabilities. Fix these by running `npm audit fix`
JIRA: [HMS-9010](https://issues.redhat.com/browse/HMS-9010)
=> devDeps: fix npm vulnerabilities (HMS-9010)

src/Components/CreateImageWizard/steps/Oscap/components/OscapProfileInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx, src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx, src/test/Components/CreateImageWizard/steps/Oscap/FipsMode.test.tsx, src/test/fixtures/oscap.ts
**Summary:** 
Automatically enable FIPS mode when:
User selects OpenSCAP profile with FIPS enabled (e.g., DISA STIG) User selects compliance profile with FIPS enabled and not customized off
- Add FIPS checkbox in openscap step
- Display FIPS status in review step
This ensures security compliance for profiles that require FIPS mode without manual user intervention.
**JIRA:**
[HMS-8919](https://issues.redhat.com/browse/HMS-8919)
**Screen Captures**
| Before                                              | After                                   |
| --------------------------------------------------- | --------------------------------------- |
| <img width="1500" height="600" alt="Screenshot 2025-08-06 at 15 45 36" src="https://github.com/user-attachments/assets/42999dfc-8b50-44a1-9650-e7cf8b71 …
=> Wizard: Enable fips for OpenSCAP profile and compliance police (HMS-8919)

src/test/Components/Blueprints/Blueprints.test.tsx, src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
Add waitFor() for CentOS Stream 8 warning dismissal check
Add await to activation key dropdown interactions
Fixes test failures that only occurred during coverage runs due to timing delays
The changes address timing issues where UI elements don't update fast enough during coverage test runs, which are slower due to code instrumentation.
=> Test: Fix race conditions in coverage tests with proper await handling

src/Components/CreateImageWizard/steps/Oscap/components/OscapProfileInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx, src/store/backendApi.ts, src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx, src/test/fixtures/compliance.ts, src/test/fixtures/oscap.ts
**Summary:**
Previously, when a user selected a compliance policy with tailored rules,
the review page always showed the default profile customizations instead
of the policy-specific customizations.
Root cause: OscapProfileInformation component was only using the profile
endpoint (/oscap/{distribution}/{profile}/customizations) which returns
base profile rules, not the policy endpoint
(/oscap/{policy}/{distribution}/policy_customizations) which returns
customized rules.
**Step-by-Step Reproduction**
1. Create and Configure a Compliance Policy
Register a RHEL system to your Red Hat account
Navigate to Compliance in Red Hat Console
Create a new policy or select an existing one
Associate the registered system to the policy
2. Customize the Policy Rules
Open the policy for editing
Find rules …
=> Wizard: Display customized policy rules in review summary (HMS-8921)

src/Components/Blueprints/BlueprintCard.tsx
Truncate the name of a bp if it's too long and does not fit the Blueprint card on landing page. Not sure truncating is what we want tho. What do you think @regexowl @supakeen ?
Fixes #3034
JIRA: [HMS-9061](https://issues.redhat.com/browse/HMS-9061)
=> Wizard: fix overflowing bp name (HMS-9061)

src/Components/ImagesTable/ImageDetails.tsx, src/Components/ImagesTable/Instance.tsx, src/Components/Launch/GcpLaunchModal.tsx, src/Components/Launch/useGenerateDefaultName.ts
This commit adds launch modal for guiding users through launching a GCP instance from their image. This commit also adds unique image name in the command in the clipboard. That way, users can rebuild the image more times without worrying about duplicate names. This guidance should be as helpful to users as possible, so even if they are able to create their own image name here, we chose it for them for the sake of simplicity.
https://github.com/user-attachments/assets/d06daa99-4f49-483c-af01-6639274bbf6b
=> Launch: implement guidance for GCP (HMS-9004)

src/Components/ImagesTable/ImagesTable.tsx, src/Components/Launch/OciLaunchModal.tsx
This commit adds launch modal for guiding users through launching a Oracle instance from their image. It provides a link to Oracle's cloud and a link for importing the image on the user's side.
The actual implementation:
vs Mocks:
=> Launch: implement guidance for Oracle (HMS-9070)

src/Components/CreateImageWizard/steps/Packages/Packages.tsx, src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx, src/test/fixtures/packages.ts
**Summary**
- Fix issue when clicking the expandable arrow or selecting a package checkbox in the Packages step it caused unexpected row reordering.
- Updated sorting logic to ensure that selecting a package with a specific stream groups all related module streams together at the top.
- Ensured that rows expand in place and selection does not affect row position.
**Jira**
Fixes [HMS-8924](https://issues.redhat.com/browse/HMS-8924)
**How to Test**
1) Navigate to Image Builder wizard → Packages step
2) Search for packages to populate the table
3) Click on the expandable arrow (▶) next to any package row
OR Click on the checkbox to select a package
🤖 Generated with AI
=> Wizard: Resolve row reordering issue on selection and expansion (HMS-8924)

playwright/test.spec.ts, src/Components/Blueprints/BlueprintCard.tsx
This might be an issue with the pf6 truncate component. Since we're not really using the popover, we can just use vanilla js to truncate the string rather than use the Truncate component. We can match the behaviour of the component by also splitting on 24 characters.
https://github.com/patternfly/patternfly-react/issues/11964
=> BlueprintCard: fix name truncation (HMS-9079)

src/Components/ShareImageModal/RegionsSelect.tsx
Replace `innerRef` prop with standard React `ref` prop in MenuToggle component
PatternFly's Select component requires a ref to the toggle element for proper dropdown positioning
=> Wizard: Replace deprecated innerRef with ref in RegionsSelect MenuToggle

schutzbot/playwright_tests.sh
The rhel-10.1 tests are timing out fairly frequently on schutzbot. Our
CI instances only have 2 CPUs, while the codebuild instances have 8.
=> schutzbot/playwright_tests: halve workers on schutzbot

.github/workflows/playwright.yml, .gitignore, buildspec.yml, eslint.config.js, playwright.config.ts, playwright/BootTests/Qcow2.spec.ts, playwright/BootTests/helpers/OpenStackWrapper.ts, playwright/BootTests/helpers/imageBuilding.ts, playwright/BootTests/helpers/targetChooser.ts
This PR implements a initial boot tests that builds a qcow2 image (without any customizations), downloads it, uploads it to a RHOS, boots it and executes a simple command to see if we can connect to the instance.
Following diagram [1] showcases how it works:
Part of the PR is a **Openstack CLI wrapper** that allows us easily to interact with RHOS. The test currently **runs only on the hosted service**.
This is a kick off for a e2e boot tests feature.
[1] [Miro Board](https://miro.com/app/board/uXjVJVpwIJU=/?share_link_id=815069995073)
=> tests/playwright: qcow2 boot test (HMS-8985)

.github/workflows/boot-tests-nightly.yml, .github/workflows/playwright.yml
This PR adds a **scheduled action** that will run the boot tests **Mon-Fri at midnight** and will send a **Slack notification** with results and a link to the job. It also allows **manual runs** (_although only on main since you cannot run upstream actions on branches from forks (I think)_).
How the notification will approximately look in Slack:
=> tests/playwright: Add nightly action for Boot tests with Slack notification

.github/workflows/boot-tests-nightly.yml
The conditions previously were dependent on the playwright step only and fetched invalid `result` steps property. This also caused that when the `playwright-tests` step failed, the _on failure_ notification got skipped as this is standard Github Action behaviour. Changed it to on `success()` and on `failure()`, since they are simpler and fit this use case better, because they are directly controlled by the outcome of previous jobs.
=> playwright/CI: Fix slack notification condition in nightly action

src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx, src/Components/CreateImageWizard/utilities/useValidation.tsx
In the wizard, it is not possible to select one language more times. However, some values like that might come from the API or from the imported blueprint. We should validate that there are no duplicates.
https://issues.redhat.com/browse/HMS-9281
Fix:
=> Wizard: add error duplicated language (HMS-9281)

src/Components/ImagesTable/ImagesTable.tsx, src/Components/ImagesTable/Status.tsx
This PR removes the old analytics (because only failed cloud builds were tracked), and adds a new one with info about the image build (both successful and failed ones, all of the different types).
=> Wizard: clean up analytics to track image creation failure or success (HMS-9219)

src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx
This renders a spinner in the compliance dropdown when policies are getting fetched.
JIRA: [HMS-9312](https://issues.redhat.com/browse/HMS-9312)
=> Wizard: Add spinner to compliance dropdown (HMS-9312)

src/Components/CreateImageWizard/CreateImageWizard.tsx, src/Components/CreateImageWizard/steps/FileSystem/components/FileSystemAutomaticPartitionInformation.tsx, src/Components/CreateImageWizard/steps/Oscap/index.tsx, src/Components/CreateImageWizard/steps/Registration/components/ManageKeysButton.tsx, src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx, src/Components/CreateImageWizard/steps/Repositories/components/ManageRepositoriesButton.tsx, src/Components/sharedComponents/DocumentationButton.tsx
This PR:
- adds tracking "Step Viewed" for when user visits a step. This way, we don't have to set up tracking for each step individually, and newly created steps will also be logged
(@regexowl @lucasgarfield  this makes me think that maybe our tracking via footer buttons is redundant - if we are tracking each step that a user visits and views, maybe current footer buttons tracking is not needed, but I am afraid to just delete them, idk how many people are looking at those statistics. It could also mean that the first bullet point of this pr might be redundant as well, unless we care about if users are using the nav bar)
- adds tracking of links that are leading outside of the wizard
=> Wizard: Tracking links leading outside Wizard (HMS-9218)

.github/dependency-review-config.yml, .github/workflows/README_SECURITY.md, .github/workflows/dependency-review.yml, package-lock.json, package.json, scripts/check-vulnerable-packages.js
Implements checks to avoid https://socket.dev/blog/npm-author-qix-compromised-in-major-supply-chain-attack
as transitive dependency.
The upstream check only seems to check changes and not dependencies already in.
So there is a small script for this. To cover _only_ the specific packages, we could remove `dependency-review-action` but this might give some other benefits 🤷
@regexowl please check.
btw. all the affected packages seem to be removed from npm database already, so we can as well cancel this PR 🤔
=> npm: check for vulnerable packages on each PR

README.md
Emphasize to use `npm clean-install` and explain why.
Always preferring the long form `clean-install` over `ci` as this is more readable for new developers and is the same effort for copy & paste.
Also fixes the TOC.
=> README: emphasize to use `npm clean-install`

src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx, src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
`image-builder.launcheof` was already removed from the code base, these mocks can be cleaned up and flags can be removed after release.
=> test: Clean up mocked flags

package-lock.json, package.json
This resolves following warning outputted when running `npm i`:
```
npm warn deprecated @types/uuid@11.0.0: This is a stub types definition. uuid provides its own type definitions, so you do not need this installed.
```
JIRA: [HMS-9431](https://issues.redhat.com/browse/HMS-9431)
=> devDeps: Remove unused @types/uuid dependency (HMS-9431)

src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx
This was previously set to 10 and there is no other way how to see other policies than the first 10 returned by Compliance API.
=> Wizard: Increase limit for Compliance policies in selector to 50

schutzbot/playwright_tests.sh
Remove Currents from CI runs for Cockpit plugin in Gitlab, because we use four runners per run and each one generates a report, which leads to increased spending for Currents that can be avoided since we can track test results using the results from hosted tests that are mostly the same.
=> playwright/CI: Remove Currents reporter from Gitlab runs (HMS-9314)

.gitlab-ci.yml
Swap AWS m5.large instances for RHOS large runners. This mainly raises the amount of avaiable vCPUs to 4, because m5.large only had 2 and that caused the flakiness in Cockpit plugin PW tests .
=> ci/playwright: Use large RHOS runners instead of AWS m5.large runners for Cockpit 
