osbuild/image-builder-frontend

- src/Routes.js
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/SmartComponents/LandingPage/CreateImageCard.js
- src/SmartComponents/LandingPage/ImagesCard.js
- src/SmartComponents/LandingPage/LandingPage.js
- src/SmartComponents/redux/reducers.js
- src/api.js
- src/constants.js
> components: Move image creation to PF4 wizard

- .travis/custom_release.sh
Ensure we deploy to stage-beta (when master is updated) and stage-stable (when master-stable is updated).
> 🚀 Deploy to stage-beta and stage-stable

- src/api.js
Be compliant with api design guidelines, see osbuild/image-builder#42.
---
merge together with  osbuild/image-builder#42
> api: Use plural URL forms

- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
very basic, make sure we can render all of the expected text
> Initial test for CreateImageWizard

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
Shouldn't this be **https** too ?
> Add // to url

- .eslintrc.yml
- src/Routes.js
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/SmartComponents/ImagesTable/ImagesTable.js
- src/entry-dev.js
So a space before ` />` and no spaces or newlines before `>`
> eslint: jsx-tag-spacing and jsx-closing-bracket-location rules

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
- Registration step in CreateImageWizard
- should allow choosing activation keys
> Add more test automation. Refs #40

- .eslintrc.yml
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
- src/test/testUtils.js
> Fixes for assertion failures in tests

- src/App.js
We shouldn't apply any style at this point, and let any style be
determined by the page we're embedded in.
---
This doesn't affect the current layout:
> src: Replace Main with React.Fragment in App.js

- src/SmartComponents/ImagesTable/ImagesTable.js
- src/test/SmartComponents/ImagesTable/ImagesTable.test.js
- src/test/SmartComponents/LandingPage/LandingPage.test.js
> Adds empty state when no images

- src/PresentationalComponents/CreateImageWizard/WizardStepUploadAWS.js
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
---
The drop in coverage here is due to the removal of code in the wizard.
> CreateImageWizard: Only ask for aws account id in upload step

- README.md
The process got a bit more complex with the mandatory client ssl
auth for composer.
> README.md: Fix dated information

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The wizard now displays inside a modal. Also the field `isInPage` is removed.
> Display wizard in modal

- codecov.yml
- src/App.js
- src/PresentationalComponents/LandingPage/PermissionDenied.js
- src/api.js
- src/test/SmartComponents/LandingPage/LandingPage.test.js
> LandingPage: Show under construction page if image-builder returns 404

- src/PresentationalComponents/LandingPage/PermissionDenied.js
> LandingPage: Add signup button to the under construction page

- src/PresentationalComponents/CreateImageWizard/WizardStepUploadAWS.js
Update the text and title to better fit current designs.
> CreateImageWizard: update aws upload step

- src/PresentationalComponents/CreateImageWizard/WizardStepReview.js
- src/PresentationalComponents/CreateImageWizard/WizardStepReview.scss
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The review page now uses more patternfly components and has been split up a little so it is easier to add review fields for additional target environments.
> CreateImageWizard: update review page

- src/PresentationalComponents/CreateImageWizard/WizardStepReview.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
The wizard crashed in the review step when registering the system later
was selected.
> CreateImageWizard: Fix review step

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
This needs to be an array of strings.
---
We need to rework this, and have the options just be a single flat object in the internal state.
> CreateImageWizard: Fix google share options

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
Image type gcp doesn't exist, it should be vhd.
> CreateImageWizard: Fix google image type

- src/PresentationalComponents/CreateImageWizard/WizardStepImageOutput.js
- src/PresentationalComponents/CreateImageWizard/WizardStepReview.scss
- src/PresentationalComponents/CreateImageWizard/WizardStepUploadAzure.js
- src/PresentationalComponents/CreateImageWizard/WizardStepUploadAzure.scss
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/test/SmartComponents/CreateImageWizard/CreateImageWizard.test.js
---
request generated (bogus values):
```json
{
"distribution": "rhel-8",
"image_requests": [
{
"architecture": "x86_64",
"image_type": "vhd",
"upload_requests": [
{
"type": "azure",
"options": {
"tenant_id": "oqiwjd",
"subscription_id": "qowidj",
"resource_group": "qowidj"
}
}
]
}
],
"customizations": {
"subscription": {
"organization": 000000
}
}
}
```
> CreateImageWizard: Azure upload step

- src/PresentationalComponents/CreateImageWizard/WizardStepUploadAzure.js
> Azure fixes

- src/PresentationalComponents/ImagesTable/Upload.js
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/SmartComponents/ImagesTable/ImagesTable.js
- src/test/SmartComponents/ImagesTable/ImagesTable.test.js
Fixes #105
---
---
TODO update the tests to check this
> ImagesTable: Instead of the image type show the upload target

- package.json
- src/App.js
- src/PresentationalComponents/CreateImageWizard/ImageWizardFooter.js
- src/PresentationalComponents/CreateImageWizard/ImageWizardFooter.scss
- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
- src/store/index.js
on error:
https://user-images.githubusercontent.com/11140201/110132872-ee03ed80-7dcb-11eb-9ddf-d2afb5840491.mp4
notification:
https://user-images.githubusercontent.com/11140201/110132891-f1977480-7dcb-11eb-977b-ae21db44002d.mp4
> Review and create feedback

- src/SmartComponents/CreateImageWizard/CreateImageWizard.js
Change image_request to accept a single upload_request instead of
an array of upload_requests.
> CreateImageWizard: single upload_request

- src/Routes.js
insights-chrome got updated, this should make us compatible.
> routes: Remove root element mutation

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/WizardStepPackages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This should fix the bug where chosen packages would disappear from the
ui when switching steps and returning to the packages step.
> CreateImageWizard: Show previously selected packages

- src/Components/ImagesTable/ImageBuildStatus.js
- src/Components/ImagesTable/ImageBuildStatus.scss
- src/Components/ImagesTable/ImagesTable.js
- src/test/Components/ImagesTable/ImagesTable.test.js
> Improve images list

- src/Components/CreateImageWizard/WizardStepUploadAzure.js
Fix issue #170 
Signed-off-by: Yuxin Sun <yuxisun@redhat.com>
> OAuth permissions text shortening

- src/Components/CreateImageWizard/WizardStepUploadAWS.js
- src/Components/CreateImageWizard/WizardStepUploadAzure.js
> CreateImageWizard: fix target environment titles

- src/Components/CreateImageWizard/WizardStepUploadAzure.js
> CreateImageWizard: fix OAuth info link style

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/WizardStepImageOutput.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The upload destinations now display in alphabetical order.
Fixes #97
> CreateImageWizard: alphabetize upload destinations

- src/store/actions/actions.js
- src/store/reducers/composes.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/testUtils.js
> store: Insert new composes on top of the table

- devel/README.md
- Add instructions for adding environment variables
- Fix small typo in `docker-compose` command
> devtools: update readme

- src/Components/CreateImageWizard/steps/msAzure.js
> CreateImageWizard: Reorder Azure form

- src/Components/CreateImageWizard/formComponents/ReviewStep.js
> CreateImageWizard: Make instructions on Review page normal font size

- src/Components/CreateImageWizard/steps/aws.js
- src/Components/CreateImageWizard/steps/googleCloud.js
- src/Components/CreateImageWizard/steps/msAzure.js
@Gundersanne  I have tried to follow the commit message style I found in the commit log - not entirely sure whether you're okay with those messages (happy to reword!).
Closes #261 and #259
> Wizard inconsistent casing

- .github/workflows/npm-update.yml
Tested in https://github.com/Gundersanne/image-builder-frontend/actions/runs/1033243136
> npm-update: Fix install step

- src/Components/CreateImageWizard/formComponents/ReviewStep.js
Closes #202
Previously no information on Azure was shown on the Review page. Now we show all three parameters (since all of them are mandatory).
> CreateImageWizard: Show Azure information on review page

- src/Components/CreateImageWizard/formComponents/ReviewStep.js
Closes #194 
Please note that this is just a minimal adjustment to the review page layout. I would personally vote for making the subsections in the "Target environment" section stand out more (are we actually bound to using h3 there or can we bump everything by one level and use h3 for the environment titles themselves?).
I can do so in a follow-up PR or even in this one if you like.
> Align all values on Review step

- src/Components/CreateImageWizard/steps/imageOutput.js
- src/Components/CreateImageWizard/steps/imageOutputStepMapper.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fallout from switching to minor versions everywhere.
> CreateImageWizard: Use rhel minor versions everywhere

- src/Components/CreateImageWizard/steps/googleCloud.js
> CreateImageWizard: fix the description for google group

- src/Components/CreateImageWizard/formComponents/Packages.js
When focused on either the available packages or chosen packages search bar, pressing the enter key will search/filter the packages.
Fixes #254
> CreateImageWizard: packages can be searched with enter key

- src/Components/CreateImageWizard/formComponents/Packages.js
> CreateImageWizard: add placeholder text to packages search bars

- src/Components/CreateImageWizard/steps/msAzure.js
> CreateImageWizard: update azure help text to present tense

- src/Components/CreateImageWizard/formComponents/Packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Sort the package results in the CreateImageWizard first by exact matches and then by package results
that start with the same letters as the search term. Fixes #256
Before (search term: "libvirt"):
After:
> CreateImageWizard: sort packages by relevance

- .github/workflows/coverity_scan.yml
https://scan.coverity.com/projects/image-builder-frontend
> ci: Enable Coverity Scan

- src/Components/CreateImageWizard/steps/imageOutput.js
- src/Components/CreateImageWizard/steps/imageOutputStepMapper.js
- src/Components/ImagesTable/Release.js
- src/constants.js
- src/store/reducers/pendingCompose.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
- src/test/redux/actions.test.js
- src/test/redux/reducers.test.js
Bump rhel-84 to rhel-85.
---
Ideally this would be part of #6 ; where we'd pick the latest rhel version that hte service supports dynamically, but this takes priority.
> constants: Introduce RHEL_8 constant

- src/App.js
- src/Components/CreateImageWizard/formComponents/Packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
> Add default state to packages selection

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/CreateImageWizard.scss
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
The review step is improved. The create button now states 'Create image'. The step description text is updated. The fields to be reviewed are now split into tabs for 'Target environment', 'Registration', 'System Configuration'. The target environments show the logo of the environment now. The quantity of packages selected also displays now. Tests are also updated.
Fixes #195
> Improve review step

- src/Components/CreateImageWizard/steps/msAzure.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
> CreateImageWizard: validate the subscription GUID is a valid GUID

- src/Components/CreateImageWizard/formComponents/CustomSubmitButtons.js
> CreateImageWizard: add loading icon when creating image

- src/Components/CreateImageWizard/formComponents/Packages.js
> CreateImageWizard: Show "no package results are found" when no packages are found

- src/Components/CreateImageWizard/formComponents/Packages.js
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/steps/packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Before
https://user-images.githubusercontent.com/11140201/143778615-9c1db6a1-dbda-47f1-8240-c87c1b7e15f4.mp4
---
After
https://user-images.githubusercontent.com/11140201/143778550-091bb6ff-8042-40e3-9c00-2c178d55b30e.mp4
> Fix deselecting single pkg

- src/Components/ImagesTable/ImagesTable.js
- src/test/Components/ImagesTable/ImagesTable.test.js
Also, test the table has expected headers.
Fixes #244
> ImagesTable: add title to Instance column

- src/Components/CreateImageWizard/formComponents/ReviewStep.js
> CreateImageWizard: only display upload review for selected destinations

- src/Components/CreateImageWizard/formComponents/Packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Testing this turned out to be a little more complicated than I would have liked so I will append the tests later.
> CreateImageWizard: display message for invalid chosen packages filter

- src/Components/CreateImageWizard/steps/registration.js
> CreateImageWizard: Detail what subscription means

- package-lock.json
- package.json
- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/ImageCreator.js
- src/Components/CreateImageWizard/formComponents/OrganizationID.js
- src/Components/CreateImageWizard/steps/registration.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
- src/test/Components/LandingPage/LandingPage.test.js
The goal of this PR is to improve the style of our tests per the rules from eslint's plugin for the testing library. This PR includes a version bump for eslint-plugin-testing-library from 3.10.2 to 5.0.1. There were many error types so I devoted one commit to each error class. If you would like I can squash some of them together but it was easiest for me to do this one error type at a time.
> Refactor tests

- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
At the final review step, only render the Registration tab if the user has selected RHEL 8 as the release.
> CreateImageWizard: conditionally render Registration tab

- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
These images need either user customization or a default user.
---
> CreateImageWizard: Disable vmware and installer images

- devel/README.md
Fixed a typo in devel/README.md
> devel: typo fix

- src/Components/CreateImageWizard/ImageCreator.js
- src/Components/CreateImageWizard/formComponents/AzureAuthExpandable.js
- src/Components/CreateImageWizard/formComponents/AzureAuthExpandable.scss
- src/Components/CreateImageWizard/steps/msAzure.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This draft PR is to fix #602. So far, 1 and 2 are completed.
> Update Azure step following SPUR

- src/Components/CreateImageWizard/steps/aws.js
> createimagewizard: update aws step text

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/steps/details.js
- src/Components/CreateImageWizard/steps/index.js
- src/Components/ImagesTable/ImagesTable.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
A user can now enter an optional custom image name. If the user enters a name it is displayed in the table, otherwise, the uuid is displayed.
> Add details step with Image Name field

- src/Components/ImagesTable/ImagesTable.js
The ImagesTable component is now a functional instead of class component. This is useful because it allows us to use react hooks in the component.
This is rebased on top of #643
> Images table hooks

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/ImageCreator.js
- src/Components/CreateImageWizard/formComponents/ActivationKeys.js
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
- src/Components/CreateImageWizard/steps/imageOutputStepMapper.js
- src/Components/ImagesTable/ImagesTable.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
This still needs some updates so opening as a draft.
Particularly the package description and filesystem size need work. Also, I am a little stuck on how to get the nav bar to behave when starting at the review step. Finally, the action kebab has too much padding.
Any thoughts?
> Recreate image builds

- src/Components/CreateImageWizard/steps/aws.js
- src/Components/CreateImageWizard/steps/details.js
- src/Components/CreateImageWizard/steps/fileSystemConfiguration.js
- src/Components/CreateImageWizard/steps/googleCloud.js
- src/Components/CreateImageWizard/steps/imageOutput.js
- src/Components/CreateImageWizard/steps/msAzure.js
- src/Components/CreateImageWizard/steps/packages.js
- src/Components/CreateImageWizard/steps/registration.js
- src/Components/CreateImageWizard/steps/review.js
- src/Components/CreateImageWizard/steps/stepTemplate.js
> CreateImageWizard: Step template with id

- src/Components/CreateImageWizard/steps/stepTemplate.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
> CreateImageWizard: Add customTitle to step template

- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This reverts commit 8e4b4ff6d504d68f93e75ac0b71ba125b2cb0b26.
> Revert "CreateImageWizard: Disable vmware and installer images"

- src/Components/CreateImageWizard/formComponents/SizeUnit.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This gets rid of prop warnings during tests.
> CreateImageWizard/FileSystem: Default to 0 if size input is NaN

- config/prod.webpack.config.js
frontend-components will automatically do the right  thing; using beta/apps if the branch is a beta one.
> config: Let frontend-components set deployment in prod config

- src/Components/CreateImageWizard/formComponents/Packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Resolves #604. The available and chosen package search inputs now have a
clear button which resets the search and list elements to their default
states. This fixes a cosmetic issue related to the focus-visible width
being smaller than the search input width.
This is accomplished by passing an onClear prop to the search input.
This makes state management is more complicated and to facilitate this feature the
chosenFilter was converted from a useState hook to a useRef hook.
The functions used to add all and selected packages were split from two
functions into four functions. The functions appear similiar but this is only
superficial; the logic is actually quite different and there is very
little code reuse. Four separate functions will be easier to understand and
maintain.
This commit …
> CreateImageWizard: Add clear button to package search inputs

- devel/.env
- devel/README.md
- devel/config/composer/osbuild-composer.toml
- devel/config/worker/osbuild-worker.toml
- devel/config/worker/secret
- devel/config/worker/token
- devel/docker-compose.yml
- distribution/Dockerfile
- minor fixes to the devel stack configuration to match the changes in other repos
- switch to a client secret instead of an offline token
- update the frontend entrypoint command
- add profiles to the metrics containers so they are only launched when desired
> Fix docker stack

- .github/workflows/sync-branches.yml
Tested against protected branches.
Automatic sync to stage-stable:
https://github.com/Gundersanne/image-builder-frontend/actions/runs/2238569756
Sync to production:
https://github.com/Gundersanne/image-builder-frontend/actions/runs/2238591787
> .github: Use SCHUTZBOT_GH_TOKEN to push

- .travis/Jenkinsfile
- .travis/custom_release.sh
Inserting different webhook url based on the deployed branch in the
modified Jenkinsfile. Also renaming it to make more sense for us.
> CI: Enable IQE trigger for prod branch

- .travis/custom_release.sh
The Jenkinsfile is actually downloaded to .travis folder so fix the
location for the sed command to work.
> CI: Fix location of Jenkinsfile for sed

- src/Components/CreateImageWizard/formComponents/CentOSAcknowledgement.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
> Wizard: CentOS acknowledgement text updated for production

- src/Components/CreateImageWizard/steps/packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes https://github.com/RedHatInsights/image-builder-frontend/issues/773. This changes description of the Packages step according to recent SPUR.
Tests have been also updated to reflect the changes.
> Wizard: Update description on the Packages step 

- src/test/Components/ImagesTable/ImagesTable.test.js
Instead of supplying the composes directly in the store, let the component call the api.
> test/ImagesTable: use redux store and mocked api

- src/Components/CreateImageWizard/steps/imageOutput.js
Clear subscription data when centos release is selected. Fixes #787
> createimagewizard: clear subscription data

- build_deploy.sh
- deploy/frontend-clowder.yml
- package.json
- pr_check.sh
Adding necessary scripts for migrating our frontend component to container.
> Frontend container migration

- src/Components/ImagesTable/ImageLink.js
- src/Components/ImagesTable/ImageLinkDirect.js
Move the conditional render on the main ImageLink component.
Uses destruct for props to streamline the usage of props.
> Hide launch button until image is built

- src/Components/ImagesTable/Release.js
During UI hackfest, my first minor UI issue!
> imagestable: removed label from release

- src/Components/ShareImageModal/RegionsSelect.js
- src/test/Components/ShareImageModal/ShareImageModal.test.js
- fix proptype of RegionsSelect
- wrap state-changing events in act
> test: fix console warnings

- src/constants.js
- src/repos.js
> src/constants: switch to rhel-87 and rhel-91

- src/Components/CreateImageWizard/formComponents/CustomButtons.js
- src/Components/CreateImageWizard/formComponents/FileSystemConfigButtons.js
- src/Components/CreateImageWizard/steps/aws.js
- src/Components/CreateImageWizard/steps/googleCloud.js
- src/Components/CreateImageWizard/steps/imageName.js
- src/Components/CreateImageWizard/steps/imageOutput.js
- src/Components/CreateImageWizard/steps/msAzure.js
- src/Components/CreateImageWizard/steps/packages.js
- src/Components/CreateImageWizard/steps/registration.js
- src/Components/CreateImageWizard/steps/review.js
This adds custom buttons for each step, where each button has a id taking the format `$step-(next|previous|cancel)-button`.
> CreateImageWizard: custom buttons for each step

- pr_check.sh
We have merged the frontend and backend plugins to one.
> pr_check: use new combined iqe plugin

- package-lock.json
- package.json
Reverts RedHatInsights/image-builder-frontend#892
> Revert "build(deps): bump react-router-dom from 6.4.2 to 6.6.1"

- src/Components/CreateImageWizard/formComponents/ImageOutputReleaseSelect.js
This will help QE with testing the app by having a specific locator for this element.
> Wizard: add ouiaId to release select

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/formComponents/Packages.js
- src/Components/CreateImageWizard/steps/packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Enables package searching and custom repositories.
> CreateImageWizard: use content sources in production beta

- src/Components/ImagesTable/ImageLink.js
needed for https://github.com/RHEnVision/provisioning-frontend/pull/195
> feat(HMS-776): Add provider to provisioning wizard

- src/Components/ImagesTable/ClonesTable.js
- src/Components/ShareImageModal/RegionsSelect.js
- src/store/clonesSlice.js
- src/store/composesSlice.js
This commit allows sharing (cloning) composes that use the sources service to resolve the AWS account ID.
> ShareImageModal: Add support for sources

- package-lock.json
- package.json
- src/Components/CreateImageWizard/formComponents/Packages.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
Includes the `isPlain` styling for the `TextList` component.
> package.json: update @patternfly/react-core

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/CreateImageWizard.scss
- src/Components/CreateImageWizard/ImageCreator.js
- src/Components/CreateImageWizard/formComponents/Registration.js
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/steps/registration.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
[1-2023-03-07_12.35.05.webm](https://user-images.githubusercontent.com/11140201/223412019-7ac627eb-67c2-4b20-a167-56f553bc73fd.webm)
> CreateImageWizard: rhc support

- src/Components/CreateImageWizard/formComponents/AWSSourcesSelect.js
see release_select for ImageOutputReleaseSelect for example
> Specify ouiaId to use as selector for testing

- src/Components/CreateImageWizard/CreateImageWizard.scss
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/formComponents/ReviewStepTables.js
- src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Fixes #919.
This updates the Review step as per proposed mocks.
The tabs were replaced by expandable sections containing all the information relevant to a specific step.
> Wizard: Update the Review step to have expandable sections

- src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
- src/Components/CreateImageWizard/steps/fileSystemConfiguration.js
Fixes #1023. This updates the links on the File system configuration step.
> Wizard: Update links on File system configuration step

- src/Components/ImagesTable/ImageLink.js
@croissanne this one should be straight forward :)
> Send upload info to ProvisioningWizard

- config/dev.webpack.config.js
> config/dev: Revert run proxy without VPN for prod envs

- src/Components/ImagesTable/ImageLink.js
~Depends on https://github.com/RHEnVision/provisioning-frontend/pull/238~
> Provisioning only launch

- src/Components/ImagesTable/RegionsPopover.js
- src/Components/LandingPage/LandingPage.js
- src/Components/sharedComponents/BetaLabel.js
- src/Components/sharedComponents/BetaLabel.scss
- src/test/Components/ImagesTable/ImagesTable.test.js
- src/test/Components/LandingPage/LandingPage.test.js
[beta-2023-04-13_11.01.48.webm](https://user-images.githubusercontent.com/11140201/231710119-9c17f6f6-6149-4e11-b880-3f030615f86e.webm)
---
> LandingPage: add "go to beta" banner

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/ImagesTable/ImageLink.js
- src/Components/LandingPage/LandingPage.js
- src/Components/LandingPage/LandingPage.scss
- src/Components/LandingPage/awsquickstart.json
- src/Components/LandingPage/azurequickstart.json
- src/Components/LandingPage/contentquickstart.json
- src/Components/ShareImageModal/ShareImageModal.js
- src/constants.js
This PR adds two prompts depending if user is in beta or not:
- Beta
- Shows buttons to start quickstarts for AWS and Azure launch and Content sources
- Non-beta
- Invites user to switch to beta to try out launch and content sources
Includes to-beta prompt from @croissanne
Includes quickstarts from @arburka (https://github.com/RedHatInsights/quickstarts/pull/84)
> Add beta prompts

- src/Components/LandingPage/LandingPage.scss
This changes the background color of the "Help get started with beta features" expandable from #FAFAFA to #FFFFFF.
> LandingPage: Change background of "Help get started with beta features"

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/formComponents/Packages.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
- src/Components/CreateImageWizard/formComponents/ReviewStepTables.js
- src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
- src/Components/CreateImageWizard/steps/repositories.js
- src/Components/CreateImageWizard/steps/repositoriesStepMapper.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
custom repositories are added to /etc/yum.repos.d
---
> Embed payload repositories as custom repositories

- src/Components/CreateImageWizard/formComponents/CustomButtons.js
- src/Components/CreateImageWizard/formComponents/FileSystemConfigButtons.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
- src/Utilities/releaseToVersion.js
This makes the wizard feel much 'faster' for a better user experience. The implementation uses RTK Query for prefetching. For most API requests, prefetching is done when the 'next' button is hovered over on the previous step.
> Wizard: Prefetch data for external API calls

- src/Components/ImagesTable/RegionsPopover.js
- src/Components/sharedComponents/BetaLabel.js
Change 'beta' to 'preview' in Launch popover.
> ImagesTable: Change 'beta' to 'preview' in Launch popover

- src/Components/ImagesTable/ImageLink.js
This fixes an erroneous switch statement.
> ImagesTable: Fix switch statement in `ImageLink`

- src/Components/ImagesTable/ClonesTable.js
- src/test/Components/ImagesTable/ImagesTable.test.js
This updates ClonesTable according to the new mocks.
> ImagesTable: Update ClonesTable

- src/Components/CreateImageWizard/CreateImageWizard.js
Related to HMS-1886: Clicking the recreate button on a build with a lot of packages results in the user being rate limited.
Package summaries are obtained by querying the Content Sources API. A large number of packages requires a large number of requests and leads to the rate limiting problem when using the 'Recreate image' function.
This commit fixes the problem by not requesting or displaying package summaries when 'Recreate image' is used. (Note that newly added packages will still request and display a summary.)
The 'Recreate image' function will soon be replaced by blueprints. This hotfix should carry us forward until then.
> Wizard: Hotfix for recreate image rate limiting issue

- src/Components/ImagesTable/ClonesTable.js
- src/Components/ImagesTable/ImageDetails.js
- src/Components/ImagesTable/ImagesTable.js
- src/test/Components/ImagesTable/ImagesTable.test.js
This adds expandable rows details for each image and updates ClonesTable according to the new [mocks](https://www.sketch.com/s/d7aa6d29-fca0-4283-a846-09cc5fd10612/a/qbbyGg3).
> ImagesTable: Add image details and update ClonesTable

- src/Components/LandingPage/LandingPage.js
This updates the text on the "About" popover and adds links according to recent [mocks](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/QDREEpx).
> LandingPage: Update the "About" popover

- src/Components/ImagesTable/ImagesTable.js
This updates text and links on empty state according to recent mocks.
> ImagesTable: Update wording and links on empty state

- api/config/contentSources.ts
- api/config/imageBuilder.ts
- src/store/contentSourcesApi.ts
- src/store/imageBuilderApi.ts
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/fixtures/packages.tsx
This migrates the `packages` fixture to TypeScript and adds needed types to `index.ts`
> test/fixtures: Migrate the `packages` fixture to TypeScript

- api/config/contentSources.ts
- api/config/imageBuilder.ts
- api/config/provisioning.ts
- api/config/rhsm.ts
This fixes linting errors in configuration files for API code generation.
> api/config: Lint API configs

- src/test/fixtures/repositories.ts
This migrates repositories fixture to TypeScript.
> test/fixtures: Migrate repositories fixture to TypeScript

- src/Components/LandingPage/LandingPage.tsx
Depends on https://github.com/RedHatInsights/quickstarts/pull/119
> Add GCP quickstart button

- .eslintrc-typescript.yml
- .eslintrc.yml
- package-lock.json
- package.json
- src/Components/ImagesTable/ImageBuildErrorDetails.js
- src/Components/ImagesTable/ImageBuildStatus.js
- src/Components/ImagesTable/ImageDetails.js
- src/Components/ImagesTable/RegionsPopover.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
This PR enforces react linting rules for eslint and fixes the errors.
React doc: https://react.dev/learn/editor-setup#linting
(Warnings are staying untouched because I think that's next level to fix them all :sweat_smile:)
> eslint: enforce react rules and fix errors

- src/Components/CreateImageWizard/formComponents/MountPoint.js
> CreateImageWizard: don't allow arbitrary mountpoints under /boot

- src/Components/LandingPage/LandingPage.tsx
This should follow up enabling Content and Launch(#1313) in stable.
> Remove the Preview banner

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/steps/packages.js
- src/test/Components/CreateImageWizard/CreateImageWizard.beta.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
Adds feature flag gating to custom repositories in preparation for Content service M1 GA.
> Custom Repositories gate by Feature flag

- src/Components/CreateImageWizard/steps/registration.js
This fixes the capitalization on the Review step from "Automatically Register your systems" to "Automatically register your systems".
> feat(HMS-1491): Fix capitalization on the Register step

- api.sh
- api/config/edge.ts
- api/schema/edge.json
- src/constants.js
- src/store/edgeApi.ts
- src/store/emptyEdgeApi.ts
- src/store/index.js
This commit adds the Edge API to RTK Query in preparation of porting edge source code to image-builder-frontend
> Api: generate RTK Query for Edge

- src/Components/ImagesTable/ImageLink.js
- src/Utilities/useProvisioningPermissions.js
This PR adds RBAC implementation for provisioning/launch wizard.
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/f9a7c3a1-8b21-43c3-8365-90d62c2673fe
> feat(HMS-1454): add RBAC permissions to launch wizard

- src/Components/LandingPage/LandingPage.tsx
- src/Components/LandingPage/Quickstarts.tsx
Promissed refactoring :)
Looks much cleaner, good thinking @lucasgarfield ! :+1:
> Extract quickstarts banner into its own component

- api/config/edge.ts
- src/store/edgeApi.ts
This commit adds more RTQ Query in preparation of porting edge source code to image-builder-frontend
> API: generate more RTK Query for edge

- api/schema/provisioning.json
- src/store/helpers.ts
- src/store/provisioningApi.ts
- src/test/fixtures/sources.ts
Follow-up for https://github.com/RedHatInsights/image-builder-frontend/pull/1299
This updates the OpenAPI spec to the new version with the nested root.
> Migrate to Provisioning API nested root

- src/Components/ImagesTable/Instance.tsx
This commit is a hotfix that restores functionality to the Launch wizard.
The `appendTo` variable must be wrapped in a useMemo() hook to work properly. Additionally, the `hasAccess`  property was missing from the `<ProvisioningWizard>` component.
To ensure full backwards compatibility, the component has also been wrapped in a `<Suspense>` as it was previously.
> LaunchWizard: Restore Launch wizard functionality

- api/config/edge.ts
- api/schema/edge.json
- src/store/edgeApi.ts
This commit adds 2 more RTQ Query in preparation of porting edge source code to image-builder-frontend
> api: add new edge endpoints

- src/Components/edge/ImageDetails.js
The federated image details been broken by a prior 
PR. FIXES: https://issues.redhat.com/browse/HMS-2620
> edge: Fixes federated edge image details view.

- pr_check.sh
I have set up a new marker "fe_pr_check" to select tests for the pr_check here. I'm also increasing the timeout of the CJI pod.
> pr_check: change marker and increase timeout

- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
- src/Components/ShareImageModal/RegionsSelect.tsx
this commit fixes some react-hooks/exhaustive-deps linting warning message
> fix some react-hooks/exhaustive-deps lint warning message

- src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/ShareImageModal/RegionsSelect.tsx
- src/store/actions/actions.js
- src/store/enhancedImageBuilderApi.ts
this commit fix some linting warnings that user get when running npm run lint:js:fix command,
some worning comes after big changes to TypeScript
> fix some lint warning message

- src/Components/CreateImageWizard/formComponents/CustomButtons.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
- src/Utilities/checkRepositoriesAvailability.js
This updates requests that contained hardcoded value `x86_64` as an architecture.
> Wizard: Remove hardcoded architecture

- src/Components/ImagesTable/ImageDetails.tsx
> ImagesTable: show architecture of composes

- src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/ImagesTable/ImagesTable.test.js
- src/test/Components/ShareImageModal/ShareImageModal.test.js
This cleans up comments in tests and removes all that are no longer relevant.
> test: Remove out-of-date comments

- api/schema/imageBuilder.yaml
- src/Components/CreateImageWizard/CreateImageWizard.js
- src/store/imageBuilderApi.ts
Depends on https://github.com/osbuild/image-builder/pull/897
This updates the api schema and adds a ClientId value to the request sent to the api.
> api/Wizard: Update ImageBuilder api schema and add ClientId to a compose request

- deploy/iqe-trigger-integration.yml
This commit adds a iqe trigger integration.
Copied from this [file](https://github.com/osbuild/image-builder/blob/main/templates/iqe-trigger-integration.yml).
> HMS 3030 - Add iqe trigger integration

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/steps/googleCloud.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
CreateImageWizard: fix passing gcp upload_options
Upload options were added in the wrong place, this inserts them back
into the correct place.
Also see #1355.
> CreateImageWizard: fix passing gcp upload_options

- src/Components/CreateImageWizard/formComponents/TargetEnvironment.js
Move the oracle cloud infrastructure PR to stable.
> CreateImageWizard: move oci to stable

- src/api.js
This removes Axios API calls which were replaced by RTK Query.
> api: Remove unused Axios API calls

- src/Components/CreateImageWizard/CreateImageWizard.js
There were some leftovers that needs to be removed. This commit simply cleans them up.
> wizard: remove unused code from the implementation

- src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This removes unused variable from the code.
> Wizard/test: Remove unused variables

- .github/workflows/dev-checks.yml
This adds a check to ensure that the code generated automatically by `npm run api` has no manual changes.
> workflows: Add check for manual changes to API

- package-lock.json
- package.json
- src/store/contentSourcesApi.ts
- src/store/edgeApi.ts
- src/store/imageBuilderApi.ts
- src/store/rhsmApi.ts
- src/test/fixtures/repositories.ts
This bumps @rtk-query/codegen-openapi to version 1.2.0 and runs `npm run api` to apply changes to the API.
> deps: Bump @rtk-query/codegen-openapi from 1.0.0 to 1.2.0 and re-generate API

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
- src/Components/CreateImageWizardV2/validators.ts
- src/store/index.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This PR adds the AWS substep to the Image Output step.
> V2 Wizard - AWS

- api/config/imageBuilder.ts
- api/schema/imageBuilder.yaml
- src/store/imageBuilderApi.ts
Include the experimental blueprint endpoints.
> api: update image builder api

- src/Components/CreateImageWizard/formComponents/Oscap.tsx
this commit convert oscap file from JavaScript to TypeScript
> Oscap: convert oscap javaScript file to typeScript file

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx
- src/Components/CreateImageWizardV2/validators.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
`<Gcp>` state is now managed with RTK instead of DDF.
> V2Wizard: Add `<Gcp>` step

- api.sh
- api/schema/imageBuilder.yaml
- src/store/imageBuilderApi.ts
First commit modifies `api.sh` so that the image builder api.yaml file is downloaded with curl, this way we don't have to manually download it anymore.
Second commit updates api via `npm run api`.
> API: improve api.sh and update api

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
This adds the OpenSCAP step to the V2Wizard,
adds new values to the wizardSlice and enables relevant tests in the `CreateImageWizard.test.tsx` test suite
> V2Wizard: add oscap to wizard2

- src/Components/Blueprints/BlueprintCard.tsx
- src/Components/Blueprints/BlueprintsSideBar.tsx
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/LandingPage/LandingPage.tsx
- src/test/Components/Blueprints/Blueprints.test.js
- src/test/fixtures/blueprints.ts
- src/test/mocks/handlers.js
This PR adds an handler for selecting a blueprint and triggering its corresponding composes
https://github.com/RedHatInsights/image-builder-frontend/assets/11807069/69ebb332-f97c-4be7-88d2-e905637b28c1
> feat(HMS-3391): add blueprint onclick handler

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
- src/Components/CreateImageWizardV2/steps/Details/index.tsx
- src/Components/CreateImageWizardV2/validators.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
this commit add Details step to v2Wizard
> V2Wizard:  add Details step to wizrd2

- src/Components/CreateImageWizard/formComponents/Packages.js
This temporarily disables custom packages search and adds an alert to the step.
> Wizard: Temporarily disable custom packages search

- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This enables a description check in the V2Wizard testing suite.
> test: Enable blueprint description test

- api/config/imageBuilder.ts
- api/schema/imageBuilder.yaml
- src/Components/Blueprints/BlueprintCard.tsx
- src/Components/Blueprints/DeleteBlueprintModal.tsx
- src/store/enhancedImageBuilderApi.ts
- src/store/imageBuilderApi.ts
This is a work in progress for now, as there is still a small glitch caused by some error. I did not discover the reason for that yet. But feel free to comment if this is going the right direction. :+1:
> feat(HMS-3390): Delete blueprint button

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/steps/Review/index.tsx
- src/store/helpers.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This adds the Review step to the V2Wizard.
> V2Wizard: Review step 

- src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
This updates the dates shown in the description text for the Release lifecycle on the Review step.
> Wizard: Fix dates in Release Lifecycle text on the Review step

- src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/OscapProfileInformation.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
- src/test/fixtures/oscap.ts
this commit adds kernel arguments and enabled/disabled services to Oscap step.
and also add to Review step.
> feat(HMS-3500) V2Wizrd: add kernel and services data

- README.md
Based on some previous discussions, here are the proposed principles for the frontend.
> README: Add frontend principles

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/formComponents/Oscap.tsx
- src/Components/CreateImageWizard/formComponents/OscapProfileInformation.tsx
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/Components/CreateImageWizard/formComponents/ReviewStepTextLists.js
- src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.js
This PR ports the work done on 40b1d4de to the V1 wizard.
> wizard/oscap: kernel and services customizations

- src/Components/CreateImageWizard/formComponents/CustomButtons.js
- src/Components/CreateImageWizard/formComponents/Packages.js
- src/Components/CreateImageWizard/formComponents/Repositories.js
- src/Components/CreateImageWizard/formComponents/ReviewStep.js
- src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
This re-enables custom repositories step and the relevant tests.
> Wizard: Re-enable custom repositories HMS-3637

- src/Components/CreateImageWizard/formComponents/AzureSourcesSelect.js
this commit clean the resource group at Azure step when user clean the source field
https://issues.redhat.com/browse/HMS-3567
> feat(HMS-3567): fix cleanup of Reource Group

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureAuthButton.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
- src/Components/CreateImageWizardV2/types.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
- src/Components/CreateImageWizardV2/validators.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.azure.test.tsx
this commit add the Azure step to the new wizrad
> feat(HMS-3537) V2Wizard: Create a folder for Azure step and copy needed components

- src/Components/ImagesTable/ImagesTable.tsx
> Blueprints: add blueprint out-of-sync alert

- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx
this commit fix source name and shared to account at review step, when user choose to use an account configured from Sources.
> feat(HMS-3553) V2Wizard: fix source name at review step when target is AWS

- api/config/contentSources.ts
- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
- src/Components/CreateImageWizardV2/steps/Packages/index.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
- src/store/contentSourcesApi.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizard/CreateImageWizard.content.test.js
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
- src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
- src/test/fixtures/packages.ts
This is an initial Packages step PR. Two PRs will follow up:
1. OpenSCAP initialization of the packages included in a profile + onRecreate packages as both are presented as a flat list only, those will need to be rendered in a different way from the package lists fetched from the API
2. Proactive Assistance repositories recommendations
> V2Wizard: Packages step

- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
The tests in the suite were improperly nested, this fixes the problem.
Structure before (steps starting by GCP are nested under AWS)
After the fix (all steps on top level)
> test: Re-align CreateImageWizard.test tests

- src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
Adds tests that verify using the custom packages step to add a custom package results in a correctly generated API request.
> V2Wizard/Packages: Add tests for requests

- .github/workflows/pr_best_practices.yml
Add an additional PR check that verifies that each pull request
1. Has a non-empty description
2. Has a title that complies with the schema: `component: This is the subject (JIRA-001)`
3. If both are ok, it adds the 'best practice' label to the PR (2 isn't blocking).
> ghactions: Add PR best practice check (COMPOSER-2140)

- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
This re-enables the rest of AWS tests in CreateImageWizard.test.tsx
> test: Re-enable part of AWS tests (HMS-2781)

- src/Components/ImagesTable/EmptyState.tsx
- src/Components/ImagesTable/ImagesTable.tsx
- src/test/Components/Blueprints/Blueprints.test.js
> Blueprints: add blueprint's images empty state

- src/Components/Blueprints/BlueprintActionsMenu.tsx
- src/Components/Blueprints/BuildImagesButton.tsx
- src/Components/Blueprints/DeleteBlueprintModal.tsx
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/LandingPage/LandingPage.tsx
- src/Components/sharedComponents/ImageBuilderHeader.tsx
- src/test/Components/ImagesTable/ImagesTable.test.js
This is a followup of #1631 and an update according to our new mockups. :)
> feat(HMS-3686): Update position of blueprint buttons

- src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
this commit change the path for MajorReleasesLifecyclesChart in the review. this fix the correct path of import
> change the import path for MajorReleasesLifecyclesChart

- src/Components/CreateImageWizardV2/steps/Details/index.tsx
- src/Components/CreateImageWizardV2/steps/ImageOutput/index.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
- src/Components/CreateImageWizardV2/steps/Packages/index.tsx
- src/Components/CreateImageWizardV2/steps/Registration/index.tsx
- src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
- src/Components/CreateImageWizardV2/steps/Review/index.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Gcp/index.tsx
This replaces h2 heading on the steps with h1 and adds a size modifier to keep the sizes approximately similar.
> V2Wizard: Replace h2 heading with h1 and sizing (HMS-2781)

- package-lock.json
- package.json
- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/EditImageWizard.tsx
- src/Components/CreateImageWizardV2/UsrSubDirectoriesDisabled.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemAutomaticPartitionInformation.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/TargetEnvironment.test.tsx
V2Wizrd: Create file System configuration step
> V2 Wizard: Add File System Configuration Step (HMS-2781)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/store/wizardSlice.ts
this commit add the addPartition function to support the adding partition
at the file system step
> V2Wizard: Add partition function (HMS-3752)

- package-lock.json
- package.json
This pins the @types/uuid version as pinned version of dependencies work best with dependabot.
> deps: Pin @types/uuid

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/store/wizardSlice.ts
ths commit fix the remove partition functionalli file system step
> V2Wizard: fix remove partition funtionallity (HMS-3753)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
- src/store/wizardSlice.ts
this commit change the default table when user choose manual configuration at file system step
> V2Wizard: change default table when user choose manual cunfiguration

- src/Components/CreateImageWizardV2/steps/Review/Footer/Footer.tsx
This encloses Save button inside a div to make testing with widgetastic.patternfly library's pattern possible.
> V2Wizard: Put Save button into div

- src/Components/Blueprints/BlueprintsPagination.tsx
- src/Components/Blueprints/BlueprintsSideBar.tsx
- src/Components/Blueprints/DeleteBlueprintModal.tsx
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/LandingPage/LandingPage.scss
- src/Components/LandingPage/LandingPage.tsx
- src/test/Components/Blueprints/Blueprints.test.js
- src/test/fixtures/blueprints.ts
- src/test/mocks/handlers.js
So, from the ticket description, we want to have server-side blueprints pagination here. Feel free to review the chosen solution.
<details>
<summary>The feature</summary>
</details>
> feat(HMS-3401): Add pagination for blueprints sidebar

- src/Components/ImagesTable/Instance.tsx
Add Popover to inform user the image is build for an older then current Blueprint version.
Fixes HMS-3763
> Images: add popover when the image is outdated (HMS-3763)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/store/wizardSlice.ts
this commit fix the partition table at review step when user choose manual partition
> V2Wizard: fix partition at review step (HMS-3754)

- deploy/iqe-trigger-integration.yml
We have switched from using a custom selenium image to the upstream variant so updating the testing template accordingly.
> templates/testing: Update sel testing image frontend (IQE-2748)

- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
This adds data-testid to the Packages search input and to the Available and Selected toggles.
> V2Wizard: Add test IDs to Packages step 

- src/store/enhancedImageBuilderApi.ts
> fix(HMS-3854): make blueprint toast notification clearer

- src/Components/CreateImageWizardV2/steps/Details/index.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemAutomaticPartitionInformation.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/index.tsx
- src/Components/CreateImageWizardV2/steps/ImageOutput/index.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
- src/Components/CreateImageWizardV2/steps/Packages/index.tsx
- src/Components/CreateImageWizardV2/steps/Registration/index.tsx
- src/Components/CreateImageWizardV2/steps/Repositories/index.tsx
This updates the copy of the Wizard steps based on the recent SPUR.
> V2Wizard: Update copy based on SPUR

- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
- src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
- src/store/wizardSlice.ts
- src/test/fixtures/repositories.ts
- src/test/mocks/handlers.js
This PR is a part of Proactive Assistance - Repository recommendations.
New toggle group was added which allows user to see results from non-added EPEL repository in a case that searched term didn't return any results from added custom and distribution repos.
> V2Wizard: Repository recommendations (HMS-3249)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemPartition.tsx
this commit adds ouiaIds to the file system for automation and manual configurations and for text input field.
> V2Wizard: Add ouiaIds to File System step

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.js
this commit remove the warning
> V2Wizrd: remove Duplicate mount points warning

- src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx
- src/Components/CreateImageWizardV2/steps/Review/Footer/EditDropdown.tsx
- src/test/Components/CreateImageWizardV2/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
This updates copy on the Save changes button as per recent mocks.
mocks:
> V2Wizard: Update create/edit button copy

- src/Components/CreateImageWizardV2/CreateImageWizard.scss
- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
- src/test/Components/CreateImageWizardV2/CreateImageWizard.compliance.test.tsx
This updates a few things connected to the repository recommendations:
- adds a "Searching" state to indicate that data is being fetched
- updates previously incorrect links
- adds tally of selected packages
- updates how are packages from compose request rendered
> V2Wizard: Repository recommendation updates

- src/Components/Blueprints/BlueprintActionsMenu.tsx
- src/Components/sharedComponents/ImageBuilderHeader.tsx
So I was thinking how to make it possible to develop the import/export, and added also an experimental flag together to the import/export that should be disabled. Does this make sense to you?
> V2 Wizard: Add feature flag for import/export (HMS-3906)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
Making it consistent with V1 wizard.
> V2Wizard: Update ouiaIds for File system configuration

- src/Components/CreateImageWizardV2/ValidatedTextInput.tsx
Needed for it to get applied from the File System Configuration step.
> V2Wizard: Add ouiaId to ValidatedTextInput

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemTable.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
The blueprint request now contains a field for the filesystem in its customizations.
> V2 Wizard: Add custom file system to request customizations (HMS-3690)

- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemTable.tsx
Need to distinguish it from V1 table.
> V2Wizard: Add ouiaId for FileSystemTable

- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
> WizardV2: use the alert color darker

- src/Components/CreateImageWizardV2/utilities/requestMapper.tsx
This adds recommended repositories to the custom and payload repositories in the compose request.
> V2Wizard: Add recommended repositories to compose request

- src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx
This updates alert and modal based on UX feedback.
> V2Wizard: Update repo removal alert and modal

- src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx
This updates wording on a repo removal modal in Edit mode as per UX feedback.
> V2Wizard: Update wording on repo removal modal in Edit mode

- src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx
Adds tests to verify that building an Azure image using either sources or manually entering the required info results in a correctly generated request.
> V2 Wizard: Add Azure tests (HMS-2781)

- src/store/wizardSlice.ts
> WizardV2: fix details validation on Edit

- api/config/imageBuilder.ts
- api/schema/imageBuilder.yaml
- src/Components/CreateImageWizardV2/CreateImageWizard.scss
- src/Components/CreateImageWizardV2/steps/Packages/PackageRecommendations.tsx
- src/Components/CreateImageWizardV2/steps/Packages/index.tsx
- src/Components/ImagesTable/Release.tsx
- src/store/imageBuilderApi.ts
- src/test/Components/CreateImageWizardV2/CreateImageWizard.content.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
- src/test/fixtures/packages.ts
- src/test/mocks/handlers.js
This adds an expandable with package recommendations to the Packages step.
The recommendations are populated when two or more packages are selected.
> V2Wizard: Packages recommendation (HMS-3890)

- src/Components/CreateImageWizardV2/steps/Oscap/Oscap.tsx
Fixes #1971
This disables stig and stig_gui profiles which are currently broken.
> V2Wizard: Disable stig and stig_gui

- src/Components/Blueprints/BlueprintsSideBar.tsx
reset pagination on "View all" closes #2008
> BlueprintsSideBar: reset pagination on "View all"

- src/Components/CreateImageWizard/CreateImageWizard.js
- src/Components/CreateImageWizard/formComponents/ActivationKeys.js
- src/Components/CreateImageWizard/formComponents/CentOSAcknowledgement.js
- src/Components/CreateImageWizard/formComponents/FileSystemConfiguration.js
- src/Components/CreateImageWizard/formComponents/Registration.js
- src/Components/CreateImageWizard/formComponents/ReleaseLifecycle.tsx
- src/Components/CreateImageWizard/steps/fileSystemConfiguration.js
- src/Components/CreateImageWizard/steps/msAzure.js
- src/Components/CreateImageWizard/steps/registration.js
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemAutomaticPartitionInformation.tsx
- src/Components/CreateImageWizardV2/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizardV2/steps/ImageOutput/CentOSAcknowledgement.tsx
- src/Components/CreateImageWizardV2/steps/ImageOutput/ReleaseLifecycle.tsx
- src/Components/CreateImageWizardV2/steps/Oscap/index.tsx
- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
- src/Components/CreateImageWizardV2/steps/Registration/ActivationKeysList.tsx
- src/Components/CreateImageWizardV2/steps/Registration/RegisterLaterInformation.tsx
- src/Components/CreateImageWizardV2/steps/Registration/Registration.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
- src/Components/ImagesTable/EmptyState.tsx
- src/Components/ImagesTable/Instance.tsx
- src/Components/LandingPage/LandingPage.tsx
- src/Components/edge/ImagesTable.js
- src/Components/sharedComponents/DocumentationButton.js
- src/Components/sharedComponents/ImageBuilderHeader.tsx
- src/constants.js
Fixes #1923
This moves all URLs from code to constants.
> constants: Move URLs to constants

- src/Components/CreateImageWizardV2/steps/Registration/RegisterLaterInformation.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsAccountId.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/index.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
- src/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/index.tsx
This converts all headings and subheadings to sentence case for the sake of consistency.
> V2Wizard: Consistent capitalisation

- src/Components/ImagesTable/ImagesTable.tsx
- src/Utilities/time.ts
I just wanted to see the time as I build a lot locally :-D
would this be useful?
> ImagesTable: show detailed time when hovering over the "Updated" column

- src/Components/LandingPage/LandingPage.tsx
- src/Components/LandingPage/NewAlert.tsx
> LandingPage: Update 'new' alert for blueprints to support quickstarts

- src/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.tsx
> V2 Wizard: Expose OCI images in stable (HMS-2781)

- api/schema/imageBuilder.yaml
- src/Components/ImagesTable/Release.tsx
- src/constants.js
- src/store/imageBuilderApi.ts
- src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
- src/test/fixtures/architectures.ts
- src/test/fixtures/blueprints.ts
- src/test/fixtures/composes.ts
> src: Add rhel-94

- src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizardV2/wizardTestUtils.tsx
- src/test/fixtures/blueprints.ts
- src/test/fixtures/composes.ts
This replaces 'rhel-94' with a RHEL_9 constant in the tests.
> test: Replace 'rhel-94' with a constant

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx
- src/Utilities/useBetaFlag.ts
> V2Wizard: Hide first boot from review step (HMS-3582)

- src/App.js
This updates the page titles according to this [ticket](https://issues.redhat.com/browse/RHINENG-9387) and [sheet](https://docs.google.com/spreadsheets/d/1Uhwn6i9B383xUbnRQ2IWY3EZ6dihc-UfkHxnR_c7zXI/edit#gid=1001620868)
> fix(RHINENG-9387): update page titles

- api/schema/imageBuilder.yaml
- src/Components/ImagesTable/Release.tsx
- src/store/imageBuilderApi.ts
https://github.com/osbuild/image-builder/pull/1200
> src: add rhel-8.10

- api/schema/imageBuilder.yaml
- src/Components/Blueprints/BuildImagesButton.tsx
- src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx
- src/Components/CreateImageWizardV2/steps/Review/Footer/EditDropdown.tsx
- src/store/imageBuilderApi.ts
add changes at schema for /experimental/blueprints/{id}/ end point <[HMS-4066](https://issues.redhat.com/browse/HMS-4066)>
> add changes at schema for /experimental/blueprints/{id}/ end point <HMS-4066>

- pr_check.sh
As that's our target eventually and it fixes issues with pulp/content-sources
> pr_check: change --ref-env to insights-production

- src/store/emptyImageBuilderApi.ts
Will need [image-builder#1222](https://github.com/osbuild/image-builder/pull/1222) to work :)
> api: Add extra header to distinguish UI requests (HMS-4254)

- deploy/iqe-trigger-integration.yml
We want to share downloaded files between the iqe and selenium containers.
> templates/iqe: Add downloads mount

- deploy/iqe-trigger-integration.yml
Name update from hms-integration to insights-experiences.
> ci(HMS-3962): Update Integration test image for IQE

- src/Components/ImagesTable/ImagesTableToolbar.tsx
- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/fixtures/blueprints.ts
- src/test/mocks/handlers.js
This adds an alert about CentOS Stream 8 being EOL.
> ImagesTable: Add alert for CentOS Stream 8 blueprints

- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
Need some ouiaIds for this step to simplify testing.
> Packages: Add ouiaIds

- deploy/iqe-trigger-integration.yml
We don't have any parallel test cases yet.
> templates/iqe: add parameter to disable parallel runs

- api/schema/imageBuilder.yaml
- src/Components/ImagesTable/Release.tsx
- src/constants.ts
- src/store/imageBuilderApi.ts
- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/mocks/handlers.js
This PR is part of th  transition  out of the `/experimental` for blueprint related endpoint.
Following https://github.com/osbuild/image-builder/pull/1203
> feat(HMS-4200): remove blueprint endpoints /experimental

- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizardV2/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizardV2/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizardV2/steps/ImageOutput/TargetEnvironment.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizardV2/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Aws/AwsTarget.test.tsx
- src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/Azure/AzureTarget.test.tsx
- src/test/Components/CreateImageWizardV2/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/fixtures/blueprints.ts
- src/test/fixtures/editMode.ts
- src/test/mocks/handlers.js
This adds basic edit mode tests for the remaining steps.
> test: Add edit mode tests (HMS-4303)

- api/config/contentSources.ts
- src/Components/CreateImageWizardV2/steps/Packages/Packages.tsx
- src/Components/CreateImageWizardV2/steps/Packages/index.tsx
- src/Components/CreateImageWizardV2/steps/Repositories/Repositories.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizardV2/utilities/requestMapper.ts
- src/store/contentSourcesApi.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizardV2/steps/Packages/Packages.test.tsx
- src/test/fixtures/packages.ts
- src/test/mocks/handlers.js
https://github.com/osbuild/image-builder-frontend/assets/11140201/8001d398-6b96-4ee7-bc74-ada93cd5c3d4
Maybe we should do expanded rows, but as a minimal thing let's do this first?
> Search for package groups (HMS-4094)

- src/Components/CreateImageWizardV2/steps/Details/index.tsx
This updates helper text for blueprint name validation, making the "word characters" more specific.
> Wizard: Update text for name validation

- src/Components/CreateImageWizardV2/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizardV2/steps/Review/ReviewStepTextLists.tsx
- src/test/Components/Blueprints/Blueprints.test.tsx
Where applicable renamed Image details or name to blueprint details or name.
> Wizard/Review: Rename from Image to blueprint

- src/Components/CreateImageWizardV2/steps/Review/Footer/CreateDropdown.tsx
this commit change navigation to specific image when creating and building new image
> CreateDropdown: change navigation to specific image <HMS-4258>

- src/constants.ts
This updates documentation URLs.
> constants: Update URLs

- src/Components/CreateImageWizardV2/steps/Snapshot/index.tsx
Now that https://github.com/osbuild/image-builder/pull/1244 is merged, this works for custom repos too
> V2Wizard: revert add alert on snapshot step

- src/Components/Blueprints/BlueprintActionsMenu.tsx
- src/Components/sharedComponents/ImageBuilderHeader.tsx
- src/Router.tsx
- src/Utilities/useGetEnvironment.ts
Adds ability to enable a feature flag in Ephemeral environment by default.
> Blueprint: enable import/export in ephemeral

- src/Components/CreateImageWizardV2/CreateImageWizard.tsx
- src/test/Components/CreateImageWizardV2/EditImageWizard.test.tsx
- src/test/fixtures/blueprints.ts
> Wizard: enable nav items properly in Edit mode

- src/test/setup.ts
This silences the DOM dump logged into test output by testing-library while keeping all the relevant information about the test failure in the output.
New error
```bash
FAIL  src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx > oscap > remove a profile
TestingLibraryElementError: Unable to find role="textbox" and name `/I broke this test on purpose/i`
❯ waitForWrapper node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1133:27
1135| /*
1136| eslint
1137|   max-lines-per-function: ["error", {"max": 200}],
|         ^
1138| */
1139| 
❯ node_modules/@testing-library/dom/dist/@testing-library/dom.esm.js:1213:12
❯ selectNone src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:85:46
❯ src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx:153:1 …
```
> test: Silence the DOM dump in test output

- src/test/setup.ts
Cleans up polyfills that doesn't seem to be needed anymore :)
> test: cleanup unnecessary polyfills

- package-lock.json
- package.json
- src/mockServiceWorker.js
This manually bumps msw from 2.3.1 to 2.3.2
> devDeps: Bump msw from 2.3.1 to 2.3.2

- README.md
This updates Jest to Vitest in Test Guidelines section of README.
> README: Update Jest to Vitest

- README.md
This updates instructions for local development.
> README: Update readme after migrating to fec.config.js

- src/Components/ImagesTable/ImagesTable.tsx
this commit add link to parent blueprint from specific image
> imageTable: link images to parent blueprint <HMS-4353>

- src/Components/CreateImageWizard/steps/Snapshot/Snapshot.tsx
> Fix typo in Snapshot step

- src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
When looking at the registration step I noticed that there was a missing article. So here's a tiny fix!
> wizard/registration: Add missing article (typo)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/FirstBoot/index.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
Shebang needs to be defined in the script, otherwise it fails to execute with weird errors.
This makes sure we validate this for User, to surface this info to them.
> Firstboot: validate shebang is defined (HMS-4458)

- deploy/iqe-trigger-integration.yml
I think it's causing issues with test_compose_clone so I want to try increasing the timeout.
> templates/testing: Increase timeout for selenium session

- src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/fixtures/repositories.ts
If repositories are disabled, don't select them via bulk select.
https://github.com/user-attachments/assets/d64bf5ca-62cb-441c-a59f-d642d9c6ed92
> Wizard: disable bulk select when appropriate

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/Components/CreateImageWizard/EditImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
When switching between preview and non-preview the Wizard nav got messy. This should fix the problem.
> Wizard: Fix death by thousand reviews (HMS-4513)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
Replace conditional rendering with `isHidden` for snapshotting step.
> Wizard: Add `isHidden` to snapshotting step

- api/schema/imageBuilder.yaml
- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/Components/ImagesTable/ImagesTableToolbar.tsx
- src/Components/ImagesTable/Release.tsx
- src/store/imageBuilderApi.ts
- src/test/fixtures/blueprints.ts
This updates image-builder API by running `npm run api` and addresses problems caused by the update.
> api: Update image-builder API

- src/Components/CreateImageWizard/steps/Packages/Packages.tsx
- src/Components/CreateImageWizard/steps/Repositories/RepositoriesStatus.tsx
- src/Components/CreateImageWizard/steps/Repositories/RepositoryUnavailable.tsx
- src/Components/CreateImageWizard/steps/Repositories/components/Empty.tsx
- src/Components/CreateImageWizard/steps/Repositories/index.tsx
- src/Components/CreateImageWizard/steps/Snapshot/index.tsx
- src/Components/CreateImageWizard/utilities/betaPath.ts
`/preview` is no longer used in url.
> Wizard: Update docs after move to new preview (HMS-4513)

- src/Components/Blueprints/BlueprintDiffModal.tsx
- src/Components/Blueprints/BuildImagesButton.tsx
> Bluperint: Allow selecting targets from diff modal

- src/Components/sharedComponents/ImageBuilderHeader.tsx
I received the mocks, so after the discussion about putting the preview label, I am doing so. :)
> blueprint: Add preview label to import button

- src/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/test/Components/Blueprints/Blueprints.test.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.azure.test.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.compliance.test.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.content.test.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/EditImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/Components/ImagesTable/ImagesTable.test.tsx
- src/test/Components/LandingPage/LandingPage.test.tsx
- src/test/Components/ShareImageModal/ShareImageModal.test.tsx
- src/test/Components/edge/EdgeImagesTable.test.tsx
- src/test/Components/edge/ImageDetails.test.tsx
- src/test/setup.ts
This moves all the mocks used throughout our test files into the test setup file.
> test: Move mocks to setup file

- package-lock.json
- package.json
- src/Components/Blueprints/BlueprintActionsMenu.tsx
- src/Components/Blueprints/BlueprintVersionFilter.tsx
- src/Components/Blueprints/BlueprintsPagination.tsx
- src/Components/Blueprints/BuildImagesButton.tsx
- src/Components/Blueprints/ImportBlueprintModal.tsx
- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/ImagesTable/Instance.tsx
- src/Components/ShareImageModal/RegionsSelect.tsx
This bumps ts-patch and updates PF imports where needed.
> devDeps, src: Bump ts-patch and update imports

- src/Components/CreateImageWizard/steps/Details/index.tsx
- src/Components/CreateImageWizard/utilities/generateDefaultName.ts
- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/wizardTestUtils.tsx
this commit add default name for blueprint name field to be able
to create an image without filling any name
format name: "$OS $ARCH $TARGETS $DATE".
> createImage : add default name in details step <HMS-4494>

- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
this commit move relevant tests from createImageWizard to fileSystem test
> test: move relevant tests from createImageWizard to fileSystem

- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
This cleans up FSC test file a bit after tests were moved here from `CreateImageWizard.test.tsx`.
> test: Clean up FSC tests

- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
This cleans up Registration tests and re-enables "clicking Cancel loads landing page" test.
> test: Clean up Registration tests and enable a test

- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
This cleans up AWS test file after relevant tests were moved there from `CreateImageWizard.test.tsx`.
> test: Clean up AWS tests

- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
This cleans up GCP test file after relevant tests were moved there from `CreateImageWizard.test.tsx`.
> test: Clean up GCP tests

- src/Components/Blueprints/BlueprintDiffModal.tsx
- src/Components/Blueprints/BuildImagesButton.tsx
For the diff modal, we want to change the button label.
In this context Synchronize images is more appropriate label.
Why: Kelsea asked me to! :)
> Blueprints: change diff modal button label

- src/Components/CreateImageWizard/steps/Details/index.tsx
- src/Components/CreateImageWizard/utilities/generateDefaultName.ts
this commit change the default name to different format 
`<release>-<arch>-<date>-<time>`
> createImageWizard: change the default name of bllueprint

- pr_check.sh
Compliance needs the limits/requests to be set correctly.
> pr_check: don't overwrite resource limits

- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
this commit moves Review tests to specific folder
> test: move Review tests to specific folder (HMS-4658)

- .github/workflows/dev-checks.yml
- vitest.config.ts
this commit add the configuration for codecov,
to be able to see the coverage of vitest in codecov website.
> codecov: enable codecov in our repo

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.3.5 to 2.4.1
> devDeps: Manual bump msw from 2.3.5 to 2.4.1

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/Components/CreateImageWizard/wizardTestUtils.tsx
This adds an "Optional steps" section to the Wizard and moves all the non-mandatory customisation options there. "Review and finish" button was also added to allow jumping through the optional section.
> Wizard: Optional steps (HMS-4589)

- api/config/imageBuilder.ts
- src/Components/Blueprints/BlueprintActionsMenu.tsx
- src/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/Components/Blueprints/ImportBlueprintModal.tsx
- src/Components/CreateImageWizard/steps/Packages/Packages.tsx
- src/Components/CreateImageWizard/steps/Review/Footer/CreateDropdown.tsx
- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/store/imageBuilderApi.ts
- src/store/wizardSlice.ts
- src/test/Components/Blueprints/Blueprints.test.tsx
We have a new export endpoint, that I used here.
I also incorporated some kind of change for centos-8 that was pulled from the API, and is not relevant. :thinking:
> Export: Use export endpoint (HMS-4459)

- pr_check.sh
This was suggested to us as fix for the deployment
> pr_check: remove resources for notifications

- src/test/Components/Blueprints/Blueprints.test.tsx
This is the followup we mentioned [here](https://github.com/osbuild/image-builder-frontend/pull/2292#discussion_r1726471390
). :)
> test: Remove local mocking of chrome and unleash

- src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
This cleans up Review tests by replacing block of code by helper functions where possible.
The last two tests were updated so that their descriptions match what the tests do.
> test: Cleanup Review tests (HMS-4658)

- src/constants.ts
This updates the documentation link.
> Wizard: Update documentation link

- src/constants.ts
This updates other incorrect links on the page.
> constants: Update documentation links

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.4.4 to 2.4.9
> devDeps: Manually bump msw from 2.4.4 to 2.4.9

- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This updates previously incorrect aria labels for VMware popovers.
> Wizard: Fix incorrect aria labels

- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
The incorrect "registration" name is bothering me. Also updated the name of the first describe block to match the pattern we have in other test files.
> test: Update test naming

- api/pull.sh
- api/schema/compliance.json
- api/schema/contentSources.json
- src/store/contentSourcesApi.ts
Some changes are still missing, but let's get this in so that we will not have a huge PR later. :)
> update compliance and content sources api

- README.md
> readme: add links

- .github/workflows/dev-checks.yml
The codecov comments don't make much sense as there's no reference point currently.
> .github/workflows: run dev checks on main

- src/Components/CreateImageWizard/CreateImageWizard.tsx
Let's expose compliance in preview while we're ironing out the creases.
> Wizard: only show compliance radio in preview

- api/schema/compliance.json
- api/schema/contentSources.json
run `npm run api` to update the content-sources spec
> 'api: update content-sources spec

- package-lock.json
- package.json
- src/mockServiceWorker.js
Bumps msw from 2.4.9 to 2.4.10.
> devDeps: Manual bump msw from 2.4.9 to 2.4.10

- api/schema/imageBuilder.yaml
- package-lock.json
- package.json
- src/store/complianceApi.ts
- src/store/imageBuilderApi.ts
- src/store/provisioningApi.ts
This bumps @rtk-query/codegen-openapi from 1.2.0 to 2.0.0
> devDeps: Manually bump @rtk-query/codegen-openapi

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps bump msw from 2.4.10 to 2.6.0
> devDeps: Manually bump msw from 2.4.10 to 2.6.0

- fec.config.js
- package-lock.json
- package.json
This will enable unminified stacktraces in sentry.
---
We might need to change the snetry project first, so don't merge yet.
> fec: add sentry plugin

- tsconfig.json
Generate source maps for typescript files, otherwise the trace will be mostly missing.
> tsconfig.json: generate sourcemaps for typescript files

- package-lock.json
- package.json
This makes 5.4.1 the version for all Patternfly deps.
> deps: Patternfly deps to version 5.4.1

- fec.config.js
moduleMetadata is  supported officially.
> fec.config: tweak sentry config

- api/schema/imageBuilder.yaml
- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx
- src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx
- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/Components/ImagesTable/Release.tsx
- src/Utilities/isRhel.ts
- src/constants.ts
- src/store/imageBuilderApi.ts
> Rhel 10 beta (HMS-5011)

- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This prefetches the list of activation keys upon entering the Wizard, making the loading times on the Registration step better for the user.
> Wizard: Prefetch the list of activation keys on Image output step

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Timezone/components/TimezoneDropDown.tsx
- src/Components/CreateImageWizard/steps/Timezone/index.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
- src/test/setup.ts
This adds bare bones Timezone step with appropriate file structure and basic unit tests.
> Wizard: Basic Timezone step (HMS-5009)

- src/Components/CreateImageWizard/ValidatedTextInput.tsx
- src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx
This is a small follow-up to add a warning to our minimum size bug fix. :) Let me know what you think about the message.
> Wizard: add warning for the min size in bytes

- src/Components/CreateImageWizard/CreateImageWizard.tsx
Feature flags can be constrained to preview / stable.
> Wizard: rely on feature flag constraints for openscap step title

- api/schema/imageBuilder.yaml
- src/Components/ImagesTable/Release.tsx
- src/store/imageBuilderApi.ts
> ImagesTable: add RHEL 9.5 display value

- pr_check.sh
We don't have any tests marked for parallel execution.
> pr_check: disable IQE parallel execution

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.6.0 to 2.6.6
> devDeps: Manually bump msw from 2.6.0 to 2.6.6

- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx
This adds Locale expandable to the Review step.
> Wizard: LOCALE - Add Locale to Review step (HMS-5098)

- src/Components/Blueprints/ImportBlueprintModal.test.tsx
This checks if specified packages get selected when importing a toml blueprint.
> test: Packages selected on import (HMS-5166)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Hostname/components/HostnameInput.tsx
- src/Components/CreateImageWizard/steps/Hostname/index.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
- src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
- src/test/setup.ts
This adds Hostname step basics and file structure. The new unleash flag is called `image-builder.hostname.enabled`.
> Wizard: Basic Hostname step (HMS-5167)

- src/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
This adds hostname to on-prem mapper and updates a test that checks if the value got parsed correctly.<br/><br/>JIRA: [HMS-5183](https://issues.redhat.com/browse/HMS-5183)
> Wizard: Add hostname to on-prem mapper (HMS-5183)

- src/Components/CreateImageWizard/ChippingInput.tsx
- src/Components/CreateImageWizard/steps/Timezone/components/NtpServersInput.tsx
This extracts input with chips from the NTP servers into a separate reusable ChippingInput component.
JIRA: [HMS-5193](https://issues.redhat.com/browse/HMS-5193)
> Wizard: Extract ChippingInput to reusable component (HMS-5193)

- src/Components/CreateImageWizard/steps/Repositories/RepositoriesStatus.tsx
- src/Components/ImagesTable/Status.tsx
Fixes #2612
This replaces the `<InProgressIcon>` with animated spinners to indicate that something is happening.
JIRA: [HMS-5239](https://issues.redhat.com/browse/HMS-5239)
> src: Make spinners spin (HMS-5239)

- src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/constants.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
- src/test/fixtures/editMode.ts
this commit adds ssh_key to users step
> wizard: add ssh_key to users step (HMS-4903)

- src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
- src/store/wizardSlice.ts
this commit add confirm password to users step
> wizard: add confirm password to users step (HMS-4903)

- src/Components/ImagesTable/ImagesTableToolbar.tsx
"All images" should change to "<blueprint_name> images" when a blueprint is selected.
JIRA: [HMS-5282](https://issues.redhat.com/browse/HMS-5282)
> ImagesTable: Fix images header (HMS-5282)

- src/Components/ImagesTable/ImagesTable.tsx
This fixes the "All versions" / "Newest" filter in the blueprint images table.
JIRA: [HMS-5281](https://issues.redhat.com/browse/HMS-5281)
> ImagesTable: Fix version filter (HMS-5281)

- api/schema/compliance.json
this commit adds the latest changes in api schema
> api: add latest changes in api

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Firewall/index.tsx
- src/test/Components/CreateImageWizard/steps/Details/Details.test.tsx
- src/test/Components/CreateImageWizard/steps/FileSystemConfiguration/FileSystemConfiguration.test.tsx
- src/test/Components/CreateImageWizard/steps/Firewall/Firewall.test.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/Hostname/Hostname.test.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
- src/test/Components/CreateImageWizard/steps/Locale/Locale.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Packages/Packages.test.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/steps/Repositories/Repositories.test.tsx
- src/test/Components/CreateImageWizard/steps/Review/Review.test.tsx
- src/test/Components/CreateImageWizard/steps/Snapshot/Snapshot.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/GCPTarget.test.tsx
- src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
- src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
- src/test/setup.ts
First step. 
Todo:
/jira-epic HMS-5168<br/><br/>JIRA: [HMS-5169](https://issues.redhat.com/browse/HMS-5169)
> Wizard: Firewall customization scaffolding (HMS-5169)

- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
this commit add ssh_key to review step under Users
JIRA: [HMS-5290](https://issues.redhat.com/browse/HMS-5290)
> wizard: add ssh_key to review step (HMS-5290)

- cockpit/cockpit-image-builder.spec
- packit.yaml
Ran through fedora-review, fixed some missing checks.
JIRA: [HMS-5325](https://issues.redhat.com/browse/HMS-5325)
> cockpit spec: review followup (HMS-5325)

- cockpit/cockpit-image-builder.spec
- packit.yaml
Required for releasing into rawhide.
JIRA: [HMS-5341](https://issues.redhat.com/browse/HMS-5341)
> Drop obsoletes in cockpit spec, and add build and release jobs to packit.yaml (HMS-5341)

- cockpit/cockpit-image-builder.spec
> cockpit/spec: post-release version bump

- .github/workflows/release.yml
> .github/workflows/release: fix make dist step

- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/test/Components/CreateImageWizard/steps/Timezone/Timezone.test.tsx
add condition that check if there is value in Hostname, Locale, Timezone steps
and if there is no value, we dont see the extendable part in review step 
FIX ISSUE: (#2718)
JIRA: [HMS-5337](https://issues.redhat.com/browse/HMS-5337)
> wizard: expand steps only if there are values in the step

- src/Components/CreateImageWizard/steps/Users/component/UserInfo.tsx
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizard/steps/Users/Users.test.tsx
this commit add remove user button in users step
JIRA: [HMS-5378](https://issues.redhat.com/browse/HMS-5378)
> Wizard: Add remove user button in users step (HMS-5378)

- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
This adds kernel to the on-prem mapper.
JIRA: [HMS-5384](https://issues.redhat.com/browse/HMS-5384)
> Blueprints: Add kernel to on-prem mapper (HMS-5384)

- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
This adds firewall to on-prem mapper.
JIRA: [HMS-5358](https://issues.redhat.com/browse/HMS-5358)
> Wizard: Add firewall to on-prem mapper (HMS-5358)

- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/store/wizardSlice.ts
this commit add administrator field to review step
JIRA: [HMS-5433](https://issues.redhat.com/browse/HMS-5433)
> Wizard: Add Administrator field to review step (HMS-5433)

- src/Components/CreateImageWizard/steps/Packages/index.tsx
- src/Components/ImagesTable/Instance.tsx
- src/store/cockpit/cockpitApi.ts
- package search alert
- basequery url fix
- compose request stringify
- local target status
> cockpit plugin: various fixes

- src/Components/ImagesTable/ImageBuildStatus.scss
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/ImagesTable/Status.tsx
Fixes #2762
This adds formatting to the status text, ensuring it's the same as on Repositories step.
JIRA: [HMS-5438](https://issues.redhat.com/browse/HMS-5438)
> ImagesTable: Format status text (HMS-5438)

- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
this adds users to on-prem mapper.
JIRA: [HMS-5436](https://issues.redhat.com/browse/HMS-5436)
> Wizard: Add users to on-prem mapper (HMS-5436)

- README.md
This updates the scripts used to run prod and stage locally.
> README: Update scripts for running prod and stage

- .eslintignore
- api/codegen.sh
- api/config/composerCloudApi.ts
- api/pull.sh
- api/schema/composerCloudApi.v2.yaml
- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
- src/Components/ImagesTable/Instance.tsx
- src/store/cockpit/composerCloudApi.ts
- src/store/cockpit/emptyComposerCloudApi.ts
Just to use the types where appropriate, not to actually make any queries.
JIRA: [HMS-5465](https://issues.redhat.com/browse/HMS-5465)
> api: add composer's cloudapi (HMS-5465)

- src/Components/CreateImageWizard/validators.ts
After the regex was fixed this condition should be removed.
JIRA: [HMS-5464](https://issues.redhat.com/browse/HMS-5464)
> validators: Remove unneeded condition for service validator (HMS-5464)

- src/store/cockpit/enhancedCockpitApi.ts
JIRA: [HMS-5467](https://issues.redhat.com/browse/HMS-5467)
> store/cockpit: Add notifications for blueprints (HMS-5467)

- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
this changes password to **** if there is value in password field
> Wizard: change password to **** if there is value in password field

- src/Components/CreateImageWizard/steps/Oscap/OscapProfileInformation.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
This gates the visibility of services on the OpenSCAP step behing a flag.
JIRA: [HMS-5406](https://issues.redhat.com/browse/HMS-5406)
> Wizard: Gate services on OpenSCAP step behind flag (HMS-5406)

- .github/dependabot.yml
The issues are resolved, let's get back to just three open pull requests at one time.
JIRA: [HMS-5492](https://issues.redhat.com/browse/HMS-5492)
> dependabot: Return limit to 3 PRs at once (HMS-5492)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizard/steps/Review/index.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Compliance.test.tsx
- src/test/setup.ts
Snapshotting is available in prod-stable now. We can probably remove the fallthrough logic now.
JIRA: [HMS-5460](https://issues.redhat.com/browse/HMS-5460)
> src: Remove snapshots fallthrough logic (HMS-5460)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/Locale/components/KeyboardDropDown.tsx
- src/Components/CreateImageWizard/steps/Locale/components/LanguagesDropDown.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
This adds step validation to Locale, allowing to properly validate imported values.
JIRA: [HMS-5505](https://issues.redhat.com/browse/HMS-5505)
> Wizard: Add step validation to Locale (HMS-5505)

- src/Components/Blueprints/ImportBlueprintModal.tsx
Fixed #2905
Fixes error rendering when invalid blueprint is uploaded.
JIRA: [HMS-5528](https://issues.redhat.com/browse/HMS-5528)
> Blueprints: Import Blueprint modal error rendering (HMS-5528)

- .github/workflows/trigger-gitlab.yml
Made some silly mistakes copying over from composer.
> Fix trigger-gitlab workflow

- src/Components/Blueprints/ImportBlueprintModal.tsx
Fixed #2919
Error message has error variant when uploading invalid blueprint.
JIRA: [HMS-5555](https://issues.redhat.com/browse/HMS-5555)
> Blueprints: invalid message variant on upload (HMS-5555)

- src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx
Fixed #2865
OpenSCAP profile page clears after selecting "None" or "X" in the dropdown.
JIRA: [HMS-5558](https://issues.redhat.com/browse/HMS-5558)
> Wizard: reseting page to default state (HMS-5558)

- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizard/steps/Services/components/ServicesInputs.tsx
- src/Components/CreateImageWizard/steps/Services/index.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
This exposes masked services in the UI by adding a masked services input.
JIRA: [HMS-5561](https://issues.redhat.com/browse/HMS-5561)
> Wizard: Add masked services input (HMS-5561)

- src/Components/LandingPage/NewAlert.tsx
This updates `NewAlert` to inform about new customizations available in Images.
Local storage item name was also updated.
JIRA: [HMS-5562](https://issues.redhat.com/browse/HMS-5562)
>  LandingPage: Add NewAlert for added customizations (HMS-5562)

- src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx
Fixes #2910
Indentation of manual file system configuration in the review step of the wizard was aligned.
JIRA: [HMS-5564](https://issues.redhat.com/browse/HMS-5564)
> Wizard: fix indentation of manual file system config (HMS-5564)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
Fixes #2947
Optional steps get clickable after Register step was visited.
JIRA: [HMS-5584](https://issues.redhat.com/browse/HMS-5584)
> Wizard: make optional steps clickable (HMS-5584)

- package.json
- playwright/lib/lib.ts
- playwright/test.spec.ts
This add the `playwright` folder to the lint script and fixes errors.
> playwright: Add playwright to ESLint and fix errors

- src/Components/CreateImageWizard/steps/Kernel/components/KernelName.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/Components/CreateImageWizard/validators.ts
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx
This fixes problems with kernel step validation and adds a new test that checks validation of steps on import.
JIRA: [HMS-5582](https://issues.redhat.com/browse/HMS-5582)
> Wizard: Fix kernel validation and add import validation test (HMS-5582)

- src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
- src/constants.ts
This updates activation keys URL to behave the same way the content one does.
JIRA: [HMS-5642](https://issues.redhat.com/browse/HMS-5642)
> Wizard: Fix activation keys URL (HMS-5642)

- .github/workflows/playwright.yml
Change trigger of Playwright workflow from finishing development checks to trigger on pull requests.
JIRA: [HMS-5658](https://issues.redhat.com/browse/HMS-5658)
> tests/CI: Change Playwright workflow trigger to pull_request (HMS-5658)

- src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx
- src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AzureTarget.test.tsx
This replaces deprecated selects on the Azure step for non-deprecated ones.
JIRA: [HMS-5655](https://issues.redhat.com/browse/HMS-5655)
> Wizard: Replace deprecated selects on Azure step (HMS-5655)

- .github/workflows/playwright.yml
- package-lock.json
- package.json
- playwright.config.ts
- schutzbot/playwright_tests.sh
This adds currents reporter for Playwright tests
JIRA: [HMS-5660](https://issues.redhat.com/browse/HMS-5660)
> Add currents reporter for Playwright tests (HMS-5660)

- playwright/lib/lib.ts
This adds a helper function that switches into preview.
Heavily inspired by and all credit due to `content-sources-playwright`.
JIRA: [HMS-5667](https://issues.redhat.com/browse/HMS-5667)
> playwright: Add `togglePreview` helper function (HMS-5667)

- src/Components/CreateImageWizard/steps/Oscap/index.tsx
- src/constants.ts
This switches from a full path to a partial one, making the compliance url work properly in local dev environment.
JIRA: [HMS-5673](https://issues.redhat.com/browse/HMS-5673)
> Wizard: Compliance URL via suffix (HMS-5673)

- src/Components/CreateImageWizard/ValidatedInput.tsx
- src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
This commit refactors the Minimun size field by replacing HookValidatedInput with the new ValidatedInputAndTextArea component. It fixes a bug where the error icon remained visible after the user cleared the value in the field.
> Wizard: Refactor Minimum Size input in File system step

- .tekton/image-builder-frontend-pull-request.yaml
- .tekton/image-builder-frontend-push.yaml
New required tasks by April 1st
> ci: add required SAST tasks to Konflux pipelintes

- src/Components/CreateImageWizard/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/test/Components/CreateImageWizard/CreateImageWizard.test.tsx
- src/test/Components/CreateImageWizard/steps/TargetEnvironment/AwsTarget.test.tsx
This replaces a deprecated select in `AwsSourcesSelect` for a non-deprecated one.
JIRA: [HMS-5622](https://issues.redhat.com/browse/HMS-5622)
> Wizard: Replace deprecated select in `AwsSourcesSelect` (HMS-5622)

- src/Components/CreateImageWizard/steps/Locale/index.tsx
This updates microcopy on Locale step as suggested in the linked bug report.
HMS: [HMS-5656](https://issues.redhat.com/browse/HMS-5656)
> Wizard: Update microcopy on Locale step (HMS-5656)

- src/Components/CreateImageWizard/CreateImageWizard.tsx
Optional steps are now clickable on prem as well :) 
JIRA: [HMS-5852](https://issues.redhat.com/browse/HMS-5852)
> Wizard: make optional steps clickable on prem (HMS-5852)

- src/Components/CreateImageWizard/steps/Registration/SatelliteRegistration.tsx
- src/Components/CreateImageWizard/steps/Registration/components/SatelliteRegistrationCommand.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizard/utilities/certificates.ts
- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/constants.ts
- src/store/wizardSlice.ts
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/Components/CreateImageWizard/wizardTestUtils.tsx
- src/test/fixtures/customizations.ts
- src/test/setup.ts
Yooo! So this is the Satellite followup. Basically, after inserting the following Satellite command and Certificate:
<details>
<summary>Satellite command</summary>
```
set -o pipefail && curl -sS ‘https://ec2-107-23-89.compute-1.amazonaws.com/register?activation_keys=ak&location_id=2&organization_id=1&update_packages=false’ -H ‘Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZGVtb1VzZXIiLCJleHAiOjMwMDAwMDAwMDB9.XYZ123ABC456DEF789GHI012JKL345MNO678PQR901 | bash
```
</details>
<details>
<summary>Certificate</summary>
```
-----BEGIN CERTIFICATE-----
MIIDUDCCAjigAwIBAgIUIE7ftn9J9krO6TRJg8M3plAZGgEwDQYJKoZIhvcNAQEL
BQAwYjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExFjAUBgNVBAcM
DVNhbiBGcmFuY2lzY28xETAPBgNVBAoMCFRlc3QgT3JnMRMwEQYDVQQDDAp0ZXN0 …
```
> Satellite registration followup

- .github/workflows/playwright.yml
SSIA
---
Did a run which retains all videos, as you can see a new user is used: https://app.currents.dev/i/wGpgxSmts5YdAWYi/test/b72ba50710186a3d173d-736ee36bae07ab26c41c?testExplorerTab=attempts
> .github: new stage user on each playwright run

- src/Components/LandingPage/NewAlert.tsx
This adds newly available customizations to the new alert on Landing Page.
JIRA: [HMS-6022](https://issues.redhat.com/browse/HMS-6022)
> LandingPage: Update alert with new customizations (HMS-6022)

- playwright.config.ts
This lowers the number of workers from 4 to 2.
> playwright: Decrease number of workers

- src/Components/ImagesTable/ImageDetails.tsx
- src/Components/ImagesTable/Instance.tsx
- src/Components/ImagesTable/Status.tsx
I noticed that we have this ongoing trend in the codebase of using "else" block after return in the `if`. Let's make sure we do not add more; I tried to fix a few in ImagesTable; more will likely come later. I wanted to prevent big PR and conflicts with other PRs. :)
> ImagesTable: remove else after return

- src/Components/Blueprints/BlueprintsSideBar.tsx
- src/Components/Blueprints/BuildImagesButton.tsx
- src/Components/Blueprints/ImportBlueprintModal.tsx
- src/Components/CreateImageWizard/steps/FileSystem/FileSystemConfiguration.tsx
- src/Components/CreateImageWizard/steps/FirstBoot/index.tsx
- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
- src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx
- src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx
- src/Components/CreateImageWizard/steps/Packages/PackageRecommendations.tsx
- src/Components/CreateImageWizard/steps/Packages/Packages.tsx
- src/Components/CreateImageWizard/steps/Registration/ActivationKeyInformation.tsx
- src/Components/CreateImageWizard/steps/Registration/ActivationKeysList.tsx
- src/Components/CreateImageWizard/steps/Registration/Registration.tsx
- src/Components/CreateImageWizard/steps/Registration/components/PopoverActivation.tsx
- src/Components/CreateImageWizard/steps/Repositories/Repositories.tsx
- src/Components/CreateImageWizard/steps/Review/Footer/Footer.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTables.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizard/steps/Snapshot/components/Templates.tsx
- src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureResourceGroups.tsx
- src/Components/CreateImageWizard/steps/TargetEnvironment/Azure/AzureSourcesSelect.tsx
- src/Components/CreateImageWizard/steps/TargetEnvironment/Gcp/index.tsx
- src/Components/ImagesTable/EmptyState.tsx
- src/Components/sharedComponents/ImageBuilderHeader.tsx
This removes unused `data-testid`s from the code base.
JIRA: [HMS-6148](https://issues.redhat.com/browse/HMS-6148)
> src: Remove unused `data-testid`s (HMS-6148)

- playwright/Customizations/Firewall.spec.ts
Playwright test to the firewall step in Wizard :mage:
> Wizard: add Firewall test (HMS-5974)

- src/Components/CreateImageWizard/utilities/requestMapper.ts
Lukas was right that this was a bug. Let's get this in:)
> Wizard: fix Satellite registration cmd not found

- src/Components/CreateImageWizard/steps/TargetEnvironment/Aws/AwsSourcesSelect.tsx
Same issue as in #3220. The list of sources did refetch, but did not re-render.
JIRA: [HMS-6298](https://issues.redhat.com/browse/HMS-6298)
> Wizard: Update AWS sources filtering (HMS-6298)

- src/Components/LandingPage/NewAlert.tsx
This adds Users to the list of new customization options.
> LandingPage: Add Users to `NewAlert`

- src/Components/CreateImageWizard/steps/Packages/Packages.tsx
If there's a package stream for both packages and modules, this will render it.
JIRA: [HMS-6311](https://issues.redhat.com/browse/HMS-6311)
> Wizard: Add package streams (HMS-6311)

- api/schema/imageBuilder.yaml
- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/ImageOutput/ReleaseSelect.tsx
- src/Components/CreateImageWizard/steps/Oscap/Oscap.tsx
- src/Components/CreateImageWizard/steps/Oscap/index.tsx
- src/Components/ImagesTable/Release.tsx
- src/constants.ts
- src/store/service/imageBuilderApi.ts
Hides the compliance step until we get the security guides in order.
> Add el10 releases

- api/schema/compliance.json
- api/schema/composerCloudApi.v2.yaml
- api/schema/imageBuilder.yaml
- src/store/cockpit/composerCloudApi.ts
- src/store/service/imageBuilderApi.ts
> API: update api

- src/Components/CreateImageWizard/utilities/useValidation.tsx
- src/test/Components/CreateImageWizard/steps/Registration/Registration.test.tsx
- src/test/fixtures/customizations.ts
The token does not need expiration date.
> Wizard: fix token not having expiration fails

- src/Components/CreateImageWizard/steps/Packages/Packages.tsx
Unpack sources for both modules and packages.
> Wizard: Sources for all

- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
Until we get our accounts back, there's nothing we can do here.
---
> Wizard: temporarily disable OCI (HMS-8569)

- src/Components/CreateImageWizard/steps/Users/components/UserInfo.tsx
- src/Components/CreateImageWizard/utilities/useValidation.tsx
Fixes: #3097
Added exclamation marks to the tabs where the user contains error.
JIRA: [HMS-8640](https://issues.redhat.com/browse/HMS-8640)
> Wizard: indicate which user tab contains error (HMS-8640)

- src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx
- src/Components/CreateImageWizard/steps/FirstBoot/index.tsx
I decided to split these into smaller PRs, as it is easy to create conflicts with these kinds of refactoring
> Remove elses after return

- cockpit/public/index.html
- cockpit/webpack.config.ts
- src/AppCockpit.scss
- src/AppCockpit.tsx
- src/Components/CreateImageWizard/steps/FileSystem/FileSystemTable.tsx
- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
- src/Components/CreateImageWizard/steps/Oscap/components/OscapProfileInformation.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.scss
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/ImagesTable/Status.tsx
- src/Components/sharedComponents/ImageBuilderHeader.tsx
The PF6 migration did not completely work for the on-prem version of the frontend. This PR
makes the necessary fixes for this.
> migrate on-prem to PF6 (HMS-8644)

- src/Components/CreateImageWizard/steps/ImageOutput/TargetEnvironment.tsx
This reverts commit efed39d, manual revert was needed as the tile were migrated to cards in the meantime.
> Manually revert "Wizard: temporarily disable OCI"

- src/Components/CreateImageWizard/steps/Oscap/components/PolicySelector.tsx
- src/Components/CreateImageWizard/steps/Oscap/components/ProfileSelector.tsx
- src/test/Components/CreateImageWizard/steps/FirstBoot/Firstboot.test.tsx
- src/test/Components/CreateImageWizard/steps/Kernel/Kernel.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Compliance.test.tsx
- src/test/Components/CreateImageWizard/steps/Oscap/Oscap.test.tsx
- src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
Fixes #3082 
Fixes #3270
JIRA: [HMS-8633](https://issues.redhat.com/browse/HMS-8633)
> Wizard: Fix "None" options in Selects for policies and Oscap profiles (HMS-8633)

- playwright/Customizations/Kernel.spec.ts
This adds a test for kernel customizations - adding, removing and changing kernel arguments.
Jira: [HMS-5973](https://issues.redhat.com/browse/HMS-5973)
> Test: add Kernel customizations test (HMS-5973)

- src/Components/CreateImageWizard/utilities/requestMapper.ts
- src/constants.ts
- src/test/Components/Blueprints/ImportBlueprintModal.test.tsx
- src/test/fixtures/editMode.ts
This PR adds some constants for our used paths in order to prevent typos in it, and make it easier to refactor later, when we need to.
Also some indentation that was not needed was removed.
> Cleanup mapper

- src/Components/CreateImageWizard/steps/Firewall/components/Services.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
- src/Components/CreateImageWizard/steps/Services/components/ServicesInputs.tsx
- src/test/Components/CreateImageWizard/steps/Services/Services.test.tsx
Changes the order of services in the systemd step we found confusing in Justin's demo
JIRA: [HMS-8687](https://issues.redhat.com/browse/HMS-8687)
> Wizard: change order of the systemd services (HMS-8687)

- cockpit/README.md
I wanted to have an initial version so we can reference it (e.g. from osbuild.org).
Feel free to rephrase or add more details (within my PR or just as a comment and I'll incorporate)
> cockpit/README.md: initial version

- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/steps/FileSystem/components/FileSystemConfiguration.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
This hides FSC step when only WSL target is selected.
JIRA: [HMS-8758](https://issues.redhat.com/browse/HMS-8758)
> Wizard: Hide FSC step for WSL targets (HMS-8758)

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.10.2 to 2.10.3
> devDeps: Bump msw from 2.10.2 to 2.10.3

- src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/ImagesTable/Instance.tsx
- src/test/Components/CreateImageWizard/steps/ImageOutput/ImageOutput.test.tsx
This updates WSL file extension from `.tar.gz` to `.wsl`
JIRA: [HMS-8827](https://issues.redhat.com/browse/HMS-8827)
> Wizard: Change WSL file extension (HMS-8827)

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.10.3 to 2.10.4
JIRA: [HMS-8864](https://issues.redhat.com/browse/HMS-8864)
> devDeps: Bump msw from 2.10.3 to 2.10.4 (HMS-8864)

- src/store/cockpit/composerCloudApi.ts
- src/store/service/imageBuilderApi.ts
This adds changes from `npm api`.
JIRA: [HMS-8938](https://issues.redhat.com/browse/HMS-8938)
> Update API (HMS-8938)

- src/Components/Blueprints/BlueprintsSideBar.tsx
- src/Components/Blueprints/helpers/onPremToHostedBlueprintMapper.tsx
- src/Components/CreateImageWizard/CreateImageWizard.tsx
- src/Components/CreateImageWizard/ImportImageWizard.tsx
- src/Components/CreateImageWizard/validators.ts
- src/Components/ImagesTable/ImagesTable.tsx
- src/Components/ImagesTable/ImagesTableToolbar.tsx
- src/Components/ImagesTable/Instance.tsx
This fixes lint warnings in:
- `Components/ImagesTable`
- `Components/Blueprints`
- `Components/CreateImageWizard`, warnings in `/steps` and `/utilities` sub-directories still need to be resolved.
JIRA: [HMS-9007](https://issues.redhat.com/browse/HMS-9007)
> src: Fix more lint warnings (HMS-9007)

- src/Components/CreateImageWizard/steps/ImageOutput/components/TargetEnvironment.tsx
Assets were renamed, this updates naming and fixes logos.
JIRA: [HMS-9009](https://issues.redhat.com/browse/HMS-9009)
> Wizard: Update public cloud logo links (HMS-9009)

- playwright/test.spec.ts
- src/Components/CreateImageWizard/steps/Review/ReviewStep.tsx
- src/Components/CreateImageWizard/steps/Review/ReviewStepTextLists.tsx
Hide some of the steps in the review step that aren't applicable to the cockpit frontend.
JIRA: [HMS-9031](https://issues.redhat.com/browse/HMS-9031)
> Wizard: hide some review items for cockpit frontend (HMS-9031)

- package-lock.json
- package.json
- src/mockServiceWorker.js
This bumps msw from 2.10.4 to 2.10.5
JIRA: [HMS-9088](https://issues.redhat.com/browse/HMS-9088)
> devDeps: Bump msw from 2.10.4 to 2.10.5 (HMS-9088)

- .github/workflows/pr_best_practices.yml
This trigger allows the bot to automatically create a Jira task from a newly opened issue
/jira-epic HMS-9196
JIRA: [HMS-9464](https://issues.redhat.com/browse/HMS-9464)
> workflow: add issues.opened trigger to pr_best_practices (HMS-9464)
